unpackaged/main/default/objects/CRM_Project__c/CRM_Project__c.object-meta.xml
<CustomObject>
    <label>Customer Project</label>
    <nameField>
        <label>Customer Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRM_Project__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>CRM Project</relationshipLabel>
    <relationshipName>CRM_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CRM_Project__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Name</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>CRM Project</relationshipLabel>
    <relationshipName>CRM_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/CRM_Project__c/fields/Project_Type__c.field-meta.xml
<CustomField>
    <fullName>Project_Type__c</fullName>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring Implementation</fullName>
            </value>
            <value>
                <fullName>Monitoring Decommissioning</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Drive O&amp;M</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CRM_Project__c/fields/Project_visibility__c.field-meta.xml
<CustomField>
    <fullName>Project_visibility__c</fullName>
    <label>Project visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visible to customer</fullName>
            </value>
            <value>
                <fullName>Not visible to customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CrmProjectListView.cls
public with sharing class CrmProjectListView {

        @AuraEnabled
        public static List <CRM_Project__c> fetchDetails() {
            List<CRM_Project__c> ProjectList = new list<CRM_Project__c>();
            Projectlist=[SELECT Id, Name, Project_Name__c   ,Account__c,Project_Type__c, Program_Name__c,
                                        Project_visibility__c, Product__c  from CRM_Project__c where Project_visibility__c = 'Visible to customer' 

 ];
            system.debug('list:'  + Projectlist);
           
            return ProjectList;
        }
}