unpackaged/main/default/objects/CRM_Project__c/CRM_Project__c.object-meta.xml
<CustomObject>
    <label>Customer Project</label>
    <nameField>
        <label>Customer Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRM_Project__c/fields/Project_visibility__c.field-meta.xml
<CustomField>
    <fullName>Project_visibility__c</fullName>
    <label>Project visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visible to customer</fullName>
            </value>
            <value>
                <fullName>Not visible to customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SubmitApproval.cls
public with sharing  class SubmitApproval {

    @AuraEnabled
    public static list<CRM_Project__c> saveRec(string RecId){
        
        system.debug('Id: '+RecId); 
        list<CRM_Project__c> ListDetails =New list<CRM_Project__c>();
            for(CRM_Project__c appRec : [SELECT Id, Name,Approval_Status__c,Project_visibility__c	
                                        from CRM_Project__c where id =:RecId  ])
            {
                appRec.Approval_Status__c='Pending';
                ListDetails.add(appRec);
            }
             
            
        try{  
        update ListDetails; 
        }catch(exception e){
            
            throw new AuraException(e.getMessage());
        }
        system.debug('Id: '+RecId); 
        Return ListDetails;
    }
}