unpackaged/main/default/objects/CRM_Project__c/CRM_Project__c.object-meta.xml
<CustomObject>
    <label>Customer Project</label>
    <nameField>
        <label>Customer Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRM_Project__c/fields/Related_Projects__c.field-meta.xml
<CustomField>
    <fullName>Related_Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Cloud Coach Project</label>
    <referenceTo>project_cloud__Project__c</referenceTo>
    <relationshipLabel>CRM Project</relationshipLabel>
    <relationshipName>CRM_Project</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Related_Projects__c.field-meta.xml
<CustomField>
    <fullName>Related_Projects__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Project</label>
    <referenceTo>project_cloud__Project__c</referenceTo>
    <relationshipLabel>Projects (Related Projects)</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/CrmProjectListViewTest.cls
/**
 * The Test class for apex CrmProjectListView.   
 * @param  :  
 * @return :  
 */
@isTest
public class CrmProjectListViewTest {
    static testmethod void testAddProgram() {
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
        
        project_cloud__Project__c projectRecord = TestDataFactory.createCCProjectTemplate('Monitoring Implementation',accnt.Id);
        insert projectRecord;
        Test.startTest();
        	CrmProjectListView.fetchDetails();
        Test.stopTest();
        CRM_Project__c crmProcessed = [select Related_Projects__c from CRM_Project__c where Related_Projects__c =:projectRecord.Id];
        System.assertEquals(crmProcessed.Related_Projects__c,projectRecord.Id);
    }
}