unpackaged/main/default/objects/CRM_Project__c/CRM_Project__c.object-meta.xml
<CustomObject>
    <label>Customer Project</label>
    <nameField>
        <label>Customer Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Customer Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CRM_Project__c/fields/Project_visibility__c.field-meta.xml
<CustomField>
    <fullName>Project_visibility__c</fullName>
    <label>Project visibility</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Visible to customer</fullName>
            </value>
            <value>
                <fullName>Not visible to customer</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SubmitApprovalTest.cls
// Test Class for Submit
//
@istest
public class SubmitApprovalTest {
    @istest
    static void saveRecTest(){
        
        CRM_Project__c c= new CRM_Project__c(
            name='Testing1',
            Project_visibility__c='Visible to customer'
             );
        // inserting the project record 
        insert c;
        system.debug('crmId..:' +c);
        // to check the crm project id with the string id 
        string RecId =c.Id;
        SubmitApproval.saveRec(RecId);
        CRM_Project__c cc=[select id,name,Approval_Status__c,Project_visibility__c from CRM_Project__c where id=:RecId ];
        system.assertequals('Pending',cc.Approval_Status__c);
      
    }

}