unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/project_cloud__Project__c/fields/External_Status__c.field-meta.xml
<CustomField>
    <fullName>External_Status__c</fullName>
    <label>External Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Info collection</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Blocked</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <isActive>false</isActive>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Done</fullName>
                <isActive>false</isActive>
                <label>Done</label>
            </value>
            <value>
                <fullName>Inbox</fullName>
                <isActive>false</isActive>
                <label>Inbox</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Selected for Development</fullName>
                <isActive>false</isActive>
                <label>Selected for Development</label>
            </value>
            <value>
                <fullName>To Do</fullName>
                <isActive>false</isActive>
                <label>To Do</label>
            </value>
            <value>
                <fullName>Under Spec</fullName>
                <isActive>false</isActive>
                <label>Under Spec</label>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Won&#39;t do</fullName>
                <isActive>false</isActive>
                <label>Won&#39;t do</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Internal_Status__c.field-meta.xml
<CustomField>
    <fullName>Internal_Status__c</fullName>
    <label>Internal Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Inbox</fullName>
                <default>true</default>
                <label>Inbox</label>
            </value>
            <value>
                <fullName>Info collection</fullName>
            </value>
            <value>
                <fullName>Under construction / backlogged</fullName>
            </value>
            <value>
                <fullName>To Do</fullName>
            </value>
            <value>
                <fullName>In progress</fullName>
            </value>
            <value>
                <fullName>Blocked - Internal</fullName>
            </value>
            <value>
                <fullName>Blocked - Customer</fullName>
            </value>
            <value>
                <fullName>Blocked - 3rd party</fullName>
            </value>
            <value>
                <fullName>Quality Checking</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Completed - work open</fullName>
            </value>
            <value>
                <fullName>Completed - historical data import</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Backlog</fullName>
                <isActive>false</isActive>
                <label>Backlog</label>
            </value>
            <value>
                <fullName>Blocked</fullName>
                <isActive>false</isActive>
                <label>Blocked</label>
            </value>
            <value>
                <fullName>Done</fullName>
                <isActive>false</isActive>
                <label>Done</label>
            </value>
            <value>
                <fullName>New</fullName>
                <isActive>false</isActive>
                <label>New</label>
            </value>
            <value>
                <fullName>Selected for Development</fullName>
                <isActive>false</isActive>
                <label>Selected for Development</label>
            </value>
            <value>
                <fullName>Under Spec</fullName>
                <isActive>false</isActive>
                <label>Under Spec</label>
            </value>
            <value>
                <fullName>Waiting</fullName>
                <isActive>false</isActive>
                <label>Waiting</label>
            </value>
            <value>
                <fullName>Won&#39;t do</fullName>
                <isActive>false</isActive>
                <label>Won&#39;t do</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <formula>Account_Plant__r.Plant__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Name</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/project_cloud__Type__c.field-meta.xml
<CustomField>
    <fullName>project_cloud__Type__c</fullName>
    <inlineHelpText>A picklist used to indicate a project&#39;s type.</inlineHelpText>
    <label>Project Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Monitoring Implementation</fullName>
            </value>
            <value>
                <fullName>Monitoring Decommissioning</fullName>
            </value>
            <value>
                <fullName>T&amp;M</fullName>
            </value>
            <value>
                <fullName>Drive O&amp;M</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Internal Projects</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/ProgramController.cls
/**
 * This class is for updating CC project records for related program  
 * from quick action
 */
public with sharing class ProgramController {
    /**
     * This method will fetch all required projects for associating program
     * @return :  all projects where program is not associated.
     */
    @AuraEnabled
    public static List<project_cloud__Project__c> fetchData() {
        //Query and return list of Projects
        List<project_cloud__Project__c> objRecords = new List<project_cloud__Project__c>();
        if(project_cloud__Project__c.SObjectType.getDescribe().isAccessible()){
            objRecords = [select Id, Name, project_cloud__Type__c,External_Status__c, Internal_Status__c,Owner.Name,Plant_Name__c,CreatedDate  from project_cloud__Project__c  where Program_Name__c = null limit 2000];
            
        }
        return objRecords;
    }
    /**
    * This method will save Project record for program Id  
    * @param  :  program Id and project list
    * @return :  Save projects for Program Id
    */
    @AuraEnabled 
    public static void addProjects(String programId, String projectIdListJSON){
        if(project_cloud__Project__c.SObjectType.getDescribe().isAccessible()){
            List<project_cloud__Project__c> lstProjects = new List<project_cloud__Project__c>();
            Type idArrType = Type.forName('List<string>');
            List<string> lstPeojectIds = (List<string>) JSON.deserialize(projectIdListJSON, idArrType);

            system.debug('==programId==::'+programId);
            system.debug('==lstPeojectIds==::'+lstPeojectIds);
            if(!string.isblank(programId) && lstPeojectIds.size()>0){
                for(project_cloud__Project__c projRec: [SELECT Id, Program_Name__c From project_cloud__Project__c where id IN :lstPeojectIds]){
                    projRec.Program_Name__c = programId;
                    lstProjects.add(projRec);
                }
                update lstProjects;
            }
        }
    }
}