unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Prompt_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Id__c</fullName>
    <label>Prompt Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PromptNavigationHelper.cls
public with sharing class PromptNavigationHelper {
 
    public static String findPromptId(String promptName) {
        String retString;

        if(!String.isBlank(promptName)){
            List<Prompt_Information__c> promptInfo = [SELECT id, Prompt_Id__c 
                            FROM Prompt_Information__c WHERE Name =: promptName LIMIT 1];
            if(promptInfo.size() > 0){
                retString = promptInfo[0].Prompt_Id__c;
            }else{
                retString = 'The Next or Previous prompt is not found, Please contact admnistrator.';
            }
        }else{
            retString = 'The Next or Previous prompt is not found, Please contact admnistrator.';
        }
        return retString;
    }
}