unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Customer_Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Name__c</fullName>
    <label>Customer Plant Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Drive_Id__c.field-meta.xml
<CustomField>
    <fullName>Drive_Id__c</fullName>
    <label>Drive Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Plant__r.Latitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Plant__r.Longitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/PF_Service_Product__c.field-meta.xml
<CustomField>
    <fullName>PF_Service_Product__c</fullName>
    <label>PF Service Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
                <default>true</default>
                <label>Drive</label>
            </value>
            <value>
                <fullName>Drive Pro</fullName>
            </value>
            <value>
                <fullName>FSM</fullName>
            </value>
            <value>
                <fullName>Asset Build</fullName>
            </value>
            <value>
                <fullName>API</fullName>
                <isActive>false</isActive>
                <label>API</label>
            </value>
            <value>
                <fullName>Advanced Analytics</fullName>
                <isActive>false</isActive>
                <label>Advanced Analytics</label>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
                <isActive>false</isActive>
                <label>Bluepoint</label>
            </value>
            <value>
                <fullName>Data Pipe</fullName>
                <isActive>false</isActive>
                <label>Data Pipe</label>
            </value>
            <value>
                <fullName>Edge Services</fullName>
                <isActive>false</isActive>
                <label>Edge Services</label>
            </value>
            <value>
                <fullName>Greenbyte</fullName>
                <isActive>false</isActive>
                <label>Greenbyte</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <formula>TEXT(Plant__r.Renewable_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewable Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <formula>TEXT( Plant__r.Timezone__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <description>Used for Asset Builder</description>
    <label>Renewable Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Hybrid - Solar PV / BESS</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>BESS</fullName>
            </value>
            <value>
                <fullName>Hybrid - Fuel Cell / BESS</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Biomass</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morocco Standard Time</fullName>
            </value>
            <value>
                <fullName>Coordinated Universal Time</fullName>
            </value>
            <value>
                <fullName>GMT Standard Time</fullName>
            </value>
            <value>
                <fullName>Greenwich Standard Time</fullName>
            </value>
            <value>
                <fullName>W. Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Central Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Romance Standard Time</fullName>
            </value>
            <value>
                <fullName>Central European Standard Time</fullName>
            </value>
            <value>
                <fullName>W. Central Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>Namibia Standard Time</fullName>
            </value>
            <value>
                <fullName>Jordan Standard Time</fullName>
            </value>
            <value>
                <fullName>GTB Standard Time</fullName>
            </value>
            <value>
                <fullName>Middle East Standard Time</fullName>
            </value>
            <value>
                <fullName>Egypt Standard Time</fullName>
            </value>
            <value>
                <fullName>Syria Standard Time</fullName>
            </value>
            <value>
                <fullName>South Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>FLE Standard Time</fullName>
            </value>
            <value>
                <fullName>Turkey Standard Time</fullName>
            </value>
            <value>
                <fullName>Jerusalem Standard Time</fullName>
            </value>
            <value>
                <fullName>E. Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Arabic Standard Time</fullName>
            </value>
            <value>
                <fullName>Kaliningrad Standard Time</fullName>
            </value>
            <value>
                <fullName>Arab Standard Time</fullName>
            </value>
            <value>
                <fullName>E. Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>Iran Standard Time</fullName>
            </value>
            <value>
                <fullName>Arabian Standard Time</fullName>
            </value>
            <value>
                <fullName>Azerbaijan Standard Time</fullName>
            </value>
            <value>
                <fullName>Russian Standard Time</fullName>
            </value>
            <value>
                <fullName>Mauritius Standard Time</fullName>
            </value>
            <value>
                <fullName>Georgian Standard Time</fullName>
            </value>
            <value>
                <fullName>India Standard Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/DownloadAbMetadataCsvTest.cls
/**
**/
@isTest
public class DownloadAbMetadataCsvTest {
     @testSetup static void methodName() {
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;
        
        Plant__c plant = new Plant__c();
        plant.Name = 'Asset Builder Plant' ;    
        plant.Renewable_Type__c=Constants.WIND;
        plant.Timezone__c= 'India Standard Time';
        plant.Latitude__c='45.5017';
        plant.Longitude__c='-75.123';
        insert plant;
        
        Account_Plant__c plantAsset = new Account_Plant__c();
        plantAsset.Customer_Plant_Name__c = 'Customer Plant Asset';
        plantAsset.PF_Service_Product__c = Constants.DRIVE_PRO;
        plantAsset.Drive_Id__c  = '21.21.21.1';
        plantAsset.TEM_Version__c = newTemVersion.id;
        plantAsset.Project_Lifecycle_Status__c = 'Pending';
        plantAsset.Plant__c = plant.id;
        insert plantAsset;
        
        Account_Plant__c newPlantAsset1 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','21.21.21',newTemVersion.Id);
        newPlantAsset1.Project_Lifecycle_Status__c = 'Pending';
        
        insert newPlantAsset1;
        plantAsset.Plant__c = plant.id;
        update plantAsset;
    }
    

     
}