unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Amendment_Action__c.field-meta.xml
<CustomField>
    <fullName>Amendment_Action__c</fullName>
    <label>Amendment Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added Plant</fullName>
            </value>
            <value>
                <fullName>Removed Plant</fullName>
            </value>
            <value>
                <fullName>No_Change</fullName>
                <label>No Change</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Contracted_MW_Unit_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Contracted_MW_Unit_List_Price__c</fullName>
    <label>Contracted MW Unit List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/MWp_Quantity__c.field-meta.xml
<CustomField>
    <fullName>MWp_Quantity__c</fullName>
    <label>MW Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plant Product</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Quote_Line_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Quantity__c</fullName>
    <description>This is the field where the User will enter the Quantity - which in turn will add to the aggregate Quantity on the Quote line. e.g. for a Product with Unit of Measure as Turbines (WTG), this filed will have the number of Turbines and the MWp_Quantity__c (which is going to be renamed to MW_Quantity__c later) will have the MW for the WTG plant</description>
    <inlineHelpText>This is the field where the User will enter the Quantity - which in turn will add to the aggregate Quantity on the Quote line. e.g. for a Product with Unit of Measure as Turbines (WTG), this filed will have the number of Turbines and the MWp_Quantity__c (which is going to be renamed to MW_Quantity__c later) will have the MW for the WTG plant</inlineHelpText>
    <label>Quote Line Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Amendment_Quoted</fullName>
                <label>Amendment Quoted</label>
            </value>
            <value>
                <fullName>Renewal Quoted</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Trial__c.field-meta.xml
<CustomField>
    <fullName>Trial__c</fullName>
    <formula>Quote__r.Trial__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Trial</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Subscription__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/AmendmentQuoteProcessHelper.cls
public class AmendmentQuoteProcessHelper {
    public static void createPPTunderAmbededQL(List <SBQQ__QuoteLine__c> amendedQl){
        
        Set<Id> prodIdSet = new Set<Id>();
        
        
        Map<Id, SBQQ__QuoteLine__c> productQuotelineMap = new Map<Id, SBQQ__QuoteLine__c>();
        
        for(SBQQ__QuoteLine__c ql : amendedQl){
            productQuotelineMap.put(ql.SBQQ__Product__c, ql);
            //prodIdSet.add(ql.SBQQ__Product__c);
        }
        
        system.debug('idList--'+prodIdSet);
        List<Plant_Product_Transaction__c> pptUnderVarginalQL = [SELECT id,
                                                                 		name,
                                                                 		Subscription__c,
                                                                 		Account__c,
                                                                 Plant__r.Name,
                                                                 Amendment_Action__c,
                                                                 Plant_Product__c,
                                                                 Plant__r.Plant__r.MWp__c,
                                                                 Contracted_MW_Unit_List_Price__c,
                                                                 Quote_Line_Quantity__c,
                                                                 		Subscription__r.SBQQ__QuoteLine__c,
                                                                 Subscription__r.SBQQ__Product__c,
                                                                 		Quote_Line__r.SBQQ__Quote__r.SBQQ__Account__c,
                                                                 		Product__c,
                                                                 		Quote_Line__r.SBQQ__Product__c
                                                                 FROM Plant_Product_Transaction__c
                                                                 WHERE Subscription__r.SBQQ__Product__c IN: productQuotelineMap.keySet() 
                                                                 AND Status__c = 'Contracted'and Plant__r.Status__c ='Active'
                                                                ];
        
        system.debug('pptUnderVarginalQL---'+pptUnderVarginalQL);
        
        Map<Id,List<Plant_Product_Transaction__c>> vargQuoteLinePptMap = new  Map<Id,List<Plant_Product_Transaction__c>>();   
       // Map<Id,Map<Id,List<Plant_Product_Transaction__c>>> vargQuoteLinePptMap2 = new  Map<Id,Map<Id,List<Plant_Product_Transaction__c>>>();   
        
        for(Plant_Product_Transaction__c ppt : pptUnderVarginalQL){	
            if(vargQuoteLinePptMap.containsKey(ppt.Subscription__r.SBQQ__Product__c)){
                vargQuoteLinePptMap.get(ppt.Subscription__r.SBQQ__Product__c).add(ppt);
            }
            else{
                vargQuoteLinePptMap.put(ppt.Subscription__r.SBQQ__Product__c  , new List<Plant_Product_Transaction__c> {ppt});
            }
            
        }
        
        List<Plant_Product_Transaction__c> pptListTOClone = new List <Plant_Product_Transaction__c>();
        
        for(SBQQ__QuoteLine__c ql : productQuotelineMap.values()){
            
            if(vargQuoteLinePptMap.containsKey(ql.SBQQ__Product__c)
               && ( ql.Plant_Product_Transactions__r.size() == null || ql.Plant_Product_Transactions__r.size() == 0)){
                for( Plant_Product_Transaction__c ppt: vargQuoteLinePptMap.get(ql.SBQQ__Product__c) ){
                    if(ppt.Account__c == ql.SBQQ__Quote__r.SBQQ__Account__c){
                        Plant_Product_Transaction__c pp = ppt.clone(false,true,false,false);
                        
                        
                        
                      pp.Quote_Line__c = ql.Id;
                    pp.Status__c = 'Amendment_Quoted';
                      //pp.Trial__c =false; 
                    //pp.Amendment_Action__c ='NoChange' ;
                    pp.Plant_Product__c =true ;
                    pp.Amendment_Action__c='No_Change';    
                    pp.Product__c=ql.SBQQ__Product__c;
                    pp.Quote__c=ql.SBQQ__Quote__r.id;
                    pp.Subscription__c = null;
                    pp.MWp_Quantity__c=pp.Plant__r.Plant__r.MWp__c;
                    //pp.Quote_Line_Quantity__c=pp.Plant__r.Plant__r.MWp__c;
                    pp.Quote_Line_Quantity__c=ppt.Quote_Line_Quantity__c;
                    
                    pp.List_Unit_Price__c=ql.SBQQ__ListPrice__c;
                    pp.Contracted_MW_Unit_List_Price__c= ppt.Contracted_MW_Unit_List_Price__c;  
                        
                        pptListTOClone.add(pp);
                    }
                }
            }
            
        }
		
		if(pptListTOClone != null && pptListTOClone.size() > 0){
            system.debug('pptListTOClone--'+pptListTOClone.size());
            insert pptListTOClone;
        }
    }
}