unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/Implementation_Wizard_Form_Detail__c.object-meta.xml
<CustomObject>
    <description>To store file and API request and response details of implementation wizard form</description>
    <label>Implementation Wizard Form Detail</label>
    <nameField>
        <label>Implementation Wizard Form Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Wizard Form Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to plant asset related to the form API request</description>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Implementation Wizard Form Details</relationshipLabel>
    <relationshipName>Implementation_Wizard_Form_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/API_Type__c.field-meta.xml
<CustomField>
    <fullName>API_Type__c</fullName>
    <description>This will help API to make the callout to get the relevant response</description>
    <label>API Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Data_Interface__c</controllingField>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AlsoEnergy</fullName>
            </value>
            <value>
                <fullName>AQS</fullName>
            </value>
            <value>
                <fullName>GreenPowerMonitor</fullName>
            </value>
            <value>
                <fullName>LocusEnergy</fullName>
            </value>
            <value>
                <fullName>SolarEdge</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Data_Interface__c.field-meta.xml
<CustomField>
    <fullName>Data_Interface__c</fullName>
    <description>This will help user to select Data Interface type to show the dependent API type</description>
    <label>Data Interface</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>API</fullName>
            </value>
            <value>
                <fullName>Datalogger</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Plant_API_Id__c.field-meta.xml
<CustomField>
    <fullName>Plant_API_Id__c</fullName>
    <description>To store the Plant Asset Id in the external system used for API</description>
    <label>Plant API Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SendNeuronTemplateDetailTest.cls
/**
 * Created by karthikeyan.k on 6/28/2021.
 */

@IsTest
private class SendNeuronTemplateDetailTest {
    @TestSetup
    static void setupData(){
        Implementation_Wizard_Form_Detail__c impWiz = new Implementation_Wizard_Form_Detail__c(
                Data_Interface__c = 'API',
                API_Type__c = 'AlsoEnergy',
                Plant_API_Id__c = '123'
        );
        insert impWiz;

        String title = 'PiBuilder-New-1';
        String extension = 'xlsx';
        String fileContent = 'PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxMaWdodG5pbmdDb21wb25lbnRCdW5kbGUgeG1sbnM9Imh0dHA6Ly9zb2FwLnNmb3JjZS5jb20vMjAwNi8wNC9tZXRhZGF0YSI+DQogICAgPGFwaVZlcnNpb24+NDguMDwvYXBpVmVyc2lvbj4NCiAgICA8aXNFeHBvc2VkPmZhbHNlPC9pc0V4cG9zZWQ+DQo8L0xpZ2h0bmluZ0NvbXBvbmVudEJ1bmRsZT4=';

        ContentVersion cv = new ContentVersion();
        cv.Title = title;
        cv.PathOnClient = title + '.' +extension;
        cv.VersionData = EncodingUtil.base64Decode(fileContent);
        cv.IsMajorVersion = true;
        Insert cv;

        Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;

        ContentDocumentLink cdl = New ContentDocumentLink();
        cdl.LinkedEntityId = impWiz.Id;
        cdl.ContentDocumentId = conDocId;
        cdl.shareType = 'V';
        Insert cdl;
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;
        Account_Plant__c newPlantAsset = TestDataFactory.createPlantAsset('Solar - PV', 'Drive', '7777.77.777', newTemVersion.Id);
        insert newPlantAsset;
    }

    @IsTest
    static void testCalloutSuccessMethod(){
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        String bodyContent = '{"status":"success","details":{"fileContent":"PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4NCjxMaWdodG5pbmdDb21wb25lbnRCdW5kbGUgeG1sbnM9Imh0dHA6Ly9zb2FwLnNmb3JjZS5jb20vMjAwNi8wNC9tZXRhZGF0YSI+DQogICAgPGFwaVZlcnNpb24+NDguMDwvYXBpVmVyc2lvbj4NCiAgICA8aXNFeHBvc2VkPmZhbHNlPC9pc0V4cG9zZWQ+DQo8L0xpZ2h0bmluZ0NvbXBvbmVudEJ1bmRsZT4="}}';
        Test.setMock(HttpCalloutMock.class, new ImplementationWizardFormMock(bodyContent, 200));
        Account_Plant__c newPlantAsset = [SELECT Id From Account_Plant__c LIMIT 1];

        Test.startTest();
        ImplementationWizardForm.queryInformation();

        Map<String, String> requestParametersMap = new Map<String, String>{
                'plantAssetId' => String.valueOf(newPlantAsset.Id)
        };

        String requestParameters = '{"plantAssetId":"'+newPlantAsset.Id+'"}';

        String templateFile = 'templateFile';
        String piTemplateFile = 'piTemplateFile';
        SendNeuronTemplateDetail.callNeuronAPI(requestParameters, templateFile, piTemplateFile);
        Test.stopTest();
    }

    @IsTest
    static void testCalloutErrorMethod(){
        // This causes a fake response to be sent
        // from the class that implements HttpCalloutMock.
        String bodyContent = '{"status": "error","details": {"code": "TenantNotFound","devMessage": "","userMessage": "Unable to retrieve tenant for customer name : 1452"}}';
        Test.setMock(HttpCalloutMock.class, new ImplementationWizardFormMock(bodyContent, 200));
        Account_Plant__c newPlantAsset = [SELECT Id From Account_Plant__c LIMIT 1];

        Test.startTest();
        ImplementationWizardForm.queryInformation();

        Map<String, String> requestParametersMap = new Map<String, String>{
                'plantAssetId' => String.valueOf(newPlantAsset.Id)
        };

        String requestParameters = '{"plantAssetId":"'+newPlantAsset.Id+'"}';

        String templateFile = 'templateFile';
        String piTemplateFile = 'piTemplateFile';
        SendNeuronTemplateDetail.callNeuronAPI(requestParameters, templateFile, piTemplateFile);
        Test.stopTest();
    }
}