unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Drive_Id__c.field-meta.xml
<CustomField>
    <fullName>Drive_Id__c</fullName>
    <label>Drive Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <formula>Plant__r.Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <formula>TEXT(Plant__r.Renewable_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewable Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Base Asset Templates</relationshipLabel>
    <relationshipName>Base_Asset_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Base_Asset__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Bulk_Import_Type__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Import_Type__c</fullName>
    <label>Bulk Import Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Base Asset Template Prompts</fullName>
                <default>true</default>
                <label>Single Base Asset Template Prompts</label>
            </value>
            <value>
                <fullName>Multiple Base Asset Template Prompts</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/G1BulkImportButtonHndlrTest.cls
/**
**/
@isTest
public class G1BulkImportButtonHndlrTest {
    @testSetup
    public static void testDataSetup() {
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;
        Account_Plant__c pa = new Account_Plant__c();
//        pa.Name = 'Plant Asset Test1';
//        pa.RecordTypeId = [SELECT id from RecordType where Name ='Parent Asset'].Id;
//        pa.Plant_Name__c = 'test1';
        pa.Project_Lifecycle_Status__c = 'Pending';
//        pa.Implementation_Status__c = 'Pending Customer Submission';
//        pa.Renewable_Type__c = Constants.WIND;
        insert pa;
        Account_Plant__c newPlantAsset1 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.777',newTemVersion.Id);
//        newPlantAsset1.Parent__c = pa.Id;
        Account_Plant__c newPlantAsset2 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.778',newTemVersion.Id);
//        newPlantAsset2.Parent__c = pa.Id;
        Account_Plant__c newPlantAsset3 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.779',newTemVersion.Id);
//        newPlantAsset3.Parent__c = pa.Id;
      Account_Plant__c newPlantAsset4 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.780',newTemVersion.Id);
        Account_Plant__c newPlantAsset5 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.781',newTemVersion.Id);
         Account_Plant__c newPlantAsset6 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.782',newTemVersion.Id);
  
        insert newPlantAsset1;
        insert newPlantAsset2;
        insert newPlantAsset3;
        insert newPlantAsset4;
        insert newPlantAsset5;
        insert newPlantAsset6;
        List<Base_Asset_Template__c> newBaseAssetTemplate = new List<Base_Asset_Template__c>();
        newBaseAssetTemplate.add(TestDataFactory.createBaseAssetTemplate(Constants.BASE_BLOCK, newTemVersion.Id));
        newBaseAssetTemplate.add(TestDataFactory.createBaseAssetTemplate(Constants.BASE_PV_PLANT, newTemVersion.Id));
       
        insert newBaseAssetTemplate;
        Prompt_Information__c newPromptInfo = TestDataFactory.createPromptInformation(Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT, newBaseAssetTemplate[0].Id, newTemVersion.Id);
        insert newPromptInfo;
        Prompt_Information__c previousPromptInfo = TestDataFactory.createPromptInformation(Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT, newBaseAssetTemplate[0].Id, newTemVersion.Id);
        insert previousPromptInfo;
        Prompt_Information__c nextPromptInfo = TestDataFactory.createPromptInformation(Constants.P1_PLANT_INFO_PROMPT_SOLAR, newBaseAssetTemplate[0].Id, newTemVersion.Id);
        insert nextPromptInfo;
        Plant_Asset_Prompt_Detail__c plantAssetPromptDetail1 = new Plant_Asset_Prompt_Detail__c();
        plantAssetPromptDetail1.Name = newPlantAsset2.Name +'-'+previousPromptInfo.Name;
        plantAssetPromptDetail1.Account_Plant__c = newPlantAsset2.Id;
        plantAssetPromptDetail1.Prompt_Information__c = previousPromptInfo.Id;
        plantAssetPromptDetail1.Base_Asset__c = newBaseAssetTemplate[0].Id;
        insert plantAssetPromptDetail1;
        Plant_Asset_Prompt_Detail__c plantAssetPromptDetail2 = new Plant_Asset_Prompt_Detail__c();
        plantAssetPromptDetail2.Name = newPlantAsset2.Name +'-'+previousPromptInfo.Name;
        plantAssetPromptDetail2.Account_Plant__c = newPlantAsset2.Id;
        plantAssetPromptDetail2.Prompt_Information__c = previousPromptInfo.Id;
        plantAssetPromptDetail2.Base_Asset__c = newBaseAssetTemplate[0].Id;
        insert plantAssetPromptDetail2;
         Plant_Asset_Prompt_Detail__c plantAssetPromptDetail3 = new Plant_Asset_Prompt_Detail__c();
         plantAssetPromptDetail3.Name = newPlantAsset3.Name +'-'+nextPromptInfo.Name;
         plantAssetPromptDetail3.Account_Plant__c = newPlantAsset3.Id;
         plantAssetPromptDetail3.Prompt_Information__c = previousPromptInfo.Id;
         plantAssetPromptDetail3.Base_Asset__c = newBaseAssetTemplate[0].Id;
         insert plantAssetPromptDetail3; 
        Plant_Asset_Prompt_Detail__c plantAssetPromptDetail4 = new Plant_Asset_Prompt_Detail__c();
        plantAssetPromptDetail4.Name = newPlantAsset4.Name +'-'+nextPromptInfo.Name;
        plantAssetPromptDetail4.Account_Plant__c = newPlantAsset4.Id;
        plantAssetPromptDetail4.Prompt_Information__c = previousPromptInfo.Id;
        plantAssetPromptDetail4.Base_Asset__c = newBaseAssetTemplate[0].Id;
       plantAssetPromptDetail4.Bulk_Import_Type__c = 'Manual';
        insert plantAssetPromptDetail4; 
        Plant_Asset_Prompt_Detail__c plantAssetPromptDetail5 = new Plant_Asset_Prompt_Detail__c();
        plantAssetPromptDetail5.Name = newPlantAsset5.Name +'-'+nextPromptInfo.Name;
        plantAssetPromptDetail5.Account_Plant__c = newPlantAsset5.Id;
        plantAssetPromptDetail5.Prompt_Information__c = previousPromptInfo.Id;
        plantAssetPromptDetail5.Base_Asset__c = newBaseAssetTemplate[0].Id;
       plantAssetPromptDetail5.Bulk_Import_Type__c = 'COMPLETED';
        insert plantAssetPromptDetail5; 
        Plant_Asset_Prompt_Detail__c plantAssetPromptDetail6 = new Plant_Asset_Prompt_Detail__c();
        plantAssetPromptDetail6.Name = newPlantAsset6.Name +'-'+previousPromptInfo.Name;
        plantAssetPromptDetail6.Account_Plant__c = newPlantAsset6.Id;
        plantAssetPromptDetail6.Prompt_Information__c = previousPromptInfo.Id;
        plantAssetPromptDetail6.Base_Asset__c = newBaseAssetTemplate[0].Id;
        plantAssetPromptDetail6.Bulk_Import_Type__c = 'Multiple Base Asset Template Prompts';
        insert plantAssetPromptDetail6;
      }
    @isTest
    public static void getG1RecordDetailsTest(){
         Id plantAsset1 = [SELECT Id, Name FROM Account_Plant__c WHERE Drive_Id__c ='7777.77.777'].Id;
         G1BulkImportButtonHndlr.getG1RecordDetails(plantAsset1);
         Id plantAsset2 = [SELECT Id, Name FROM Account_Plant__c WHERE Drive_Id__c ='7777.77.778'].Id;
         G1BulkImportButtonHndlr.getG1RecordDetails(plantAsset2);
         Id plantAsset3 = [SELECT Id, Name FROM Account_Plant__c WHERE Drive_Id__c ='7777.77.779'].Id;
         G1BulkImportButtonHndlr.getG1RecordDetails(plantAsset3);
         Id plantAsset4 = [SELECT Id, Name FROM Account_Plant__c WHERE Drive_Id__c ='7777.77.780'].Id;
         G1BulkImportButtonHndlr.getG1RecordDetails(plantAsset4);
         Id plantAsset5 = [SELECT Id, Name FROM Account_Plant__c WHERE Drive_Id__c ='7777.77.781'].Id;
         G1BulkImportButtonHndlr.getG1RecordDetails(plantAsset5);
        Id plantAsset6 = [SELECT Id, Name FROM Account_Plant__c WHERE Drive_Id__c ='7777.77.782'].Id;
         G1BulkImportButtonHndlr.getG1RecordDetails(plantAsset6);
        
    }

}