unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <formula>Drive_Id__c &amp; &quot;,&quot; &amp;  Customer_Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Compiled_Excel_Sorting_Order__c.field-meta.xml
<CustomField>
    <fullName>Compiled_Excel_Sorting_Order__c</fullName>
    <label>Compiled Excel Sorting Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Alternate_Parent_Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Parent_Site_Metadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alternate Parent Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Site Metadata (Alternate Parent Site Metadata)</relationshipLabel>
    <relationshipName>Alternate_Parent_Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <label>Asset Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <formula>Plant_Asset_Prompt_Detail__r.Is_Deleted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Parent_Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Parent_Site_Metadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Site Metadata (Parent Site Metadata)</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/PlantAssetABTreeViewHandler.cls
public with sharing class PlantAssetABTreeViewHandler {

    @AuraEnabled
    public static String formTreeView(String plantAssetId){
        String result;
        List<String> assetShortNameEmptyPrompts = new List<String>{Constants.P10A_OTHER_ASSET_BUILD , Constants.W3_TURBINE_BUILD};
        List<Site_Metadata__c> siteMetadataSOs = [SELECT Id, Asset_Name__c, Asset_Short_Name__c , Parent_Site_Metadata__c, Alternate_Parent_Site_Metadata__c, Prompt_Information__r.Name, Account_Plant__r.Name
                                                    FROM Site_Metadata__c WHERE Account_Plant__c =: plantAssetId
                                                    AND Plant_Asset_Prompt_Detail__r.Is_Deleted__c = false
                                                    AND Prompt_Information__r.Name NOT IN : assetShortNameEmptyPrompts 
                                                    ORDER BY Prompt_Information__r.Compiled_Excel_Sorting_Order__c, Asset_Name__c ASC];
        if(siteMetadataSOs.size() > 0){
            Map<String, List<Id>> promptNameAndRecordIdsMap = new Map<String, List<Id>>();
            Map<Id,SiteMetadataWrapper> siteMetadataWrapperMap = new Map<Id,SiteMetadataWrapper>();
    
            /*
                * To create PromptName and its related site metadata Ids Map
                * To create SiteMetadataWrapperMap with site metadata Id as Key and wrapper (empty items) has its value 
            */
            for (Site_Metadata__c siteMetadataSO : siteMetadataSOs) {
                String promptName = siteMetadataSO.Prompt_Information__r.Name;
                if(!promptNameAndRecordIdsMap.containsKey(promptName)){
                    promptNameAndRecordIdsMap.put(promptName, new List<Id>());
                }
                promptNameAndRecordIdsMap.get(promptName).add(siteMetadataSO.Id);
    
                SiteMetadataWrapper siteMetadataWrapperSO = new SiteMetadataWrapper();
                siteMetadataWrapperSO.Id = siteMetadataSO.Id;
                siteMetadataWrapperSO.label = siteMetadataSO.Asset_Short_Name__c + ' - '+ siteMetadataSO.Asset_Name__c;
                siteMetadataWrapperSO.promptName = siteMetadataSO.Prompt_Information__r.Name;
                siteMetadataWrapperSO.items = new List<SiteMetadataWrapper>();
                siteMetadataWrapperMap.put(siteMetadataSO.Id, siteMetadataWrapperSO);
            }
    
            //To add the site metadata wrapper into the alternate parent if exists or parent site metadata items list
            String ParentOrAltParentId;
            for(Site_Metadata__c siteMetadataSO : siteMetadataSOs){
                if(siteMetadataWrapperMap.containsKey(siteMetadataSO.Parent_Site_Metadata__c)){
                    SiteMetadataWrapper siteMetadataWrapperSO = siteMetadataWrapperMap.get(siteMetadataSO.Id);
                    String siteMetadataSOAltParentId = siteMetadataSO.Alternate_Parent_Site_Metadata__c;
                    if(siteMetadataSOAltParentId != null && siteMetadataWrapperMap.containsKey(siteMetadataSOAltParentId)){
                        ParentOrAltParentId = siteMetadataSOAltParentId;
                    }else{
                        ParentOrAltParentId = siteMetadataSO.Parent_Site_Metadata__c;
                    }
                    SiteMetadataWrapper parentSiteMetadata = siteMetadataWrapperMap.get(ParentOrAltParentId);
                    parentSiteMetadata.items.add(siteMetadataWrapperSO);
                }
            }
    
            // To form the Wrapper(Used in Lwc) which contains P1 items, w1 items, Metmast record and Substation record
            SiteMetadataWrapper plantAssetSitemetaWrapper = new SiteMetadataWrapper();
            plantAssetSitemetaWrapper.Id = plantAssetId;
            plantAssetSitemetaWrapper.label = siteMetadataSOs[0].Account_Plant__r.Name;
            plantAssetSitemetaWrapper.items = new List<SiteMetadataWrapper>();
    
            List<Id> g1Id  =  promptNameAndRecordIdsMap.get(Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT);
            SiteMetadataWrapper g1SiteMetadataWrapper = siteMetadataWrapperMap.get(g1Id[0]);
            for(SiteMetadataWrapper g1SiteMetadataItem : g1SiteMetadataWrapper.items){
                if(g1SiteMetadataItem.promptName == Constants.P1_PLANT_INFO_PROMPT_SOLAR || g1SiteMetadataItem.promptName == Constants.W1_PLANT_INFO_PROMPT_WIND){
                    plantAssetSitemetaWrapper.items.addAll(g1SiteMetadataItem.items);
                }else{
                    plantAssetSitemetaWrapper.items.add(g1SiteMetadataItem);
                }
            }
    
            List<SiteMetadataWrapper> resultList = new List<SiteMetadataWrapper>();
            resultList.add(plantAssetSitemetaWrapper);
            result = JSON.serialize(resultList);
        }else{
            result = 'NoData';  //This is used for checking condition in JS so custom label is not required  
        }
        return result;
    }

    public class SiteMetadataWrapper{
        public String Id;
        public String label;
        public String promptName;
        public List<SiteMetadataWrapper> items;
    }
}