unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <formula>Drive_Id__c &amp; &quot;,&quot; &amp;  Customer_Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Master__c/Attribute_Master__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute Master</label>
    <nameField>
        <label>Attribute Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Master__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines the attribute type as it pertains to the template. This determines the role of the data populated against the attribute for the static value configuration versus being read from a measured value</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metadata</fullName>
            </value>
            <value>
                <fullName>Time Series</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Prompt Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Attribute__c/fields/Attribute_Master__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Master__c</fullName>
    <label>Attribute Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Attribute_Master__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Attribute_Master__c</referenceTo>
    <relationshipLabel>Core Atributes</relationshipLabel>
    <relationshipName>Core_Atributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Defines the attribute type as it pertains to the template. This determines the role of the data populated against the attribute for the static value configuration versus being read from a measured value.</description>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Metadata</fullName>
            </value>
            <value>
                <fullName>Time Series</fullName>
            </value>
            <value>
                <fullName>Calculated</fullName>
            </value>
            <value>
                <fullName>Prompt Specific</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
            <value>
                <fullName>MetMast</fullName>
            </value>
            <value>
                <fullName>SubstationSwitchgear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Alternate_Parent_Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Alternate_Parent_Site_Metadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Alternate Parent Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Site Metadata (Alternate Parent Site Metadata)</relationshipLabel>
    <relationshipName>Alternate_Parent_Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <label>Asset Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Attribute_Info__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Info__c</fullName>
    <label>Attribute Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <formula>Plant_Asset_Prompt_Detail__r.Is_Deleted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Specific_Info__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Specific_Info__c</fullName>
    <label>Prompt Specific Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/ImportAndExportCSV.cls
public with sharing class ImportAndExportCSV{
    /*
     *To load the prompt SiteMetadataRecords
     *@param1 plantAssetId
     *@param2 PromptInfo
    */
    @AuraEnabled
    public Static Map<String,String> getPromptSiteMetadataRecords(String plantAssetId, String promptInfo){
        Prompt_Information__c promptInfoRecord = (Prompt_Information__c)
                System.JSON.deserialize(promptInfo,Prompt_Information__c.class);
        String promptInfoId = promptInfoRecord.Id;
        Map<String, String> csvDataAndSiteMetadata = new Map<String, String>();
        Map<Id, Site_Metadata__c> IdToSiteMetadata = new Map<Id, Site_Metadata__c>(
            [SELECT id,Attribute_Info__c,Prompt_Specific_Info__c,Asset_Name__c  
            FROM Site_Metadata__c WHERE  Account_Plant__c =: plantAssetId AND Prompt_Information__c =: promptInfoId AND Plant_Asset_Prompt_Detail__r.Is_Deleted__c = false]);
            if(IdToSiteMetadata.size() > 0)
            csvDataAndSiteMetadata.put('siteMetadata', JSON.serialize(IdToSiteMetadata));
        IdToSiteMetadata.clear();
        return csvDataAndSiteMetadata;
    }

    /*
     *To update the SiteMetadata records 
     *@param1 siteMetadataRecords (List of SiteMetadata records)
    */
    @AuraEnabled
    public static Boolean updateSiteMetadata(String siteMetadataRecords, Boolean isDelete, Boolean isLastBatch){
        Boolean result = false;
        List<Site_Metadata__c> siteMetadataList =  (List<Site_Metadata__c>) System.JSON.deserialize(siteMetadataRecords ,List<Site_Metadata__c>.class);
        for(Site_Metadata__c siteMetadata: siteMetadataList){
            String promptSpecificMap = siteMetadata.Prompt_Specific_Info__c;
            String attrSpecificMap = siteMetadata.Attribute_Info__c;
            attrSpecificMap = attrSpecificMap.replaceAll('"false"', 'false');
            attrSpecificMap = attrSpecificMap.replaceAll('"true"', 'true');
            attrSpecificMap = attrSpecificMap.replaceAll('"FALSE"', 'false');
            attrSpecificMap = attrSpecificMap.replaceAll('"TRUE"', 'true');
            promptSpecificMap = promptSpecificMap.replaceAll('"false"', 'false');
            promptSpecificMap = promptSpecificMap.replaceAll('"true"', 'true');
            promptSpecificMap = promptSpecificMap.replaceAll('"FALSE"', 'false');
            promptSpecificMap = promptSpecificMap.replaceAll('"TRUE"', 'true');
            siteMetadata.Prompt_Specific_Info__c = promptSpecificMap;
            siteMetadata.Attribute_Info__c = attrSpecificMap;
           }

        if(siteMetadataList.size() >0 ){
            update siteMetadataList;
            if(isDelete){
                List<Site_Metadata__c> siteMetadata = [SELECT Id,Plant_Asset_Prompt_Detail__r.Id, Plant_Asset_Prompt_Detail__r.Prompt_Information__r.Type__c from Site_Metadata__c where Id=: siteMetadataList[0].Id];
                Utils.plantAssetPromptDetailIsDeleteUpdate(
                        siteMetadata[0].Plant_Asset_Prompt_Detail__r.Id,
                        siteMetadata[0].Plant_Asset_Prompt_Detail__r.Prompt_Information__r.Type__c);
            }
                    
            result = true;
        }

        if(isLastBatch){
            Set<Id> alternateParentSiteMetadataRecordIdSet = new Set<Id>();
            List<Site_Metadata__c> siteMetadataRecordsToUpdate = new List<Site_Metadata__c>();
            List<Site_Metadata__c> siteMetadata = [SELECT Id, Name, Account_Plant__c from Site_Metadata__c where Id=: siteMetadataList[0].Id];
            siteMetadataRecordsToUpdate = Utils.querySiteMetadata(siteMetadata[0].Name, siteMetadata[0].Account_Plant__c);
            for(Site_Metadata__c sitemetadataSo : siteMetadataRecordsToUpdate){
                alternateParentSiteMetadataRecordIdSet.add(sitemetadataSo.Alternate_Parent_Site_Metadata__c);
            }
            
            if(siteMetadataRecordsToUpdate.size()>0){
                result = Utils.saveParentNameInSiteMetadataRecords(alternateParentSiteMetadataRecordIdSet, siteMetadataRecordsToUpdate, true);
            }
        }
        return result;  
    }
    
    @AuraEnabled
    public static Map<String,Object> getCSVInputsMap(
    List<Attribute_Master__c> attrLst,
    List<Site_Metadata__c> siteMetadataLst,
    list<Core_Attribute__c> assetNameAttr,
    list<Core_Attribute__c> parentAssetNameAttr,
    list<Core_Attribute__c> allCoreAttrLst){
        Map<String,Object> csvInputsMap = new Map<String,Object>();
        csvInputsMap.put('Attributes', attrLst);
        csvInputsMap.put('SiteMetadataRecords', siteMetadataLst);
        csvInputsMap.put('AssetNameAttr', assetNameAttr);
        csvInputsMap.put('ParentAssetAttrName', parentAssetNameAttr);
        csvInputsMap.put('allCoreAttrLst',allCoreAttrLst);
        return csvInputsMap;
    }

    @AuraEnabled
    public static String getPlantAssetDetail(String plantAssetId){
       List<Account_Plant__c> plantasset = [Select Customer_Plant_Asset_ID__c from Account_Plant__c where Id = :plantAssetId];
      return  plantasset[0].Customer_Plant_Asset_ID__c;
    }
}