unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <formula>TEXT(Plant__r.Asset_Class__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Class</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/Active_Megawatts__c.object-meta.xml
<CustomObject>
    <label>Active Megawatts</label>
    <nameField>
        <displayFormat>AM-{0000}</displayFormat>
        <label>Active Megawatts No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Active Megawatts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>AM for Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Active Megawatts</relationshipLabel>
    <relationshipName>Active_Megawatts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/MW_Hydro__c.field-meta.xml
<CustomField>
    <fullName>MW_Hydro__c</fullName>
    <label>MW Hydro</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/MW_Other_Renewable__c.field-meta.xml
<CustomField>
    <fullName>MW_Other_Renewable__c</fullName>
    <label>MW_Other Renewable</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/MW_Solar__c.field-meta.xml
<CustomField>
    <fullName>MW_Solar__c</fullName>
    <label>MW Solar</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/MW_Storage__c.field-meta.xml
<CustomField>
    <fullName>MW_Storage__c</fullName>
    <label>MW Storage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/MW_Wind__c.field-meta.xml
<CustomField>
    <fullName>MW_Wind__c</fullName>
    <label>MW Wind</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Total_Agnostic__c.field-meta.xml
<CustomField>
    <fullName>Total_Agnostic__c</fullName>
    <label>Total Agnostic</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Total_MW_Hydro__c.field-meta.xml
<CustomField>
    <fullName>Total_MW_Hydro__c</fullName>
    <label>Total MW Hydro</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Total_MW_Other_Renewable__c.field-meta.xml
<CustomField>
    <fullName>Total_MW_Other_Renewable__c</fullName>
    <label>Total MW Other Renewable</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Total_MW_Solar__c.field-meta.xml
<CustomField>
    <fullName>Total_MW_Solar__c</fullName>
    <label>Total MW Solar</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Total_MW_Storage__c.field-meta.xml
<CustomField>
    <fullName>Total_MW_Storage__c</fullName>
    <label>Total MW Storage</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Active_Megawatts__c/fields/Total_MW_Wind__c.field-meta.xml
<CustomField>
    <fullName>Total_MW_Wind__c</fullName>
    <label>Total MW Wind</label>
    <precision>12</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Non-Recurring Products (Product)</relationshipLabel>
    <relationshipName>Non_Recurring_Products</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar PV</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Other Renewable</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <formula>TEXT(Product__r.Asset_Class__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Class</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/MWp_Quantity__c.field-meta.xml
<CustomField>
    <fullName>MWp_Quantity__c</fullName>
    <label>MW Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Amendment_Quoted</fullName>
                <label>Amendment Quoted</label>
            </value>
            <value>
                <fullName>Renewal Quoted</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Class</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hydro</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Other Renewable</fullName>
    </customValue>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Wind</fullName>
    </customValue>
    <customValue>
        <fullName>All Renewables (Agnostic)</fullName>
    </customValue>
    <masterLabel>Asset Class</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/ActiveMegawattQuantityBatchapex.cls
/**
@description
BatchApex class to Aggregate Active Megawatts records Under Account object  
*/

global class ActiveMegawattQuantityBatchapex implements Database.Batchable<SObject> {
 
 /**
* Batachable start method implementation.
* @param BC The BatchableContext object provided by runtime.
* @return List of Plant_Product_Transaction to be fetched when the Status__c= Contracted,
  QuantityUnitOfMeasureas (MWp or MWh or WTG
  Account Plantis unique
*/   
global Database.QueryLocator Start(Database.BatchableContext bc)
{
       
            
       set<Id> accId = new set<Id>(); 
       list<Plant_Product_Transaction__c> p =[SELECT id,Plant__c,MWp_Quantity__c, Account__c, status__c FROM Plant_Product_Transaction__c
                                              Where Status__c ='contracted'
                                              and (Product__r.QuantityUnitOfMeasure='MWp' OR Product__r.QuantityUnitOfMeasure='MWh' OR Product__r.QuantityUnitOfMeasure='WGT') 
                                              and Plant__c!=null ];
        for(Plant_Product_Transaction__c se: p){
            accId.add(se.Account__c);
       }
    
   
        set<id> plist = new set<id>();
        List<Account_Plant__c> pe =[select id, name,Account__c from Account_Plant__c where Account__c=:accId];
   
        for(Account_Plant__c pl:pe){
            plist.add(pl.id);
       }
                
        String query = 'SELECT id,Plant__c, Account__c,plant__r.Asset_Class__c,status__c,MWp_Quantity__c  FROM '+
                        ' Plant_Product_Transaction__c WHERE Status__c = \'contracted\' and '+
                         ' (Product__r.QuantityUnitOfMeasure=\'MWp\' OR Product__r.QuantityUnitOfMeasure=\'MWh\' OR'+
                          ' Product__r.QuantityUnitOfMeasure=\'WGT\') and '+
                            ' plant__c=:plist';// AND Contract__r.status = \'Activated\'
        return Database.getQueryLocator(query);
    } 

/**
* Batchable execute method implementation.
* This method applies calculate logic based on the asset class.

*/
    global void execute(Database.BatchableContext bc, List<Plant_Product_Transaction__c> scope){
        Decimal SumSolar =0;
        Decimal SumWind =0;
        Decimal SumHydro =0;
        Decimal SumStorage =0;
        Decimal SumOtherRenewable=0;
        
        map<id,Active_Megawatts__c> mer =  new map<id,Active_Megawatts__c>();
        for(Plant_Product_Transaction__c pData :scope)
        {           
          if(pData.Account__c!=null){
             AggregateResult[] groupedResult1 = [SELECT SUM(MWp_Quantity__c)aver FROM Plant_Product_Transaction__c
                                                   where Account__c=:pData.Account__c and 
                                                    plant__r.Asset_Class__c='Solar'];
                                               Object a=groupedResult1[0].get('aver');
                if(a!=null && a!=''){SumSolar = Decimal.valueOf(String.valueOf(a));}
                
                AggregateResult[] groupedResult2 = [SELECT SUM(MWp_Quantity__c)aver FROM Plant_Product_Transaction__c
                                                   where Account__c=:pData.Account__c and 
                                                    plant__r.Asset_Class__c='Other Renewable'];
                                               Object b=groupedResult2[0].get('aver');
                if(b!=null && b!=''){SumOtherRenewable = Decimal.valueOf(String.valueOf(b));}
                
                
                    
                AggregateResult[] groupedResult3 = [SELECT SUM(MWp_Quantity__c)aver FROM Plant_Product_Transaction__c
                                                    where Account__c=:pData.Account__c and plant__r.Asset_Class__c='Wind'];
                Object c=groupedResult3[0].get('aver');
                if(c!=null && c!=''){SumWind = Decimal.valueOf(String.valueOf(c));}
                
                AggregateResult[] groupedResult4 = [SELECT SUM(MWp_Quantity__c)aver FROM Plant_Product_Transaction__c
                                                    where Account__c=:pData.Account__c and plant__r.Asset_Class__c='Hydro'];
                Object d=groupedResult4[0].get('aver');
                if(d!=null && d!=''){SumWind = Decimal.valueOf(String.valueOf(d));}
             
                    
                AggregateResult[] groupedResult5 = [SELECT SUM(MWp_Quantity__c)aver FROM Plant_Product_Transaction__c
                                                    where Account__c=:pData.Account__c and plant__r.Asset_Class__c='Storage'];
                object e = groupedResult5[0].get('aver');
                  if(e!=null && e!=''){SumStorage = Decimal.valueOf(String.valueOf(e));}
                
                
                    
                Active_Megawatts__c ae3 = new Active_Megawatts__c(
                    Total_Agnostic__c= SumStorage + SumWind + SumSolar + SumHydro+ SumOtherRenewable,
                    MW_Storage__c=SumStorage,
                    Total_MW_Storage__c=SumStorage ,
                    MW_Other_Renewable__c=SumOtherRenewable,
                    Total_MW_Other_Renewable__c=SumOtherRenewable,
                    MW_Wind__c =SumWind,
                    Total_MW_Wind__c =SumWind, 
                    MW_Solar__c = SumSolar,
                    Total_MW_Solar__c = SumSolar,
                    MW_Hydro__c = SumHydro,
                    Total_MW_Hydro__c = SumHydro,
                   Account__c=pData.Account__c);
                   mer.put(pData.Account__c,ae3);
             
           }SumSolar=0;SumHydro=0;SumWind=0;SumOtherRenewable=0;
        } 
        insert mer.Values();   
    }
    /**
* Batchable finish method implementation.
* @param BC The BatchableContext object provided by runtime.
*/
    global void finish(Database.BatchableContext BC)
    {
    }
    
    }