unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Builder_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Builder_Status__c</fullName>
    <label>Asset Builder Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Async_Job__e/Asset_Builder_Async_Job__e.object-meta.xml
<CustomObject>
    <label>Asset Builder Async Job</label>
    <pluralLabel>Asset Builder Async Jobs</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/Asset_Builder_Async_Job__e/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Async_Job__e/fields/Plant_Asset_Id__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Id__c</fullName>
    <description>Also reference as Account Plant.</description>
    <label>Plant Asset Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Capability_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Capability_Report_Status__c</fullName>
    <label>Capability Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
                <default>true</default>
                <label>Not Yet Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed - Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Completeness_Report_Status__c.field-meta.xml
<CustomField>
    <fullName>Completeness_Report_Status__c</fullName>
    <label>Completeness Report Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Yet Started</fullName>
                <default>true</default>
                <label>Not Yet Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed - Error</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Report_Execution_By_User__c.field-meta.xml
<CustomField>
    <fullName>Report_Execution_By_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Report Execution By User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Report_Generated_Datetime__c.field-meta.xml
<CustomField>
    <fullName>Report_Generated_Datetime__c</fullName>
    <label>Report Generated Datetime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/TriggerPEForReports.cls
/**
 * TODO - Calls from Finish button in LWC
 * Publish Two Platform events for Capability and Completeness Reports.  
 * */ 
public with sharing class TriggerPEForReports {
    public static String plantAssetId;
    /*
    * Publish Platform Events for Capability and Completeness report Platform Events.
    @param {String} plantAssetId - Pass Plant Asset for data creation for reports.
    */
    @AuraEnabled
    public static String createPE(String plantAssetId){
        Map<String, Object> responseMap = new Map<String, Object>();
        Savepoint sp = Database.setSavepoint();
        try{
            plantAssetId = plantAssetId;
            Plant_Asset_Prompt_Detail__c pltAstPrtDtl = [SELECT Id, Name, Capability_Report_Status__c,Completeness_Report_Status__c, 
                    Prompt_Information__c, Account_Plant__c,  Account_Plant__r.Asset_Builder_Status__c, Report_Generated_Datetime__c 
                    FROM Plant_Asset_Prompt_Detail__c 
                    WHERE Account_Plant__c =:plantAssetId AND Prompt_Information__r.Name=: Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT
                    AND Is_Deleted__c = false ];
                    
            if(pltAstPrtDtl.Account_Plant__r.Asset_Builder_Status__c == ConstantsPicklistValues.PLANT_ASSET_ASSET_BUILDER_STATUS_IN_PROGRESS){
                Account_Plant__c plantAsset= new Account_Plant__c (id = pltAstPrtDtl.Account_Plant__c);
                plantAsset.Asset_Builder_Status__c = ConstantsPicklistValues.PLANT_ASSET_ASSET_BUILDER_STATUS_COMPLETED;
                update plantAsset;
            }

            //Evaluation Value Creation
            Asset_Builder_Async_Job__e asyncEV = new Asset_Builder_Async_Job__e(); 
            asyncEV.Job_Type__c = Constants.CAPABILITY_REPORT; 
            asyncEV.Plant_Asset_Id__c = plantAssetId; 
            EventBus.publish(asyncEV);
            pltAstPrtDtl.Capability_Report_Status__c = ConstantsPicklistValues.PLANT_ASSET_PROMPT_DETAIL_REPORT_STATUS_IN_PROGRESS;
            pltAstPrtDtl.Report_Execution_By_User__c = UserInfo.getUserId(); 

            //Report Data Handler - Completeness report
            Asset_Builder_Async_Job__e asyncRDHdlr = new Asset_Builder_Async_Job__e(); 
            asyncRDHdlr.Job_Type__c = Constants.COMPLETENESS_REPORT; 
            asyncRDHdlr.Plant_Asset_Id__c = plantAssetId; 
            EventBus.publish(asyncRDHdlr);
            pltAstPrtDtl.Completeness_Report_Status__c = ConstantsPicklistValues.PLANT_ASSET_PROMPT_DETAIL_REPORT_STATUS_IN_PROGRESS;
            pltAstPrtDtl.Report_Execution_By_User__c = UserInfo.getUserId();
            pltAstPrtDtl.Report_Generated_Datetime__c = System.now();
            update pltAstPrtDtl;

            String g1PromptId = PromptNavigationHelper.findPromptId(Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT);
            Boolean substationRFICreation = RFIDataCreation.abSubstationRFICreation(plantAssetId);
            responseMap.put('result', true);
            responseMap.put('g1PromptId', g1PromptId);
        }catch(Exception exceptionDetails){
            Database.rollback(sp);
            insert Utils.catchErrorLogs('createPE',exceptionDetails.getMessage(), exceptionDetails.getLineNumber(), plantAssetId, '');
            responseMap.put('result', false);
            responseMap.put('g1PromptId', 'None');
        }
        return JSON.serialize(responseMap);
    }
}