unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <formula>Drive_Id__c &amp; &quot;,&quot; &amp;  Customer_Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <formula>Plant__r.Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Master__c/Attribute_Master__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute Master</label>
    <nameField>
        <label>Attribute Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Master__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Master__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attribute Masters</relationshipLabel>
    <relationshipName>Attribute_Masters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/Asset_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Short_Name__c</fullName>
    <label>Asset Short Name</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Base Asset Templates</relationshipLabel>
    <relationshipName>Base_Asset_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Attribute__c/fields/Attribute_Master__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Master__c</fullName>
    <label>Attribute Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Attribute_Master__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Attribute_Master__c</referenceTo>
    <relationshipLabel>Core Atributes</relationshipLabel>
    <relationshipName>Core_Atributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Base_Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link the attributes to the relevant Base Asset</description>
    <label>Base Asset Name</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Attributes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Picklist_Detail__c/Picklist_Detail__c.object-meta.xml
<CustomObject>
    <description>This object has all picklist values related to its picklist master E.g Time Zone is the picklist master and its time zone literals (values) like IST, PST, EST will be here in this object</description>
    <label>Picklist Detail</label>
    <nameField>
        <label>Picklist Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Picklist_Detail__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Picklist Details</relationshipLabel>
    <relationshipName>Picklist_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Picklist_Master__c/Picklist_Master__c.object-meta.xml
<CustomObject>
    <description>This object will have the picklist master details. E.g Time Zone. The time zone literals will be there in Picklist Details object</description>
    <label>Picklist Master</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Picklist_Master__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Picklist Master</relationshipLabel>
    <relationshipName>Picklist_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/CSV_Sorting_Order__c.field-meta.xml
<CustomField>
    <fullName>CSV_Sorting_Order__c</fullName>
    <label>CSV Sorting Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Asset_Name__c</fullName>
    <label>Asset Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Attribute_Info__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Info__c</fullName>
    <label>Attribute Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <formula>Plant_Asset_Prompt_Detail__r.Is_Deleted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Parent_Asset_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Parent_Asset_Short_Name__c</fullName>
    <label>Parent Asset Short Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/DownloadAbMetadataCsv.cls
public with sharing class DownloadAbMetadataCsv {
    @AuraEnabled
    public static String getSiteMetadata(String plantAssetId){ 
        String csvInputsString = '';
        List<Site_Metadata__c> siteMetadataLst = [SELECT Parent_Asset_Short_Name__c, Asset_Short_Name__c, Name, Asset_Name__c, 
        Base_Asset_Template__r.Name, Attribute_Info__c, Account_Plant__r.Customer_Plant_Asset_ID__c, Base_Asset_Template__c,
        Account_Plant__r.Plant_Name__c, Prompt_Information__r.Name FROM Site_Metadata__c 
        WHERE Account_Plant__c =: plantAssetId AND Asset_Short_Name__c != null AND Base_Asset_Template__c != null 
        AND Plant_Asset_Prompt_Detail__r.Is_Deleted__c = false
        ORDER BY Plant_Asset_Prompt_Detail__r.Prompt_Information__r.CSV_Sorting_Order__c ASC NULLS last];
        

        String temVersion = [SELECT Id, TEM_Version__c FROM Account_Plant__c WHERE Id =: plantAssetId].TEM_Version__c;

        if(siteMetadataLst.size()>0){
            Map<String, Set<Id>> attrList = Utils.getCoreAttrIdsBasedOnAttrRequirement(plantAssetId); 
            Set<Id> coreAttrIds = attrList.get(Constants.FILTERED);

            List<Core_Attribute__c> attrLst = [SELECT Id, Name, Attribute_Master__r.Name, Base_Asset_Name__c, Attribute_Master__r.Alias__c,
                Attribute_Master__r.Type__c, Attribute_Master__r.Data_Type__c,  Base_Asset_Name__r.Name, Prompt_Information__r.Name, TEM_Version__c, Show_Path_in_CSV_Generation__c,
                Default_value__c, Attribute_Master__r.Picklist_Master__c 
                FROM Core_Attribute__c 
                WHERE Base_Asset_Name__c != null 
                    AND TEM_Version__c =: temVersion
                    AND Id IN: coreAttrIds];

            List<Picklist_Detail__c> picklistDetails = [SELECT Id, Name, Picklist_Master__c, Picklist_Master__r.Name
            FROM Picklist_Detail__c WHERE Is_Active__c = TRUE AND TEM_Version__c =: temVersion ORDER BY Name ASC];

            Map<String,Object> csvInputsMap = DownloadAbMetadataCsv.getCSVInputsMap(attrLst, siteMetadataLst, picklistDetails);
            csvInputsString = JSON.serialize(csvInputsMap);
            return csvInputsString;
        }else{
            return csvInputsString;
        }    
    }
    
    @AuraEnabled
    public static Map<String,Object> getCSVInputsMap(
    List<Core_Attribute__c> attrLst,
    List<Site_Metadata__c> siteMetadataLst,
    List<Picklist_Detail__c> picklistDetails){
        Map<String,Object> csvInputsMap = new Map<String,Object>();
        csvInputsMap.put('Attributes', attrLst);
        csvInputsMap.put('SiteMetadataRecords', siteMetadataLst);
        csvInputsMap.put('picklistDetails', picklistDetails);
        return csvInputsMap;
    }
    
    @AuraEnabled
    public static Boolean fileUpload(String csvString, String plantAssetId, String fileName){
        try{    
            ContentVersion cv = new ContentVersion();
            cv.Title = fileName;
            cv.PathOnClient = fileName;
            cv.VersionData = Blob.valueOf(csvString);
            cv.IsMajorVersion = true;
            Insert cv;

            Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;

            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = plantAssetId;
            cdl.ContentDocumentId = conDocId;
            cdl.shareType = 'V';
            Insert cdl;
            return true;
        }catch(Exception exceptionDetails){
                String errorMessage = System.Label.AssetBuilderExceptionMessage + ' - ' + exceptionDetails.getMessage();
                System.debug(' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber());
                throw new AuraHandledException(errorMessage);
        }
    }

    @AuraEnabled
    public static Boolean sendDataSiteMetadata(String siteMetadataLstString){ // String plantAssetId, String fileName
        try{    
            List<Site_Metadata__c> siteMetadataLst = (List<Site_Metadata__c>)System.JSON.deserialize(siteMetadataLstString, List<Site_Metadata__c>.class); 
            List<Site_Metadata__c> siteMetadataLstUpdate = new List<Site_Metadata__c>(); 

            for(Site_Metadata__c siteMetadata : siteMetadataLst){
                String attrInfoQuotesRemovedValue = (siteMetadata.Attribute_Info__c.removeEnd('"')).removeStart('"');
                siteMetadata.Attribute_Info__c = attrInfoQuotesRemovedValue;
                siteMetadataLstUpdate.add(siteMetadata);
            }

            if(siteMetadataLstUpdate.size() > 0){
                update siteMetadataLstUpdate;
            }

            return true;
        }catch(Exception exceptionDetails){
                String errorMessage = System.Label.AssetBuilderExceptionMessage + ' - ' + exceptionDetails.getMessage();
                System.debug(' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber());
                throw new AuraHandledException(errorMessage);
        }
    }
}