unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <formula>TEXT(Plant__r.Asset_Class__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Class</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar PV</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Other Renewable</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Megawatt_AC__c.field-meta.xml
<CustomField>
    <fullName>Megawatt_AC__c</fullName>
    <label>Megawatt AC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Megawatt_DC__c.field-meta.xml
<CustomField>
    <fullName>Megawatt_DC__c</fullName>
    <label>Megawatt DC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <formula>TEXT(Product__r.Asset_Class__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Class</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/MWp_Quantity__c.field-meta.xml
<CustomField>
    <fullName>MWp_Quantity__c</fullName>
    <label>MW Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Product__r.Product_Line__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <formula>TEXT(Product__r.Product_Type__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Amendment_Quoted</fullName>
                <label>Amendment Quoted</label>
            </value>
            <value>
                <fullName>Renewal Quoted</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Class</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>&quot;Software</fullName>
                <isActive>false</isActive>
                <label>&quot;Software</label>
            </value>
            <value>
                <fullName>Professional Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Professional Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Pro</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
            </value>
            <value>
                <fullName>Add-ons</fullName>
            </value>
            <value>
                <fullName>Breeze Development</fullName>
            </value>
            <value>
                <fullName>Core Lite</fullName>
            </value>
            <value>
                <fullName>Ekho</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>&quot;Core</fullName>
                <isActive>false</isActive>
                <label>&quot;Core</label>
            </value>
            <value>
                <fullName>Edge Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Edge Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Services__c.field-meta.xml
<CustomField>
    <fullName>Product_Services__c</fullName>
    <label>Product Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Customization</fullName>
            </value>
            <value>
                <fullName>Consulting/Other</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Subscription__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hydro</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Other Renewable</fullName>
    </customValue>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Wind</fullName>
    </customValue>
    <customValue>
        <fullName>All Renewables (Agnostic)</fullName>
    </customValue>
    <masterLabel>Asset Class</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SaaS</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Recurring</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/AccountHierarchyforProductfamilyTest.cls
@isTest
public class AccountHierarchyforProductfamilyTest {
	@TestSetup
    public static void setupData(){
        
        // Test data creation :
        List<String> assetClassList = new List<String>{'Solar', 'Wind','Hydro','Storage','Industrial','Other Renewable'};
        List<String> productFamily = new List<String>{'Drive', 'Greenbyte','BluePoint','Ekhosoft','Drive', 'Greenbyte'};
        
        List<Account> actList = new List<Account>();
        
        Account act = new Account();
        act.Name  = 'AccountHierarchyMWTest';
        insert act;
        actList.add(act);
        
        Account act2 = new Account();
        act2.Name  = 'Test-2022';
        act2.ParentId = act.Id;
        insert act2;
        actList.add(act2);
        
        Account act3 = new Account();
        act3.Name  = 'Test-2023';
        insert act3;
        actList.add(act3);
         
       	List<Plant__c> plantList = new List<Plant__c>();
        for(Integer i = 0 ; i<6 ; i++){
            Plant__c pl = new Plant__c();
            //pl.Name = 'Test Plant - '+(i+1);
            pl.Megawatt_AC__c = i+5;
            pl.Megawatt_DC__c = i+10;
            pl.Asset_Class__c = assetClassList[i];
            plantList.add(pl);
        }
		insert plantList;
        
        Test.startTest();
        List<Account_Plant__c> accPlantList = new List<Account_Plant__c>();
        for(Integer i = 0 ; i<6 ; i++){
            Account_Plant__c accPlant = new Account_Plant__c();
            //accPlant.Name = 'Test Acc Plant - '+(i+1);
            accPlant.Account__c = math.mod(i, 2) == 0 ? act.Id : act2.Id;
            accPlant.Plant__c = plantList[i].Id;
            accPlant.Status__c ='Active';
            accPlantList.add(accPlant);
            
        }
        insert accPlantList;
        
        Contract cnt = new Contract();
        cnt.AccountId = act.Id;
        cnt.Status = 'Draft';
        cnt.StartDate = System.today().addDays(-5);
        cnt.ContractTerm = 5;
        insert cnt;
       
        cnt.Status = 'Activated';
        update cnt;
        
        
        
        List<Product2> prdList = new List<Product2>();
        for(Integer i = 0 ; i<6 ; i++){
            Product2 prd = new Product2();
            prd.Name = 'Test Product - '+(i+1);
            prd.QuantityUnitOfMeasure = 'MWp';
            prd.Product_Line__c = 'Core'; 
            prd.Product_Category__c = 'Software';
            prd.Product_Type__c = 'SaaS';
            prd.Product_Services__c = 'N/A';
            prd.QuantityUnitOfMeasure = 'MWp';
            prd.Asset_Class__c = 'Solar';
            prd.Family = productFamily[i];
            prdList.add(prd);
        }
        insert prdList;
        
        SBQQ__Subscription__c subs = new SBQQ__Subscription__c();
        subs.SBQQ__Quantity__c = 100;
        //subs.SBQQ__Product__c = prdList[i].Id;
        subs.SBQQ__Contract__c = cnt.Id;
        subs.SBQQ__Account__c = act.Id;
        insert subs;
        
        List<Plant_Product_Transaction__c> pptList = new List<Plant_Product_Transaction__c>();
        for(Integer i = 0 ; i<6 ; i++){
            Plant_Product_Transaction__c ppt = new Plant_Product_Transaction__c();   
            ppt.Name = 'AccountHierarch- Catan- DR-CR-SW-SS-N/A-AL-MW-LA - '+(i+1);
            ppt.Plant__c = accPlantList[i].Id;
            ppt.Status__c = 'Contracted';
            ppt.Subscription__c = subs.Id;
            ppt.Product__c = prdList[i].Id;
            ppt.Contract__c = cnt.Id;
            ppt.MWp_Quantity__c = 11;
            ppt.Account__c = math.mod(i, 2) == 0 ? act.Id : act2.Id;
            if(i == 5)  ppt.Account__c = act3.Id;
            pptList.add(ppt);
        }
        insert pptList;
        Test.stopTest();
    }
    
     @isTest
    public static void testMethod02(){
        List<Plant_Product_Transaction__c> pptList = [Select Id FROM Plant_Product_Transaction__c]; 
        Test.startTest();
        
        AccountHierarchyforProductfamily upd = new AccountHierarchyforProductfamily();
        Database.executeBatch(upd);
        
        Test.stopTest();
    }
}