unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/Asset_Builder_Report_Data__c.object-meta.xml
<CustomObject>
    <label>Completeness Report Data</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Asset Builder Report Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completeness Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Completeness Report Data</relationshipLabel>
    <relationshipName>Asset_Builder_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Asset Builder Report Data</relationshipLabel>
    <relationshipName>Completeness_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Archived?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Completeness Report Data</relationshipLabel>
    <relationshipName>Asset_Builder_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Total_Attribute_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Attribute_Count__c</fullName>
    <label>Total Attribute Count</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Total_Completed_Attribute_Count__c.field-meta.xml
<CustomField>
    <fullName>Total_Completed_Attribute_Count__c</fullName>
    <label>Total Count of Completed Attribute</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/CompletenessReportSectionConfig__mdt.object-meta.xml
<CustomObject>
    <label>CompletenessReportSectionConfig</label>
    <pluralLabel>CompletenessReportSectionConfig</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>This field values should be in sync with Prompt Information Object - Prompt Type field</description>
    <inlineHelpText>To get the respective prompt details in report</inlineHelpText>
    <label>App Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Builder</fullName>
                <default>true</default>
                <label>Asset Builder</label>
            </value>
            <value>
                <fullName>Interface Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Prompt_Type__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Type__c</fullName>
    <label>Prompt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wind - Onshore</fullName>
                <default>true</default>
                <label>Wind - Onshore</label>
            </value>
            <value>
                <fullName>MetMast</fullName>
            </value>
            <value>
                <fullName>SubstationSwitchgear</fullName>
            </value>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Report_Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Report_Display_Order__c</fullName>
    <inlineHelpText>Report Section Display Order</inlineHelpText>
    <label>Report Section Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Section_Label__c.field-meta.xml
<CustomField>
    <fullName>Section_Label__c</fullName>
    <inlineHelpText>This field value is used as completeness report section label</inlineHelpText>
    <label>Section Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Summary_Report_First_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Summary_Report_First_Column_Label__c</fullName>
    <inlineHelpText>This field value will be used in completeness summary report first column label</inlineHelpText>
    <label>Summary Report First Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/CSV_Sorting_Order__c.field-meta.xml
<CustomField>
    <fullName>CSV_Sorting_Order__c</fullName>
    <label>CSV Sorting Order</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Prompt_Type__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Type__c</fullName>
    <label>Prompt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Build Prompt</fullName>
            </value>
            <value>
                <fullName>Detail Prompt</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
            <value>
                <fullName>MetMast</fullName>
            </value>
            <value>
                <fullName>SubstationSwitchgear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/CompletenessReportSummary.cls
public with sharing class CompletenessReportSummary {
    @AuraEnabled
    public Static String getCompletenessReportSummary(String plantAssetId) {
        Map<String, Object> reportInputData = new  Map<String, Object>();

        List<String> pfServiceProducts = Utils.getAttrReqSysNamesFrmG1(plantAssetId);
        List<Asset_Builder_Report_Data__c> assetBuilderReportData = [SELECT Id, Name, Base_Asset_Template__r.Name, Is_Archived__c, Account_Plant__c, Prompt_Information__r.Name, System__c,
        Total_Attribute_Count__c, Total_Completed_Attribute_Count__c, Type__c, Prompt_Information__r.CSV_Sorting_Order__c,
        Prompt_Information__r.Type__c    
        FROM Asset_Builder_Report_Data__c 
        WHERE Account_Plant__c =: plantAssetId
        AND Is_Archived__c = FALSE ORDER BY Prompt_Information__r.CSV_Sorting_Order__c DESC];
            
        List<CompletenessReportSectionConfig__mdt> promptTypeLst  = new List<CompletenessReportSectionConfig__mdt>();
        for(CompletenessReportSectionConfig__mdt promptType : 
            [SELECT Id, App_Name__c, Prompt_Type__c, Section_Label__c, Report_Display_Order__c,
            Summary_Report_First_Column_Label__c
            FROM CompletenessReportSectionConfig__mdt WHERE App_Name__c = 'Asset Builder'
            ORDER BY Report_Display_Order__c ASC]){
                promptTypeLst.add(promptType);
        }

        reportInputData.put('systemName', pfServiceProducts);
        reportInputData.put('completnessReport', assetBuilderReportData);
        reportInputData.put('promptType', promptTypeLst);

        return JSON.serialize(reportInputData);
    }
}