unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/AB_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>AB_Approval_Status__c</fullName>
    <label>AB-Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Drive_Id__c.field-meta.xml
<CustomField>
    <fullName>Drive_Id__c</fullName>
    <label>Drive Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <formula>Plant__r.Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <formula>TEXT(Plant__r.Renewable_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewable Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SAT__c/SAT__c.object-meta.xml
<CustomObject>
    <label>SAT</label>
    <nameField>
        <label>SAT Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>SATs</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SAT__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>SATs</relationshipLabel>
    <relationshipName>SATs1</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SAT__c/fields/Customer_Acceptance_Status__c.field-meta.xml
<CustomField>
    <fullName>Customer_Acceptance_Status__c</fullName>
    <inlineHelpText>Approved = No concerns or comments remain open for resolution.


Rejected = Known concerns do not meet the contractual requirements for contract services. Requires rework and possible re-submission of SAT validation report.</inlineHelpText>
    <label>Customer Acceptance Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>On-Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SAT__c/fields/Customer_User__c.field-meta.xml
<CustomField>
    <fullName>Customer_User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Customer User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>SATs3</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SAT__c/fields/SAT_Approval_Status__c.field-meta.xml
<CustomField>
    <fullName>SAT_Approval_Status__c</fullName>
    <inlineHelpText>Approved-no concerns or comments remain open for resolution</inlineHelpText>
    <label>SAT Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SAT__c/fields/SAT_Status__c.field-meta.xml
<CustomField>
    <fullName>SAT_Status__c</fullName>
    <label>SAT Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
            </value>
            <value>
                <fullName>Submitted - Pending Customer Review</fullName>
            </value>
            <value>
                <fullName>Remediation Required</fullName>
            </value>
            <value>
                <fullName>Remediation in Progress</fullName>
            </value>
            <value>
                <fullName>Remediation in Progress - Partial</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Cancelled</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/SATApprovalHandlerTest.cls
/**
**/
@isTest
public class SATApprovalHandlerTest {
    @testSetup static void methodName() {
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;
        Account_Plant__c pa = new Account_Plant__c();
//        pa.Name = 'Plant Asset Test1';
//        pa.RecordTypeId = [SELECT id from RecordType where Name ='Parent Asset'].Id;
//        pa.Plant_Name__c = 'test1';
        pa.Project_Lifecycle_Status__c = 'Pending';
//        pa.Implementation_Status__c = 'Pending Customer Submission';
//        pa.Renewable_Type__c = Constants.WIND;
        insert pa;
        Account_Plant__c newPlantAsset1 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','21.21.21',newTemVersion.Id);
//        newPlantAsset1.Parent__c = pa.Id;
        insert newPlantAsset1;
        newPlantAsset1.Project_Lifecycle_Status__c = 'Data Validation';
 //       newPlantAsset1.Implementation_Status__c = 'In Progress';
        newPlantAsset1.AB_Approval_Status__c = 'Approved';
        update newPlantAsset1;
        Account_Plant__c newPlantAsset2 = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','21.21.21.1',newTemVersion.Id);
//        newPlantAsset2.Parent__c = pa.Id;
        insert newPlantAsset2;
        
        //Create first SAT
        list<Sat__c> newsatlst = new list <Sat__c>();
        Sat__c firstSAT1 = new Sat__c();
        firstSAT1.Name = 'firstSAT';
        firstSAT1.Account_Plant__c = newPlantAsset1.Id;
        insert firstSAT1;
    }
    
    @isTest static void setSubmitForApprovalTest(){
        User u = new User(
        ProfileId = [SELECT Id FROM Profile WHERE Name = 'System Administrator'].Id,
        LastName = 'last',
        Email = 'puser000@cittest.com',
        Username = 'puser000@cittest.com' + System.currentTimeMillis(),
        CompanyName = 'TEST',
        Title = 'title',
        Alias = 'alias',
        TimeZoneSidKey = 'America/Los_Angeles',
        EmailEncodingKey = 'UTF-8',
        LanguageLocaleKey = 'en_US',
        LocaleSidKey = 'en_US');
        insert u;
        
        SAT__C sat = [SELECT Id, Customer_Acceptance_Status__c, Account_Plant__r.Drive_Id__c, SAT_Approval_Status__c,
                      SAT_Status__c, Customer_User__c FROM Sat__c WHERE 
                      Account_Plant__r.Drive_Id__c ='21.21.21' LIMIT 1];
        sat.Customer_User__c = u.Id;
        sat.SAT_Approval_Status__c  = '';
        update sat;
        Approval.ProcessSubmitRequest app = new Approval.ProcessSubmitRequest();
		    app.setObjectId(sat.id);
        Approval.ProcessResult result = Approval.process(app);
        SATApprovalHandler.setSubmitForApproval(sat.Id);
        SATApprovalHandler.getApprovalHistory(sat.Id);
        SATApprovalHandler.reassignApproval(sat.Id, u.Id, 'Reassign');
        SATApprovalHandler.processStep(sat.Id, 'Approve', 'Approve');
    }
}