unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/Implementation_Wizard_Form_Detail__c.object-meta.xml
<CustomObject>
    <description>To store file and API request and response details of implementation wizard form</description>
    <label>Implementation Wizard Form Detail</label>
    <nameField>
        <label>Implementation Wizard Form Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Wizard Form Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to plant asset related to the form API request</description>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Implementation Wizard Form Details</relationshipLabel>
    <relationshipName>Implementation_Wizard_Form_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Is_Created_in_Neuron_Update__c.field-meta.xml
<CustomField>
    <fullName>Is_Created_in_Neuron_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <description>This field help us to identify the records created through Neuron Template Update.</description>
    <label>Is Created in N3uron Update</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Response_Message__c.field-meta.xml
<CustomField>
    <fullName>Response_Message__c</fullName>
    <description>To track the response message from API</description>
    <label>Response Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>To track the status of the API request</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/SendNeuronTemplateDetail.cls
/**
 * Created by karthikeyan.k on 6/23/2021.
 */

public with sharing class SendNeuronTemplateDetail {

    @AuraEnabled
    public static Map<String, Object> callNeuronAPI(String requestParameters, String assetModelBase64, String templatesBase64){

        String plantAssetId;
        String customerPlantAssetID;
        String jsonStream;
        Map<String, Object> outputJSON = new Map<String, Object>();

        Map<String, String> requestParametersMap = (Map<String, String>) json.deserialize(requestParameters, Map<String, String>.class);

        plantAssetId = requestParametersMap.get('plantAssetId');
        customerPlantAssetID = [SELECT Customer_Plant_Asset_ID__c FROM Account_Plant__c WHERE id =: plantAssetId].Customer_Plant_Asset_ID__c;
        //String restURI = 'callout:ImpWizFormAPIDetails/apitype/AQS/assetbuilder?elementPath={0}';
        String restURI = 'callout:NeuronTemplateAPIDetail?elementPath={0}';

        restURI = String.format(restURI, new String[]{customerPlantAssetID});
        
        String requestBody = '{'+
                '"assetModelBase64": "'+assetModelBase64+'",'+ // assetModelBase64
                '"templatesBase64": "'+templatesBase64+'"'+'}'; // templatesBase64

        Http http = new Http();
        HttpRequest request = new HttpRequest();
        request.setEndpoint(restURI);
        request.setMethod('POST');
        request.setHeader('Content-Type', 'application/json');
        request.setHeader('Ocp-Apim-Trace', 'true');
        request.setHeader('Ocp-Apim-Subscription-Key', '{!$Credential.Password}');
        request.setBody(requestBody);
        request.setTimeout(120000);
        HttpResponse response = http.send(request);
        jsonStream = response.getBody();
        outputJSON = parseResponse(jsonStream, requestParametersMap);
        return outputJSON;
    }

    public static Map<String, Object> parseResponse(String jsonStream, Map<String, String> requestParametersMap){
        Map<String, Object> jsonMap = (Map<String, Object>)JSON.deserializeUntyped(jsonStream);
        Map<String, Object> outputJSON = new Map<String, Object>();

        String resStatus = '';
        if(jsonMap.containsKey('status')){
            resStatus = ((String)jsonMap.get('status')).toLowercase();
        }

        outputJSON.put('status', resStatus );

        if(jsonMap.containsKey('details')){
            if(resStatus == 'success'){
                Map<String, Object> jsonMapSuccess = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(jsonMap.get('details')));
                String fileContent = (String)jsonMapSuccess.get('fileContent');
                String fileName = (String)jsonMapSuccess.get('fileName');
                String fileExtension = (String)jsonMapSuccess.get('fileExtension');
                String impWizStatus = createImpWizFormDetails(resStatus, '', requestParametersMap, jsonStream);

                if(impWizStatus.length() == 18){
                    ContentDocumentLink cdl = createContentVersion(fileContent, fileName, fileExtension, impWizStatus, requestParametersMap);
                    outputJSON.put('cdID', cdl.ContentDocumentId );
                    outputJSON.put('status', 'success');
                    outputJSON.put('impWizStatus', impWizStatus);
                }else{
                    outputJSON.put('status', 'error');
                    outputJSON.put('errorMessage',System.Label.ImplementationWizFormDetailNotCreated);
                }
            }else if(resStatus == 'error'){
                Map<String, Object> jsonMapError = (Map<String, Object>)JSON.deserializeUntyped(JSON.serialize(jsonMap.get('details')));
                String code = (String)jsonMapError.get('code');
                String userMessage = (String)jsonMapError.get('userMessage');
                String devMessage = (String)jsonMapError.get('devMessage');

                String resMes = code + ' \n ';
                resMes += (userMessage != null && userMessage != '') ? userMessage + ' \n ' : '';
                resMes += (devMessage != null && devMessage != '') ? devMessage : '';

                String impWizStatus = createImpWizFormDetails(resStatus, resMes, requestParametersMap, jsonStream);
                outputJSON.put('errorMessage', userMessage );
            }
        } else if(jsonMap.containsKey('errors')) {

            outputJSON.put('status', 'error');
            outputJSON.put('errorMessage', 'The input is not valid' );
        }

        return outputJSON;
    }

    public static String createImpWizFormDetails(String Status, String resMessage, Map<String, String> requestParametersMap, String jsonStream){
        try{
            String plantAssetId;

            plantAssetId = requestParametersMap.get('plantAssetId');

            List<Account_Plant__c> plantAsset = [SELECT Id FROM Account_Plant__c WHERE Id =: plantAssetId];

            Implementation_Wizard_Form_Detail__c impWiz = new Implementation_Wizard_Form_Detail__c(
                    Account_Plant__c = (plantAsset.size() > 0) ? plantAsset[0].Id : null,
                    Status__c = Status,
                    Response_Message__c = (Status == 'success') ? '' : resMessage,
                    Is_Created_in_Neuron_Update__c = true
            );

            insert impWiz;
            return String.valueof(impWiz.Id);

        }catch(exception exceptionDetails){
            String errorMessage = ' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber();
            System.debug(errorMessage);
            throw new AuraHandledException(errorMessage);
        }
    }

    public static ContentDocumentLink createContentVersion(String fileContent, String fileName, String fileExtension,
            String impWizRecId, Map<String, String> requestParametersMap){

        try{
            ContentVersion cv = new ContentVersion();
            cv.Title = fileName;
            cv.PathOnClient = fileName + '.' +fileExtension;
            cv.VersionData = EncodingUtil.base64Decode(fileContent);
            cv.IsMajorVersion = true;
            Insert cv;

            Id conDocId = [SELECT ContentDocumentId FROM ContentVersion WHERE Id =:cv.Id].ContentDocumentId;

            ContentDocumentLink cdl = New ContentDocumentLink();
            cdl.LinkedEntityId = impWizRecId;
            cdl.ContentDocumentId = conDocId;
            cdl.shareType = 'V';
            Insert cdl;

            return cdl;
        }catch(Exception exceptionDetails){
            String errorMessage = ' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber();
            System.debug(errorMessage);
            throw new AuraHandledException(errorMessage);
        }
    }
}