unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Asset_Builder_Status__c.field-meta.xml
<CustomField>
    <fullName>Asset_Builder_Status__c</fullName>
    <label>Asset Builder Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In-Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Commercial_Operating_Date__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Operating_Date__c</fullName>
    <formula>Plant__r.Commercial_Operating_Date__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Commercial Operating Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Drive_Id__c.field-meta.xml
<CustomField>
    <fullName>Drive_Id__c</fullName>
    <label>Drive Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Plant__r.Latitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Plant__r.Longitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <formula>TEXT(Plant__r.Renewable_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewable Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <formula>TEXT( Plant__r.Timezone__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Base Asset Templates</relationshipLabel>
    <relationshipName>Base_Asset_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/Commercial_Operating_Date__c.field-meta.xml
<CustomField>
    <fullName>Commercial_Operating_Date__c</fullName>
    <label>Commercial Operating Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <description>Used for Asset Builder</description>
    <label>Renewable Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Hybrid - Solar PV / BESS</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>BESS</fullName>
            </value>
            <value>
                <fullName>Hybrid - Fuel Cell / BESS</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Biomass</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morocco Standard Time</fullName>
            </value>
            <value>
                <fullName>Coordinated Universal Time</fullName>
            </value>
            <value>
                <fullName>GMT Standard Time</fullName>
            </value>
            <value>
                <fullName>Greenwich Standard Time</fullName>
            </value>
            <value>
                <fullName>W. Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Central Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Romance Standard Time</fullName>
            </value>
            <value>
                <fullName>Central European Standard Time</fullName>
            </value>
            <value>
                <fullName>W. Central Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>Namibia Standard Time</fullName>
            </value>
            <value>
                <fullName>Jordan Standard Time</fullName>
            </value>
            <value>
                <fullName>GTB Standard Time</fullName>
            </value>
            <value>
                <fullName>Middle East Standard Time</fullName>
            </value>
            <value>
                <fullName>Egypt Standard Time</fullName>
            </value>
            <value>
                <fullName>Syria Standard Time</fullName>
            </value>
            <value>
                <fullName>South Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>FLE Standard Time</fullName>
            </value>
            <value>
                <fullName>Turkey Standard Time</fullName>
            </value>
            <value>
                <fullName>Jerusalem Standard Time</fullName>
            </value>
            <value>
                <fullName>E. Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Arabic Standard Time</fullName>
            </value>
            <value>
                <fullName>Kaliningrad Standard Time</fullName>
            </value>
            <value>
                <fullName>Arab Standard Time</fullName>
            </value>
            <value>
                <fullName>E. Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>Iran Standard Time</fullName>
            </value>
            <value>
                <fullName>Arabian Standard Time</fullName>
            </value>
            <value>
                <fullName>Azerbaijan Standard Time</fullName>
            </value>
            <value>
                <fullName>Russian Standard Time</fullName>
            </value>
            <value>
                <fullName>Mauritius Standard Time</fullName>
            </value>
            <value>
                <fullName>Georgian Standard Time</fullName>
            </value>
            <value>
                <fullName>India Standard Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Prompt_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Id__c</fullName>
    <label>Prompt Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/TEM_Version__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <inlineHelpText>Select Active if this record is the current active version.
Note: Only one version can be active at a time.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Draft</fullName>
            </value>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Archived</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/G1IntialPlantInfoPromptTest.cls
/**
**/
@istest
public with sharing class G1IntialPlantInfoPromptTest {
    @testSetup
    public static void testDataSetup() { 
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;
        
        Account acc = new account();
        acc.name ='Test';
        Insert acc;
        
        Account_Plant__c newPlantAssetParent = TestDataFactory.createPlantAsset(Constants.SOLAR,'Drive','7777.77.777',newTemVersion.Id);
        
        insert newPlantAssetParent;
        List<Account_Plant__c> plantAssetLst= new List<Account_Plant__c>();

        list<String> renewableType = new list<String>{Constants.SOLAR,Constants.WIND,Constants.SOLAR};
		
        List<Plant__c> plantLst= new List<Plant__c>();
        for(integer i = 0; i<3; i++){
            Plant__c plant = new Plant__c();
            plant.Name = 'Test Plant' ;    
            plant.Renewable_Type__c=renewableType[i];
            plant.Timezone__c= 'India Standard Time';
            plant.Latitude__c='45.5017';
            plant.Longitude__c='-75.123';
            plant.Commercial_Operating_Date__c = system.today();
            plantLst.add(plant);
        }
        insert plantLst;
        
        for(integer i = 0; i<3; i++){
            Account_Plant__c newPlantAsset = new Account_Plant__c();
            newPlantAsset.Plant__c = plantLst[i].id;
            newPlantAsset.Asset_Builder_Status__c = '';
            newPlantAsset.Drive_Id__c = '0000.000.00' + i;
            newPlantAsset.Drive_Id__c = '7777.77.777';
            newPlantAsset.TEM_Version__c = newTemVersion.Id;
            newPlantAsset.Project_Lifecycle_Status__c = 'Pending';
            newPlantAsset.Asset_Builder_Status__c = 'Completed';
//            newPlantAsset.Implementation_Status__c = 'In Progress';
            newPlantAsset.Account__c = acc.id;
            plantAssetLst.add(newPlantAsset);
        }
        insert plantAssetLst;
        Base_Asset_Template__c newBaseAssetTemplate = TestDataFactory.createBaseAssetTemplate(Constants.BASE_INVERTER, newTemVersion.Id);
        insert newBaseAssetTemplate;
        Prompt_Information__c previousPromptInfo = TestDataFactory.createPromptInformation(Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT,
                                                                                        newBaseAssetTemplate.Id, newTemVersion.Id);
        insert previousPromptInfo ; 
        Prompt_Information__c nextPromptInfo = TestDataFactory.createPromptInformation(Constants.P1_PLANT_INFO_PROMPT_SOLAR,
                                                                                        newBaseAssetTemplate.Id, newTemVersion.Id);
        nextPromptInfo.Prompt_Id__c = 'prompt2';                                                                              
        insert nextPromptInfo;

        //update TemVersion status to Active
        newTemVersion.Status__c = 'Active';
        update newTemVersion;
    }
    public static testMethod void g1InitialPlantInfoTest(){
        Boolean fromPlaantAssetLsttrue = true;
        Account_Plant__c plantAssetLst = [SELECT Id, Name, Commercial_Operating_Date__c, Latitude__c, Longitude__c, PF_Service_Product__c,
              Status__c, Plant_Name__c, Drive_Id__c,Account__c,
               Renewable_Type__c, Timezone__c,  TEM_Version__c
                FROM Account_Plant__c ORDER BY Name ASC limit 1];
        string querPlantAsset = G1IntialPlantInfoPrompt.queryPlantAssetList(plantAssetLst.Id,fromPlaantAssetLsttrue);
        string plantassetId=plantAssetLst.id;
        string accountid= plantAssetLst.Account__c;
        string rType=plantAssetLst.Renewable_Type__c;
        string pfServiceProduct=plantAssetLst.PF_Service_Product__c;
        String plantAssetIdNull = '';
        string queryPlantAssetElse = G1IntialPlantInfoPrompt.queryPlantAssetList(plantAssetIdNull,fromPlaantAssetLsttrue);
        list<Account_Plant__c> queryPlantAssetAcc = G1IntialPlantInfoPrompt.queryPlantAssetListAcc(fromPlaantAssetLsttrue,accountid);
        map<String, String> jsonInputParametersAndValuesMap = new Map<String, String>{'isBulkUpload' => 'false', 'isBulkUploadMultipleBAT' => 'false'};
        map<String, String> additionalParamsMap = new Map<String, String>{'isReadOnly' => 'false', 'bifacialModules' => 'true'}; 
        map<String, String> bifacialValuesMap = new Map<String, String>{'bifacialModules' => 'true'};
        Boolean saveDataCheck = G1IntialPlantInfoPrompt.savePlantAsset(plantassetId,'2','3',rType,pfServiceProduct,JSON.serialize(bifacialValuesMap));
        
       // Decimal metMastCount = [SELECT Id, Name,Met_Mast__c FROM Account_Plant__c WHERE Id =: plantAssetLst.Id].Met_Mast__c;
       // System.assertEquals(1, metMastCount);

        String nextPromptResFinder = G1IntialPlantInfoPrompt.findNextPromptId(plantassetId,'2','3',rType,pfServiceProduct,JSON.serialize(additionalParamsMap),JSON.serialize(jsonInputParametersAndValuesMap));
        Map<String,String> nextPromptResponse = 
            (Map<String,String>) JSON.deserialize(nextPromptResFinder, Map<String,String>.class);
        String nextPromptId = (String)nextPromptResponse.get('nextPromptId');
        System.assertEquals(PromptNavigationHelper.findPromptId(Constants.P1_PLANT_INFO_PROMPT_SOLAR),nextPromptId);

        String promptResFinderError = G1IntialPlantInfoPrompt.findNextPromptId(plantassetId,'2','3',rType,pfServiceProduct,JSON.serialize(additionalParamsMap),JSON.serialize(jsonInputParametersAndValuesMap));
        Map<String,String> promptResponseError = 
            (Map<String,String>) JSON.deserialize(promptResFinderError, Map<String,String>.class);
        String nextPromptIdError = (String)promptResponseError.get('nextPromptId');
        string querySite = G1IntialPlantInfoPrompt.getSiteMetadata(plantassetId);
    }
}