unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RAID__c/RAID__c.object-meta.xml
<CustomObject>
    <description>This is created as part of REQ-2739 for cloud coach</description>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID-{0000}</displayFormat>
        <label>RAID ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RAID__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>RAIDS</relationshipLabel>
    <relationshipName>RAIDS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RAID__c/fields/Manual_Submission_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Manual_Submission_DateTime__c</fullName>
    <label>Manual Submission DateTime</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/RAID__c/recordTypes/RFI.recordType-meta.xml
<RecordType>
    <fullName>RFI</fullName>
    <active>true</active>
    <label>RFI</label>
</RecordType>

unpackaged/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RFI_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>RFI Items</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Implementation_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Implementation Blocked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/RAID__c.field-meta.xml
<CustomField>
    <fullName>RAID__c</fullName>
    <label>RAID</label>
    <referenceTo>RAID__c</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/RFI_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Item_Status__c</fullName>
    <label>RFI Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
                <default>true</default>
                <label>Drafting</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/updateRFIstatus.cls
/**
 * @description       :
 * @author            : 
 * @group             :
 * @last modified on  : 
 * @last modified by  : 
 * Modifications Log
 * Ver   Date         Author                   
 * 1.0   ?            
 * 1.1         Changed Picklist Status values, refactored for bulkification
 **/
public class updateRFIstatus {
  public static void getrfidetails(List<RFI_Detail__c> rfiDetailsLst) {
    Set<Id> rfiId = new Set<Id>();
    System.debug('rfiDetailsLst' + rfiDetailsLst.size());
    for (RFI_Detail__c a : rfiDetailsLst) {
      rfiId.add(a.RAID__c);
    }

    List<RAID__c> rfis = new List<RAID__c>(
      [
        SELECT
          Id,
          Account_Plant__c,
          Manual_Submission_DateTime__c ,
          Account_Plant__r.Project_Lifecycle_Status__c,
          RFI_Status__c,          
          (
            SELECT Id, RAID__c, RFI_Item_Status__c, Implementation_Blocked__c
            FROM RFI_Detail__r
            WHERE RFI_Item_Status__c != 'Drafting'
          )
        FROM RAID__c
        WHERE Id IN :rfiId
      ]
    );

    List<RAID__c> updateRFIs = new List<RAID__c>();
    List<Account_Plant__c> updatePlantAssets = new List<Account_Plant__c>();

    for (RAID__c rfi : rfis) {
      Boolean inProgress = false;
      Boolean submitted = false;
      Boolean closed = false;
      Boolean blocked = false;
      Boolean requested = false;
      Boolean drafting = false;

      for (RFI_Detail__c rfiVar : rfi.RFI_Detail__r) {
        if (rfiVar.RFI_Item_Status__c == 'Drafting') {
          drafting = true;
        } else if (
          rfiVar.RFI_Item_Status__c == 'Closed' ||
          rfiVar.RFI_Item_Status__c == 'Canceled' ||
          rfiVar.RFI_Item_Status__c == 'Cannot Complete'
        ) {
          closed = true;
        } else if (rfiVar.RFI_Item_Status__c == 'In Progress' || rfiVar.RFI_Item_Status__c == 'Needs Detail') {
          inProgress = true;
        } else if (rfiVar.RFI_Item_Status__c == 'Submitted') {
          submitted = true;
        } else if (rfiVar.RFI_Item_Status__c == 'Requested') {
          requested = true;
        }
        if (
          rfiVar.Implementation_Blocked__c == true &&
          (rfiVar.RFI_Item_Status__c == 'In Progress' ||
          rfiVar.RFI_Item_Status__c == 'Needs Detail' ||
          rfiVar.RFI_Item_Status__c == 'Requested')
        ) {
          blocked = true;
        }
      }

      if (drafting) {
        rfi.RFI_Status__c = 'Drafting';
      } else if (inProgress && rfi.Manual_Submission_DateTime__c == null) {
        rfi.RFI_Status__c = 'In Progress';
      } else if (requested && rfi.Manual_Submission_DateTime__c == null) {
        rfi.RFI_Status__c = 'Requested';
      } else if (submitted) {
        rfi.RFI_Status__c = 'Submitted';
      } else if (closed && !inProgress && !requested) {
        rfi.RFI_Status__c = 'Closed';
      }
      rfi.Implementation_Blocked__c = blocked;
      updateRFIs.add(rfi);
/*
      Account_Plant__c plantAsset = rfi.Account_Plant__r;
      if (plantAsset.Project_Lifecycle_Status__c != 'Pending') {
        if (blocked && plantAsset.Implementation_Status__c != 'Blocked') {
          plantAsset.Implementation_Status__c = 'Blocked';
          updatePlantAssets.add(plantAsset);
        } else if (!blocked && plantAsset.Implementation_Status__c != 'In Progress') {
          plantAsset.Implementation_Status__c = 'In Progress';
          updatePlantAssets.add(plantAsset);
        }
      }*/
    }

    update updateRFIs;
    if (!updatePlantAssets.isEmpty())
      update updatePlantAssets;
  }
}