unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RAID__c/RAID__c.object-meta.xml
<CustomObject>
    <description>This is created as part of REQ-2739 for cloud coach</description>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID-{0000}</displayFormat>
        <label>RAID ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RAID__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>RAIDS</relationshipLabel>
    <relationshipName>RAIDS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RFI_Categories__c/RFI_Categories__c.object-meta.xml
<CustomObject>
    <label>RFI Category</label>
    <nameField>
        <label>RFI Category</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Categories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RFI_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>RFI Items</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Category_Type__c.field-meta.xml
<CustomField>
    <fullName>Category_Type__c</fullName>
    <label>Category Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Missing/Incomplete Data</fullName>
                <default>true</default>
                <label>Missing/Incomplete Data</label>
            </value>
            <value>
                <fullName>Incorrect Information</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Implementation_Blocked__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Blocked__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Implementation Blocked</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Incorrect_Category__c.field-meta.xml
<CustomField>
    <fullName>Incorrect_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Incorrect Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipLabel>RFI Items</relationshipLabel>
    <relationshipName>RFI_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Missing_Incomplete_Category__c.field-meta.xml
<CustomField>
    <fullName>Missing_Incomplete_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Missing/Incomplete Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipLabel>RFI Items (Missing/Incomplete Category)</relationshipLabel>
    <relationshipName>RFI_Items1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Description__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Description__c</fullName>
    <label>Onsite Remediation Description</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Onsite_Remediation_Required__c.field-meta.xml
<CustomField>
    <fullName>Onsite_Remediation_Required__c</fullName>
    <label>Onsite Remediation Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>No</fullName>
                <default>true</default>
                <label>No</label>
            </value>
            <value>
                <fullName>Yes</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/RAID__c.field-meta.xml
<CustomField>
    <fullName>RAID__c</fullName>
    <label>RAID</label>
    <referenceTo>RAID__c</referenceTo>
    <relationshipLabel>RFI Item</relationshipLabel>
    <relationshipName>RFI_Detail</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/RFI_Category__c.field-meta.xml
<CustomField>
    <fullName>RFI_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RFI Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipLabel>RFI Items (RFI Category)</relationshipLabel>
    <relationshipName>RFI_Items2</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/RFI_Detail_Description__c.field-meta.xml
<CustomField>
    <fullName>RFI_Detail_Description__c</fullName>
    <label>RFI Item Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/RFI_Item_Status__c.field-meta.xml
<CustomField>
    <fullName>RFI_Item_Status__c</fullName>
    <label>RFI Item Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drafting</fullName>
                <default>true</default>
                <label>Drafting</label>
            </value>
            <value>
                <fullName>Requested</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Needs Detail</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Canceled</fullName>
            </value>
            <value>
                <fullName>Cannot Complete</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/wrapperClassNew.cls
/**
 * @description       :
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             :
 * @last modified on  : 10-05-2020
 * @last modified by  : Justin Smith @cyberjus
 * Modifications Log
 * Ver   Date         Author                               Modification
 * 1.0   09-21-2020   ChangeMeIn@UserSettingsUnder.SFDoc   Initial Version
 **/
public with sharing class wrapperClassNew implements Comparable {
    @AuraEnabled
    public RFI_Categories__c lstRfiCat { get; set; }
    @AuraEnabled
    public RFI_Detail__c lstRfiDetails { get; set; }
    @AuraEnabled
    public String description { get; set; }
    @AuraEnabled
    public String selOption { get; set; }
    @AuraEnabled
    public List<String> onsitePicklist { get; set; }
    @AuraEnabled
    public String onsiteDescription { get; set; }
    @AuraEnabled
    public Boolean implementationBlock { get; set; }
    @AuraEnabled
    public String categoryType { get; set; }
    @AuraEnabled
    public Boolean filtered { get; set; }
    @AuraEnabled
    public Boolean selected { get; set; }
    @AuraEnabled
    public String status { get; set; }
  
    public wrapperClassNew() {
      lstRfiCat = new RFI_Categories__c();
      onsitePicklist = new List<String>();
      onsiteDescription = '';
      filtered = false;
      selected = false;
    }
  
    public Integer compareTo(Object compareTo) {
      wrapperClassNew compareToW = (wrapperClassNew) compareTo;
      if (selected && !compareToW.selected)
        return -1;
      if (!selected && compareToW.selected)
        return 1;
      if (lstRfiCat.Name < compareToW.lstRfiCat.Name)
        return -1;
      if (lstRfiCat.Name > compareToW.lstRfiCat.Name)
        return 1;
      return 0;
    }
  
    public RFI_Detail__c convertToRFIItem(RFI_Categories__c category, Id rfiId) {
      RFI_Detail__c rfiDetail = new RFI_Detail__c();
      if (category.RecordType.Name == 'Incorrect Information') {
        rfiDetail.Incorrect_Category__c = category.Id;
      } else if (category.RecordType.Name == 'Missing/Incomplete Information') {
        rfiDetail.Missing_Incomplete_Category__c = category.Id;
      }
      rfiDetail.RFI_Category__c = category.Id;
      rfiDetail.RAID__c = rfiId; //record Id
      rfiDetail.RFI_Detail_Description__c = this.description;
      if (this.status != null)
        rfiDetail.RFI_Item_Status__c = this.status;
      //rfiDetial.RFI_Item_Status__c = 'Submitted – Pending Customer Review';
      //rfiDetial.Account_Plant__c = rfiVariable.Account_Plant__c;
      rfiDetail.Category_Type__c = this.categoryType;
      //rfiDetial.Onsite_Remediation_Required__c = wrpCls.selOption;
      rfiDetail.Implementation_Blocked__c = this.implementationBlock;
      //if (wrpCls.selOption == 'Yes') {
      //  rfiDetial.Onsite_Remediation_Description__c = wrpCls.onsiteDescription;
      //}
      return rfiDetail;
    }
  }