unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Bulk_Import_Type__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Import_Type__c</fullName>
    <label>Bulk Import Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Base Asset Template Prompts</fullName>
                <default>true</default>
                <label>Single Base Asset Template Prompts</label>
            </value>
            <value>
                <fullName>Multiple Base Asset Template Prompts</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/G1BulkImportButtonHndlr.cls
public with sharing class G1BulkImportButtonHndlr {
    @AuraEnabled
    /*
     To check whether selected plant asset is new to asset build or only the G1 record exist ro the build started. 
     Based on which the relevant opration will be done.
     If the G1 record exsit, system allow user to download the asset builder prompt template
     If the no G1 record exsit, system prompt user to click save in G1 prompt and click export button
     If other prompt also exist, system prompt user to delete all the current asset build records and export      
    */
    public static String getG1RecordDetails(String plantAssetId){
         try {
             Integer noOfprompts = 0;
              List<Plant_Asset_Prompt_Detail__c> plantAssetPromptDetailLst = 
                  [SELECT id, Name,Prompt_Information__r.Name, Bulk_Import_Type__c FROM Plant_Asset_Prompt_Detail__c 
                  WHERE Account_Plant__c =:plantAssetId and Is_Deleted__c = False AND 
                  Prompt_Information__r.Name =: Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT];
 
             if(plantAssetPromptDetailLst.size() == 0){
                 return 'isNewPlant';
             }else if(plantAssetPromptDetailLst[0].Prompt_Information__r.Name == Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT && 
                         plantAssetPromptDetailLst[0].Bulk_Import_Type__c != Constants.Manual && 
                         plantAssetPromptDetailLst[0].Bulk_Import_Type__c != Constants.COMPLETED){
                 return 'enableBulkImportButton';
             }else if(plantAssetPromptDetailLst[0].Bulk_Import_Type__c == Constants.Manual || 
                         plantAssetPromptDetailLst[0].Bulk_Import_Type__c == Constants.COMPLETED){
                 return 'buildStarted'; 
             }
             
             return null;
         } catch (Exception exceptionDetails) {
             String errorMessage = 'Please Contact Administrator '+ exceptionDetails.getMessage();
             System.debug(' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber());
             throw new AuraHandledException(errorMessage);
          }
    }
 }