unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Drive_Id__c.field-meta.xml
<CustomField>
    <fullName>Drive_Id__c</fullName>
    <label>Drive Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Plant__r.Latitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Plant__r.Longitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <formula>TEXT(Plant__r.Renewable_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewable Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <formula>TEXT( Plant__r.Timezone__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Timezone</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Support</fullName>
            </value>
            <value>
                <fullName>Service Ticket</fullName>
            </value>
            <value>
                <fullName>Issue</fullName>
            </value>
            <value>
                <fullName>Feature Request</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <label>Latitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <label>Longitude</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <description>Used for Asset Builder</description>
    <label>Renewable Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Hybrid - Solar PV / BESS</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>BESS</fullName>
            </value>
            <value>
                <fullName>Hybrid - Fuel Cell / BESS</fullName>
            </value>
            <value>
                <fullName>Fuel Cell</fullName>
            </value>
            <value>
                <fullName>Biomass</fullName>
            </value>
            <value>
                <fullName>Not Applicable</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/fields/Timezone__c.field-meta.xml
<CustomField>
    <fullName>Timezone__c</fullName>
    <label>Timezone</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Morocco Standard Time</fullName>
            </value>
            <value>
                <fullName>Coordinated Universal Time</fullName>
            </value>
            <value>
                <fullName>GMT Standard Time</fullName>
            </value>
            <value>
                <fullName>Greenwich Standard Time</fullName>
            </value>
            <value>
                <fullName>W. Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Central Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Romance Standard Time</fullName>
            </value>
            <value>
                <fullName>Central European Standard Time</fullName>
            </value>
            <value>
                <fullName>W. Central Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>Namibia Standard Time</fullName>
            </value>
            <value>
                <fullName>Jordan Standard Time</fullName>
            </value>
            <value>
                <fullName>GTB Standard Time</fullName>
            </value>
            <value>
                <fullName>Middle East Standard Time</fullName>
            </value>
            <value>
                <fullName>Egypt Standard Time</fullName>
            </value>
            <value>
                <fullName>Syria Standard Time</fullName>
            </value>
            <value>
                <fullName>South Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>FLE Standard Time</fullName>
            </value>
            <value>
                <fullName>Turkey Standard Time</fullName>
            </value>
            <value>
                <fullName>Jerusalem Standard Time</fullName>
            </value>
            <value>
                <fullName>E. Europe Standard Time</fullName>
            </value>
            <value>
                <fullName>Arabic Standard Time</fullName>
            </value>
            <value>
                <fullName>Kaliningrad Standard Time</fullName>
            </value>
            <value>
                <fullName>Arab Standard Time</fullName>
            </value>
            <value>
                <fullName>E. Africa Standard Time</fullName>
            </value>
            <value>
                <fullName>Iran Standard Time</fullName>
            </value>
            <value>
                <fullName>Arabian Standard Time</fullName>
            </value>
            <value>
                <fullName>Azerbaijan Standard Time</fullName>
            </value>
            <value>
                <fullName>Russian Standard Time</fullName>
            </value>
            <value>
                <fullName>Mauritius Standard Time</fullName>
            </value>
            <value>
                <fullName>Georgian Standard Time</fullName>
            </value>
            <value>
                <fullName>India Standard Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RAID__c/RAID__c.object-meta.xml
<CustomObject>
    <description>This is created as part of REQ-2739 for cloud coach</description>
    <label>RAID</label>
    <nameField>
        <displayFormat>RAID-{0000}</displayFormat>
        <label>RAID ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>RAIDS</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RAID__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RAIDS</relationshipLabel>
    <relationshipName>RAIDS</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RAID__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>RAIDS</relationshipLabel>
    <relationshipName>RAIDS</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/RAID__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Current status of the RAID log</description>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Closed</fullName>
            </value>
            <value>
                <fullName>Ready</fullName>
            </value>
            <value>
                <fullName>Ready for Review</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>On Hold</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RAID__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>RAID type for categorization</description>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Development</fullName>
            </value>
            <value>
                <fullName>Documentation</fullName>
            </value>
            <value>
                <fullName>Project Management</fullName>
            </value>
            <value>
                <fullName>Question</fullName>
            </value>
            <value>
                <fullName>Scope</fullName>
            </value>
            <value>
                <fullName>Design</fullName>
            </value>
            <value>
                <fullName>Process</fullName>
            </value>
            <value>
                <fullName>Ownership</fullName>
            </value>
            <value>
                <fullName>Scheduling</fullName>
            </value>
            <value>
                <fullName>Resource</fullName>
            </value>
            <value>
                <fullName>Technology</fullName>
            </value>
            <value>
                <fullName>Performance</fullName>
            </value>
            <value>
                <fullName>Budget</fullName>
            </value>
            <value>
                <fullName>Quality</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/RAID__c/recordTypes/RFI.recordType-meta.xml
<RecordType>
    <fullName>RFI</fullName>
    <active>true</active>
    <label>RFI</label>
</RecordType>

unpackaged/main/default/objects/RFI_Detail__c/RFI_Detail__c.object-meta.xml
<CustomObject>
    <label>RFI Item</label>
    <nameField>
        <label>RFI Item</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>RFI Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/RFI_Detail__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>RFI Items</relationshipLabel>
    <relationshipName>RFI_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/RFI_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>RFI Items</relationshipLabel>
    <relationshipName>RFI_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/UpdaterfidetailTest.cls
/**
**/
@isTest
public class UpdaterfidetailTest {
      @testSetup static void  setup(){
         Product2 pr = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');
        insert pr;
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
          
        Contact c = TestDataFactory.createContact(accnt.id);
        insert c;
      
        system.debug('contact--->'+ c);
        
       Plant__c plant = new Plant__c();       
       plant.Renewable_Type__c = Constants.WIND;
       plant.Timezone__c = 'India Standard Time';
       plant.Latitude__c = '45.4543';
       plant.Longitude__c= '70.123';
       insert plant;
          
        Account_Plant__c palntAsset = new Account_Plant__c();
        palntAsset.plant__c = plant.id;       
        palntAsset.Project_Lifecycle_Status__c = 'Pending';        
        
        insert palntAsset;
        
        Account_Plant__c palntAsst = new Account_Plant__c();
        
        palntAsst.plant__c = plant.id;        
        palntAsst.Drive_Id__c = '123';        
        palntAsst.Account__c = accnt.Id;
        palntAsst.Assigned_Customer_Contact__c = c.Id;
        
        insert palntAsst;
          
        palntAsst.Project_Lifecycle_Status__c = 'Pending';
        
        Update palntAsst;
        
        RAID__c newrfi = new RAID__c();
        newrfi.Account_Plant__c = palntAsst.Id;
        newrfi.Priority__c= 'Low';
        newrfi.Status__c= 'In Progress';
        newrfi.Title__c = 'Test Controller';
        newrfi.Type__c = 'Process';
        insert newrfi;
        system.debug('--RFI RAID:-' +newrfi);
        
        RFI_Categories__c newRFICat = new RFI_Categories__c();
        newRFICat.Category_Classification__c = 'General';
        newRFICat.Name = 'Test missing';
        newRFICat.RecordTypeId = [SELECT id from RecordType where Name ='Missing/Incomplete Information'].Id;
        insert newRFICat;
        
        RFI_Categories__c newRFICat1 = new RFI_Categories__c();
        newRFICat1.Category_Classification__c = 'General';
        newRFICat1.Name = 'Test Incorrect';
        newRFICat1.RecordTypeId = [SELECT id from RecordType where Name ='Incorrect Information'].Id;
        insert newRFICat1;
        RFI_Categories__c newRFICat2 = new RFI_Categories__c();
        newRFICat2.Category_Classification__c = 'General';
        newRFICat2.Name = 'Test Incorrect 1';
        newRFICat2.RecordTypeId = [SELECT id from RecordType where Name ='Incorrect Information'].Id;
        insert newRFICat2;
          
        list<RFI_Detail__c> rfiitemlst = new list<RFI_Detail__c> ();  
		RFI_Detail__c newrfiItem = new RFI_Detail__c();
        newrfiItem.RFI_Item_Status__c = 'Requested';
        newrfiItem.RAID__c = newrfi.Id;
        newrfiItem.Missing_Incomplete_Category__c = newRFICat.id;
        newrfiItem.RFI_Category__c = newRFICat.id;
        newrfiItem.Implementation_Blocked__c = false;
        rfiitemlst.add(newrfiItem);
          
        RFI_Detail__c newrfiItem1 = new RFI_Detail__c();
        newrfiItem1.RFI_Item_Status__c = 'Needs Detail';
        newrfiItem1.RAID__c = newrfi.Id;
        newrfiItem1.Missing_Incomplete_Category__c = newRFICat1.id;
        newrfiItem1.RFI_Category__c = newRFICat1.id;
        newrfiItem1.Implementation_Blocked__c = false;
        rfiitemlst.add(newrfiItem1);
        RFI_Detail__c newrfiItem2 = new RFI_Detail__c();
        newrfiItem2.RFI_Item_Status__c = 'Requested';
        newrfiItem2.RAID__c = newrfi.Id;
        newrfiItem2.Missing_Incomplete_Category__c = newRFICat2.id;
        newrfiItem2.RFI_Category__c = newRFICat2.id;
        newrfiItem2.Implementation_Blocked__c = false;
        rfiitemlst.add(newrfiItem2);  
        insert rfiitemlst;  
    }
    @isTest static void testMethod2() {
        list<RFI_Detail__c> rfiitemlstupdate = new list<RFI_Detail__c> ();
        RFI_Detail__c updaterfiItem2 = [SELECT Id FROM RFI_Detail__c WHERE Name='Test Incorrect 1' LIMIT 1];
        updaterfiItem2.RFI_Item_Status__c = 'Canceled';
        updaterfiItem2.Cancel_Cannot_Complete_Description__c = 'test';
		updaterfiItem2.Implementation_Blocked__c = true;
        rfiitemlstupdate.add(updaterfiItem2);
        RFI_Detail__c updaterfiItem = [SELECT Id FROM RFI_Detail__c WHERE Name='Test Incorrect' LIMIT 1];
        updaterfiItem.RFI_Item_Status__c = 'Requested';
        updaterfiItem.Implementation_Blocked__c = false;
        rfiitemlstupdate.add(updaterfiItem);
        RFI_Detail__c updaterfiItem1 = [SELECT Id FROM RFI_Detail__c WHERE Name='Test missing' LIMIT 1];
        updaterfiItem1.RFI_Item_Status__c = 'In Progress';
        updaterfiItem1.Implementation_Blocked__c = false;
        rfiitemlstupdate.add(updaterfiItem1);
        Test.startTest();
        update rfiitemlstupdate;
        Test.stopTest();
    }
}