unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Master__c/Attribute_Master__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute Master</label>
    <nameField>
        <label>Attribute Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Master__c/fields/Picklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist Master</label>
    <referenceTo>Picklist_Master__c</referenceTo>
    <relationshipLabel>Attribute Masters</relationshipLabel>
    <relationshipName>Attribute_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Master__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attribute Masters</relationshipLabel>
    <relationshipName>Attribute_Masters</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Requirement__c/Attribute_Requirement__c.object-meta.xml
<CustomObject>
    <description>Stores the base asset&#39;s attribute requirement information to be fetched in prompt screens</description>
    <label>Attribute Requirement</label>
    <nameField>
        <label>Attribute Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Requirement__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attribute Requirements</relationshipLabel>
    <relationshipName>Attribute_Requirements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Base Asset Templates</relationshipLabel>
    <relationshipName>Base_Asset_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Attribute__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Attributes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/recordTypes/Core_Attribute.recordType-meta.xml
<RecordType>
    <fullName>Core_Attribute</fullName>
    <active>true</active>
    <label>Core Attribute</label>
</RecordType>

unpackaged/main/default/objects/Evaluation__c/Evaluation__c.object-meta.xml
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Evaluation__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Evaluations</relationshipLabel>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Evaluations</relationshipLabel>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Metric_Definition__c/Metric_Definition__c.object-meta.xml
<CustomObject>
    <label>Metric Definition</label>
    <nameField>
        <label>Metric Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Metric Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Metric_Definition__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Metric Definitions</relationshipLabel>
    <relationshipName>Metric_Definitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Metric_Definition__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Metric Definitions</relationshipLabel>
    <relationshipName>Metric_Definitions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Metric_Definition__c/recordTypes/Constants.recordType-meta.xml
<RecordType>
    <fullName>Constants</fullName>
    <active>true</active>
    <description>Constants for Evaluation</description>
    <label>Constants</label>
</RecordType>

unpackaged/main/default/objects/Metric_Definition__c/recordTypes/Definition.recordType-meta.xml
<RecordType>
    <fullName>Definition</fullName>
    <active>true</active>
    <description>Definition for Metric and Evaluation</description>
    <label>Definition</label>
</RecordType>

unpackaged/main/default/objects/Metric_Value__c/Metric_Value__c.object-meta.xml
<CustomObject>
    <label>Metric Value</label>
    <nameField>
        <displayFormat>MetricValue-{0000}</displayFormat>
        <label>Metric Values Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Metric Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Metric_Value__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Metric Values</relationshipLabel>
    <relationshipName>Metric_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Picklist_Detail__c/Picklist_Detail__c.object-meta.xml
<CustomObject>
    <description>This object has all picklist values related to its picklist master E.g Time Zone is the picklist master and its time zone literals (values) like IST, PST, EST will be here in this object</description>
    <label>Picklist Detail</label>
    <nameField>
        <label>Picklist Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Picklist_Detail__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Picklist Details</relationshipLabel>
    <relationshipName>Picklist_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Picklist_Master__c/Picklist_Master__c.object-meta.xml
<CustomObject>
    <description>This object will have the picklist master details. E.g Time Zone. The time zone literals will be there in Picklist Details object</description>
    <label>Picklist Master</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Picklist_Master__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Picklist Master</relationshipLabel>
    <relationshipName>Picklist_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/EvaluationValueDataCreationTest.cls
/**
**/
@isTest
public with sharing class EvaluationValueDataCreationTest {
    @testSetup
    public static void testDataSetup() {
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;

        Account_Plant__c newPlantAsset = TestDataFactory.createPlantAsset(Constants.SOLAR, 'Drive', '7777.77.777', newTemVersion.Id);
        insert newPlantAsset;

        Base_Asset_Template__c p1PromptBaseAsset = TestDataFactory.createBaseAssetTemplate(Constants.BASE_PV_PLANT, newTemVersion.Id);
        insert p1PromptBaseAsset;
		
        Prompt_Information__c g1PromptInfo = new Prompt_Information__c();
        g1PromptInfo.Name = Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT  ;
        g1PromptInfo.TEM_Version__c = newTemVersion.Id;
        insert g1PromptInfo;

        Prompt_Information__c p1PromptInfo = TestDataFactory.createPromptInformation(Constants.P1_PLANT_INFO_PROMPT_SOLAR,
                                                p1PromptBaseAsset.Id, newTemVersion.Id);
        insert p1PromptInfo;

        Picklist_Master__c newPicklistMaster = TestDataFactory.createPicklistMaster(Constants.FLAT_HIERARCHY, newTemVersion.Id);
        insert newPicklistMaster;
        
        Picklist_Detail__c picklistDetailValue = TestDataFactory.createPicklistValue(newPicklistMaster.Id, newTemVersion.Id);
        insert picklistDetailValue;

        Id coreAttrRTId = Utils.getRecordTypeInfo('Core_Attribute__c','Core_Attribute').getRecordTypeId();

        List<Core_Attribute__c> coreAttrLst  = new List<Core_Attribute__c> ();
        list<String>datatypeLst = new list<String>{'Number','Number','Decimal','Decimal','Text','Text','Picklist','Picklist',
        'Date','Date','Checkbox','Checkbox'};
        list<String>coreAttrNameLst = new list<String>{'No1','No2','Decimal1','Decimal2','Text1','Text2','Picklist1','Picklist2'
        ,'Date1','Date2','Checkbox1','Checkbox2'};
        for(integer i = 0; i < 12; i++){
            Core_Attribute__c coreAttr = TestDataFactory.createCoreAttribute(coreAttrNameLst[i],
                                                                                'Metadata',
                                                                                datatypeLst[i],
                                                                                coreAttrRTId,
                                                                                (datatypeLst[i] == 'Picklist')? newPicklistMaster.Id : null,
                                                                                p1PromptBaseAsset.Id, newTemVersion.Id);                                                                 
            coreAttrLst.add(coreAttr);
        }
        insert coreAttrLst;
        List<Attribute_Requirement__c> attrReqLst  = new List<Attribute_Requirement__c> ();
        for(integer i = 0; i < 1; i++){
            Attribute_Requirement__c attrReq = TestDataFactory.createAttributeRequirement('Drive', 'Yes', coreAttrLst[i].Id, newTemVersion.Id);
            attrReqLst.add(attrReq);
        }

        Id metricDefinition = Utils.getRecordTypeInfo('Metric_Definition__c','Definition').getRecordTypeId();
        Id metricConst = Utils.getRecordTypeInfo('Metric_Definition__c','Constants').getRecordTypeId();

        Plant_Asset_Prompt_Detail__c g1PlantAssetPromptDetail = new Plant_Asset_Prompt_Detail__c();
        g1PlantAssetPromptDetail.Name = 'Test Plant' +'-'+ p1PromptInfo.Name;
        g1PlantAssetPromptDetail.Account_Plant__c = newPlantAsset.Id;
        g1PlantAssetPromptDetail.Prompt_Information__c = g1PromptInfo.Id;
        insert g1PlantAssetPromptDetail;

        Plant_Asset_Prompt_Detail__c p1PlantAssetPromptDetail = new Plant_Asset_Prompt_Detail__c();
        p1PlantAssetPromptDetail.Name = 'Test Plant' +'-'+ p1PromptInfo.Name;
        p1PlantAssetPromptDetail.Account_Plant__c = newPlantAsset.Id;
        p1PlantAssetPromptDetail.Prompt_Information__c = p1PromptInfo.Id;
        p1PlantAssetPromptDetail.Base_Asset__c = p1PromptBaseAsset.Id;
        insert p1PlantAssetPromptDetail;

        String promptSpecificInfoJSON = JSON.serialize('{"No of Blocks":"2","Flat Hierarchy":"No"');
        String coreAttributeInfoJSON = JSON.serialize('{"AC_CAPACITY":""}');

        Site_Metadata__c p1SiteMetaData = new Site_Metadata__c(); 
        p1SiteMetaData.Name = Constants.P1_PLANT_INFO_PROMPT_SOLAR;
        p1SiteMetaData.Prompt_Specific_Info__c = '{"No of Blocks":"2","Flat Hierarchy":"No"';
        p1SiteMetaData.Attribute_Info__c = '{"AC_CAPACITY":""}';
        p1SiteMetaData.Account_Plant__c= newPlantAsset.id;
        p1SiteMetaData.Base_Asset_Template__c = p1PromptBaseAsset.id;
        p1SiteMetaData.Plant_Asset_Prompt_Detail__c = p1PlantAssetPromptDetail.Id;
        insert p1SiteMetaData;
        
        List<String> metricDefStr = new List<String>();
        String str= 'VALUES';
        List<Metric_Definition__c> metricDefLst = new List<Metric_Definition__c>();
        for(Core_Attribute__c coreAttrIns : coreAttrLst){
                Metric_Definition__c metricDef = TestDataFactory.createMetricDef(String.valueOf(p1PromptBaseAsset.Id), String.valueOf(coreAttrIns.Id), str, '', '', String.valueOf(newTemVersion.Id), metricDefinition);
                metricDefLst.add(metricDef);
        }
        insert metricDefLst;
        
        List<Metric_Value__c> metricValueLst = new List<Metric_Value__c>();
        for(Metric_Definition__c metricDefIn : [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: newPlantAsset.TEM_Version__c]){
                
                Metric_Value__c metricValue = TestDataFactory.createMetricValue(String.valueOf(metricDefIn.Id), String.valueOf(newPlantAsset.Id), '', metricDefIn.Attribute__r.Attribute_Master__r.Data_Type__c);  
                metricValueLst.add(metricValue);
        }
        insert metricValueLst;

        Metric_Definition__c metricDefCnst = TestDataFactory.createMetricDef('', '', 'CONSTANT', 'NUMBER', '300', String.valueOf(newTemVersion.Id), metricConst);
        insert metricDefCnst;
    }
    
    public static testMethod void testMethod1(){
        //Scenario 1 -> When Attribute data type as Number in metric definition, which used for Component 1 and Component 2 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id),'',
                                                               '=', '', 'Pass', '', '');
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id),'',
                                                               '<>', '', 'Pass', '', '');
        evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id),'',
                                                               '>', '', 'Pass', '', '');
        evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id),'',
                                                               '<', '', 'Pass', '', '');
        evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id),'',
                                                               '>=', '', 'Pass', '', '');
        evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id),'',
                                                               '<=', '', 'Pass', '', '');
        evalLst.add(eval6);
       
        
        insert evalLst;
        
       EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    } 
    
     public static testMethod void testMethod2(){
        //Scenario 2 -> When Attribute data type as Number in metric definition, which used for Component 1, Component 2 and Component 3 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
         
         
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id), String.valueOf(metricDefCalLst[1].Id),
                                                               '=', '<=', '{0}/{1}', String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id));
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id), String.valueOf(metricDefCalLst[1].Id),
                                                               '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id));
		evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id), String.valueOf(metricDefCalLst[1].Id),
                                                               '>', '<', '{0}/{1}', String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id));
		evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id), String.valueOf(metricDefCalLst[1].Id),
                                                               '<', '>', '{0}/{1}', String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id));
		evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id), String.valueOf(metricDefCalLst[1].Id),
                                                               '>=', '<>', '{0}/{1}', String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id));
		evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id), String.valueOf(metricDefCalLst[1].Id),
                                                               '<=', '=', '{0}/{1}', String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefCalLst[1].Id));
		evalLst.add(eval6);
    insert evalLst;

    EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    public static testMethod void testMethod3(){
        //Scenario 3 -> When Attribute data type as Decimal in metric definition, which used for Component 1 and Component 2 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id),'',
                                                               '=', '', 'Pass', '', '');
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id),'',
                                                               '<>', '', 'Pass', '', '');
        evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id),'',
                                                               '>', '', 'Pass', '', '');
        evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id),'',
                                                               '<', '', 'Pass', '', '');
        evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id),'',
                                                               '>=', '', 'Pass', '', '');
        evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id),'',
                                                               '<=', '', 'Pass', '', '');
        evalLst.add(eval6);
        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    
     public static testMethod void testMethod4(){
        //Scenario 4 -> When Attribute data type as Decimal in metric definition, which used for Component 1, Component 2 and Component 3 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id), String.valueOf(metricDefCalLst[3].Id),
                                                               '=', '<=', '{0}/{1}', String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[4].Id));
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id), String.valueOf(metricDefCalLst[3].Id),
                                                               '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[4].Id));
		evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id), String.valueOf(metricDefCalLst[3].Id),
                                                               '>', '<', '{0}/{1}', String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[4].Id));
		evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id), String.valueOf(metricDefCalLst[3].Id),
                                                               '<', '>', '{0}/{1}', String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[4].Id));
		evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id), String.valueOf(metricDefCalLst[3].Id),
                                                               '>=', '<>', '{0}/{1}', String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[4].Id));
		evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id), String.valueOf(metricDefCalLst[3].Id),
                                                               '<=', '=', '{0}/{1}', String.valueOf(metricDefCalLst[2].Id), String.valueOf(metricDefCalLst[3].Id));
		evalLst.add(eval6);
    insert evalLst;
    EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    public static testMethod void testMethod5(){
        //Scenario 5 -> When Attribute data type as Text in metric definition, which used for Component 1 and Component 2 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[4].Id), String.valueOf(metricDefCalLst[5].Id),'',
                                                               '=', '', 'Pass', '', '');
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[4].Id), String.valueOf(metricDefCalLst[5].Id),'',
                                                               '<>', '', 'Pass', '', '');
        evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[4].Id), String.valueOf(metricDefCalLst[5].Id),'',
                                                               '>', '', 'Pass', '', '');
        evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[4].Id), String.valueOf(metricDefCalLst[5].Id),'',
                                                               '<', '', 'Pass', '', '');
        evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[4].Id), String.valueOf(metricDefCalLst[5].Id),'',
                                                               '>=', '', 'Pass', '', '');
        evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[4].Id), String.valueOf(metricDefCalLst[5].Id),'',
                                                               '<=', '', 'Pass', '', '');
        evalLst.add(eval6);
        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    
     public static testMethod void testMethod6(){
        //Scenario 6 -> When Attribute data type as Text in metric definition, which used for Component 1, Component 2 and Component 3 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[6].Id), String.valueOf(metricDefCalLst[7].Id), String.valueOf(metricDefCalLst[6].Id),
                                                               '=', '<=', '{0}/{1}', String.valueOf(metricDefCalLst[5].Id), String.valueOf(metricDefCalLst[6].Id));
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[6].Id), String.valueOf(metricDefCalLst[7].Id), String.valueOf(metricDefCalLst[6].Id),
                                                               '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[5].Id), String.valueOf(metricDefCalLst[6].Id));
		evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[6].Id), String.valueOf(metricDefCalLst[7].Id), String.valueOf(metricDefCalLst[6].Id),
                                                               '>', '<', '{0}/{1}', String.valueOf(metricDefCalLst[5].Id), String.valueOf(metricDefCalLst[6].Id));
		evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[6].Id), String.valueOf(metricDefCalLst[7].Id), String.valueOf(metricDefCalLst[6].Id),
                                                               '<', '>', '{0}/{1}', String.valueOf(metricDefCalLst[5].Id), String.valueOf(metricDefCalLst[6].Id));
		evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[6].Id), String.valueOf(metricDefCalLst[7].Id), String.valueOf(metricDefCalLst[6].Id),
                                                               '>=', '<>', '{0}/{1}', String.valueOf(metricDefCalLst[5].Id), String.valueOf(metricDefCalLst[6].Id));
		evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[6].Id), String.valueOf(metricDefCalLst[7].Id), String.valueOf(metricDefCalLst[6].Id),
                                                               '<=', '=', '{0}/{1}', String.valueOf(metricDefCalLst[5].Id), String.valueOf(metricDefCalLst[6].Id));
		evalLst.add(eval6);

        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    public static testMethod void testMethod7(){
        //Scenario 7 -> When Attribute data type as Picklist in metric definition, which used for Component 1 and Component 2 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id),'',
                                                               '=', '', 'Pass', '', '');
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id),'',
                                                               '<>', '', 'Pass', '', '');
        evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id),'',
                                                               '>', '', 'Pass', '', '');
        evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id),'',
                                                               '<', '', 'Pass', '', '');
        evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id),'',
                                                               '>=', '', 'Pass', '', '');
        evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id),'',
                                                               '<=', '', 'Pass', '', '');
        evalLst.add(eval6);
        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    
     public static testMethod void testMethod8(){
        //Scenario 8 -> When Attribute data type as picklist in metric definition which used for Component 1, and When Attribute data type as date in metric definition which used for Component 2 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id), String.valueOf(metricDefCalLst[9].Id),
                                                               '=', '<=', '{0}/{1}', String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id));
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id), String.valueOf(metricDefCalLst[9].Id),
                                                               '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id));
		evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id), String.valueOf(metricDefCalLst[9].Id),
                                                               '>', '<', '{0}/{1}', String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id));
		evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id), String.valueOf(metricDefCalLst[9].Id),
                                                               '<', '>', '{0}/{1}', String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id));
		evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id), String.valueOf(metricDefCalLst[9].Id),
                                                               '>=', '<>', '{0}/{1}', String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id));
		evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id), String.valueOf(metricDefCalLst[9].Id),
                                                               '<=', '=', '{0}/{1}', String.valueOf(metricDefCalLst[9].Id), String.valueOf(metricDefCalLst[8].Id));
		evalLst.add(eval6);
        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    public static testMethod void testMethod9(){
        //Scenario 9 -> When Attribute data type as Date in metric definition, which used for Component 1 and Component 2 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id),'',
                                                               '=', '', 'Pass', '', '');
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id),'',
                                                               '<>', '', 'Pass', '', '');
        evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id),'',
                                                               '>', '', 'Pass', '', '');
        evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id),'',
                                                               '<', '', 'Pass', '', '');
        evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id),'',
                                                               '>=', '', 'Pass', '', '');
        evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id),'',
                                                               '<=', '', 'Pass', '', '');
        evalLst.add(eval6);
        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    
    public static testMethod void testMethod10(){
        //Scenario 10 -> When Attribute data type as Date in metric definition, which used for Component 1, Component 2 and Component 3 field in Evaluation
        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];
        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name FROM Metric_Definition__c 
            WHERE TEM_Version__c =: plantAsset.TEM_Version__c];

        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id), String.valueOf(metricDefCalLst[11].Id),
                                                               '=', '<=', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id), String.valueOf(metricDefCalLst[11].Id),
                                                               '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
		evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.03', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id), String.valueOf(metricDefCalLst[11].Id),
                                                               '>', '<', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
		evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.04', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id), String.valueOf(metricDefCalLst[11].Id),
                                                               '<', '>', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
		evalLst.add(eval4);
        Evaluation__c eval5 = TestDataFactory.createEvaluation('TEST.0001.05', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id), String.valueOf(metricDefCalLst[11].Id),
                                                               '>=', '<>', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
		evalLst.add(eval5);
        Evaluation__c eval6 = TestDataFactory.createEvaluation('TEST.0001.06', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id), String.valueOf(metricDefCalLst[11].Id),
                                                               '<=', '=', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
		evalLst.add(eval6);
    insert evalLst;
    EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
    
    public static testMethod void testMethod11(){
        //Scenario 11 -> When Component1 as metric definition and component 2 as metric constant
        Id metricDefinition = Utils.getRecordTypeInfo('Metric_Definition__c','Definition').getRecordTypeId();
        Id metricConst = Utils.getRecordTypeInfo('Metric_Definition__c','Constants').getRecordTypeId();

        Account_Plant__c plantAsset = [SELECT Id, Name, TEM_Version__c, Renewable_Type__c FROM Account_Plant__c WHERE Drive_Id__c  = '7777.77.777' LIMIT 1];

        List<Metric_Definition__c> metricDefCalLst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name,RecordTypeId FROM Metric_Definition__c 
                WHERE TEM_Version__c =: plantAsset.TEM_Version__c AND RecordTypeId=:metricDefinition];
        Metric_Definition__c metricDefConst = [SELECT Attribute__c, Attribute__r.Attribute_Master__r.Data_Type__c, Base_Asset_Template__c,Description__c,
                Id,IsDeleted,Modifer_1__c,Modifer_2_Value__c,Modifer_2__c,Name,RecordTypeId FROM Metric_Definition__c 
                WHERE TEM_Version__c =: plantAsset.TEM_Version__c AND RecordTypeId=:metricConst LIMIT 1];
        List<Evaluation__c> evalLst = new List<Evaluation__c>();
        Evaluation__c eval1 = TestDataFactory.createEvaluation('TEST.0001.01', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[0].Id), String.valueOf(metricDefConst.Id),'',
                                                               '=', '', 'Pass', '', '');
        evalLst.add(eval1);
        Evaluation__c eval2 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                               String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefConst.Id), String.valueOf(metricDefConst.Id),
                                                               '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
        evalLst.add(eval2);
        Evaluation__c eval3 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Plant','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                            String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefConst.Id), String.valueOf(metricDefConst.Id),
                                                            '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
        evalLst.add(eval3);
        Evaluation__c eval4 = TestDataFactory.createEvaluation('TEST.0001.02', 'Data Capability', 'Drive', 'Solar - PV', 'Feature','', '', String.valueOf(plantAsset.TEM_Version__c),
                                                            String.valueOf(metricDefConst.Id), String.valueOf(metricDefConst.Id), String.valueOf(metricDefConst.Id),

                                                            '<>', '>=', '{0}/{1}', String.valueOf(metricDefCalLst[11].Id), String.valueOf(metricDefCalLst[10].Id));
        evalLst.add(eval4);
        insert evalLst;
        EvaluationValueDataCreation.mapFormationForEvaluationValue(plantAsset.Id);
    }
}