unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Evaluation__c/Evaluation__c.object-meta.xml
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Evaluation__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Capability</fullName>
            </value>
            <value>
                <fullName>Feature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Evaluation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Notes__c</fullName>
    <label>Evaluation Notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Group_1__c.field-meta.xml
<CustomField>
    <fullName>Group_1__c</fullName>
    <label>Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Group_for_Evaluation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Group_2__c.field-meta.xml
<CustomField>
    <fullName>Group_2__c</fullName>
    <label>Group 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Group_for_Evaluation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Drive Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Evaluations</relationshipLabel>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Feature</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Weather Station</fullName>
            </value>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/Evaluation_Value__c.object-meta.xml
<CustomObject>
    <label>Evaluation Value</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Evaluation Values</relationshipLabel>
    <relationshipName>Evaluation_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation</label>
    <referenceTo>Evaluation__c</referenceTo>
    <relationshipLabel>Evaluation Values</relationshipLabel>
    <relationshipName>Evaluation_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Logic_Result__c.field-meta.xml
<CustomField>
    <fullName>Logic_Result__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logic Result</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Show_In_Report__c.field-meta.xml
<CustomField>
    <fullName>Show_In_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show In Report</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Test_Id__c.field-meta.xml
<CustomField>
    <fullName>Test_Id__c</fullName>
    <label>Test Id</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Previous_Plant_Asset_Prompt__c.field-meta.xml
<CustomField>
    <fullName>Previous_Plant_Asset_Prompt__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Previous Plant Asset Prompt</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details (Previous Plant Asset Prompt)</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details1</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Prompt Name Alias</description>
    <label>Alias</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Prompt_Id__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Id__c</fullName>
    <label>Prompt Id</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/globalValueSets/Group_for_Evaluation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ambient Temperature</fullName>
    </customValue>
    <customValue>
        <fullName>Anemometer</fullName>
    </customValue>
    <customValue>
        <fullName>Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Combiner Heatmap</fullName>
    </customValue>
    <customValue>
        <fullName>Common</fullName>
    </customValue>
    <customValue>
        <fullName>Common - Energy Loss Allocation - Energy Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Dashboard</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Loss Allocation</fullName>
    </customValue>
    <customValue>
        <fullName>Event Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Expected/Predicted Production</fullName>
    </customValue>
    <customValue>
        <fullName>Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Inverter Configuration S</fullName>
    </customValue>
    <customValue>
        <fullName>IRRADIANCE CLEAR_SKY</fullName>
    </customValue>
    <customValue>
        <fullName>Level 0</fullName>
    </customValue>
    <customValue>
        <fullName>Level 0 (optional)</fullName>
    </customValue>
    <customValue>
        <fullName>Level 2</fullName>
    </customValue>
    <customValue>
        <fullName>Meter</fullName>
    </customValue>
    <customValue>
        <fullName>Met mast Configuration W</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Metadata - Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Metadata - Plant</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Metadata - Subarray</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Subarray Metadata - Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Modelling</fullName>
    </customValue>
    <customValue>
        <fullName>Module Temperature</fullName>
    </customValue>
    <customValue>
        <fullName>Nominal Power</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Other Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>Plant Configuration S</fullName>
    </customValue>
    <customValue>
        <fullName>Plant configuration W</fullName>
    </customValue>
    <customValue>
        <fullName>POA Pyranometer</fullName>
    </customValue>
    <description>Picklist values for Group fields in Evaluation Object.</description>
    <masterLabel>Group for Evaluation</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CapabilityReportController.cls
public with sharing class CapabilityReportController {
    
    @AuraEnabled
    public static String getEvaluationValues(String plantAssetId, String categoryName, String subCategory) {
        List<String> pfServiceProducts = Utils.getAttrReqSysNamesFrmG1(plantAssetId);
        String evaluationValueString = '';
        list<Evaluation_Value__c> evaluationValueLst = [SELECT Id, Test_Id__c, Evaluation__r.Category__c, Result__c,
            Evaluation__r.Alias__c, Evaluation__r.Evaluation_Notes__c, Account_Plant__c, Evaluation__r.Name, Evaluation__r.Group_2__c,
            Evaluation__r.Group_1__c, Evaluation__r.Result__c, Evaluation__r.Sub_Category__c, Evaluation__r.Prompt_Information__r.Id, Evaluation__r.Prompt_Information__r.Prompt_Id__c FROM Evaluation_Value__c WHERE
            Logic_Result__c = true AND Evaluation__r.Category__c =: categoryName AND 
            Account_Plant__c =: plantAssetId AND Evaluation__r.Group_1__c != null AND Evaluation__r.Alias__c != null AND
            Evaluation__r.Sub_Category__c =: subCategory AND Show_In_Report__c = true AND Evaluation__r.Products__c IN :pfServiceProducts ORDER BY Evaluation__r.Group_1__c ASC, Test_Id__c ASC];

        if(evaluationValueLst.size()>0){
            Map<String,Object> evaluationValueMap = CapabilityReportController.getEvaluationValueMap(evaluationValueLst);
            evaluationValueString = JSON.serialize(evaluationValueMap);
            return evaluationValueString;
        }else{
            return evaluationValueString;
        }
    }
    @AuraEnabled
    public static Map<String,Object> getEvaluationValueMap(list<Evaluation_Value__c> evaluationValueLst){
        Map<String,Object> evaluationValueMap = new Map<String,Object>();
        evaluationValueMap.put('evaluationValue',evaluationValueLst);
        Map<String,String> promptIdToPreviousPlantAssetDetail = new Map<String,String>();
        Map<String,String> promptToPromptId = new Map<String,String>();
        
        List<Id> promptInfoIds = new List<Id>();
        for( Evaluation_Value__c evaluationValue : evaluationValueLst){
            if(evaluationValue.Evaluation__r.Prompt_Information__r.Id != NULL && evaluationValue.Evaluation__r.Prompt_Information__r.Prompt_Id__c !=NULL) {
            promptToPromptId.put(evaluationValue.Evaluation__r.Prompt_Information__r.Id, evaluationValue.Evaluation__r.Prompt_Information__r.Prompt_Id__c );
            promptInfoIds.add(evaluationValue.Evaluation__r.Prompt_Information__r.Id);
            }
        }
        
        evaluationValueMap.put('promptToPromptId',promptToPromptId);
        List<Plant_Asset_Prompt_Detail__c> plantAssetPromptDetails = [SELECT Id,Previous_Plant_Asset_Prompt__c,Prompt_Information__c from Plant_Asset_Prompt_Detail__c where Prompt_Information__c IN: promptInfoIds and is_Deleted__c= FALSE];
        for(Plant_Asset_Prompt_Detail__c plantAssetPromptDetail :plantAssetPromptDEtails){
            if(plantAssetPromptDetail.Prompt_Information__c != NULL && plantAssetPromptDetail.Previous_Plant_Asset_Prompt__c  != NULL){
            promptIdToPreviousPlantAssetDetail.put(plantAssetPromptDetail.Prompt_Information__c,plantAssetPromptDetail.Previous_Plant_Asset_Prompt__c );
            }
        }
       evaluationValueMap.put('promptIdToPreviousPlantAssetDetail',promptIdToPreviousPlantAssetDetail);
       return evaluationValueMap;
    }

    @AuraEnabled
    public static String getallEvaluationValues(String plantAssetId){
        List<String> pfServiceProducts = Utils.getAttrReqSysNamesFrmG1(plantAssetId);
        String evaluationValueString = '';
        list<Evaluation_Value__c> evaluationValueLst = [SELECT Id, Test_Id__c, Evaluation__r.Category__c, Result__c,
        Account_Plant__c, Evaluation__r.Name, Evaluation__r.Group_1__c, 
            Evaluation__r.Result__c, Evaluation__r.Sub_Category__c, Evaluation__r.Prompt_Information__r.Id, Evaluation__r.Prompt_Information__r.Prompt_Id__c FROM Evaluation_Value__c WHERE
            Logic_Result__c = true AND Account_Plant__c =: plantAssetId AND Evaluation__r.Sub_Category__c != null
            AND Evaluation__r.Category__c != null AND Show_In_Report__c = true AND Evaluation__r.Group_1__c != null AND Evaluation__r.Products__c IN :pfServiceProducts];
        if(evaluationValueLst.size()>0){
            Map<String,Object> evaluationValueMap = CapabilityReportController.getEvaluationValueMap(evaluationValueLst);
            evaluationValueString = JSON.serialize(evaluationValueMap);
            return evaluationValueString;
        }else{
            return evaluationValueString;
        }
    }

    @AuraEnabled
    public static String getallEvaluation(){ 
        String evaluationString = NULL;
        Map<String,Set<String>> evaluationMapLsts = new Map<String,Set<String>>();
        for(Evaluation__c evaluationRecord : [SELECT Id, Category__c, Sub_Category__c 
                            FROM Evaluation__c WHERE
                            Category__c != null AND Sub_Category__c != null]){
            String CategoryName = evaluationRecord.Category__c;
            if (!evaluationMapLsts.containsKey(CategoryName)){
                evaluationMapLsts.put(CategoryName, new Set<String>());
            }
            evaluationMapLsts.get(CategoryName).add(evaluationRecord.Sub_Category__c);
        }
        if(evaluationMapLsts.size()>0){
            Map<String,Object> evaluationMap = new Map<String,Object>();
            evaluationMap.put('evaluation',evaluationMapLsts);
            evaluationString = JSON.serialize(evaluationMap);
            return evaluationString;
        }else{
            return evaluationString;
        }
    }
}