unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Plant__c</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
                <default>true</default>
                <label>Active</label>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/MWp__c.field-meta.xml
<CustomField>
    <fullName>MWp__c</fullName>
    <formula>CASE(Asset_Class__c,
&quot;Solar&quot;,
	IF(ISBLANK( Megawatt_DC__c ), DC_Capacity_Quoted__c , Megawatt_DC__c),
&quot;Wind&quot;,
	IF(ISBLANK( Megawatt_AC__c ), AC_Capacity_Quoted__c , Megawatt_AC__c),
&quot;Hydro&quot;,
	IF(ISBLANK( Megawatt_AC__c ), AC_Capacity_Quoted__c , Megawatt_AC__c),
&quot;Storage&quot;,
	IF(ISBLANK( Megawatt_DC__c ), DC_Capacity_Quoted__c , Megawatt_DC__c),
&quot;Other Renewable&quot;,
	IF(ISBLANK( Megawatt_AC__c ), AC_Capacity_Quoted__c , Megawatt_AC__c),
NULL)</formula>
    <label>MWp</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Addl_Discount_Percent__c.field-meta.xml
<CustomField>
    <fullName>Addl_Discount_Percent__c</fullName>
    <description>This is the additional discount percentage entered by the User at the Quote line level</description>
    <inlineHelpText>This is the additional discount percentage entered by the User at the Quote line level</inlineHelpText>
    <label>Addl Discount Percent</label>
    <precision>6</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Contracted_MW_Unit_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Contracted_MW_Unit_List_Price__c</fullName>
    <label>Contracted MW Unit List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/List_Unit_Price__c.field-meta.xml
<CustomField>
    <fullName>List_Unit_Price__c</fullName>
    <label>List Unit Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/MWp_Quantity__c.field-meta.xml
<CustomField>
    <fullName>MWp_Quantity__c</fullName>
    <label>MW Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Order__c.field-meta.xml
<CustomField>
    <fullName>Order__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Order</label>
    <referenceTo>Order</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant_Product__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Plant Product</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Quote__c.field-meta.xml
<CustomField>
    <fullName>Quote__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Quote_Line__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Quote Line</label>
    <referenceTo>SBQQ__QuoteLine__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Quote_Line_Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quote_Line_Quantity__c</fullName>
    <description>This is the field where the User will enter the Quantity - which in turn will add to the aggregate Quantity on the Quote line. e.g. for a Product with Unit of Measure as Turbines (WTG), this filed will have the number of Turbines and the MWp_Quantity__c (which is going to be renamed to MW_Quantity__c later) will have the MW for the WTG plant</description>
    <inlineHelpText>This is the field where the User will enter the Quantity - which in turn will add to the aggregate Quantity on the Quote line. e.g. for a Product with Unit of Measure as Turbines (WTG), this filed will have the number of Turbines and the MWp_Quantity__c (which is going to be renamed to MW_Quantity__c later) will have the MW for the WTG plant</inlineHelpText>
    <label>Quote Line Quantity</label>
    <precision>18</precision>
    <scale>3</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Renewal_Action__c.field-meta.xml
<CustomField>
    <fullName>Renewal_Action__c</fullName>
    <label>Renewal Action</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Added Plant</fullName>
            </value>
            <value>
                <fullName>Removed Plant</fullName>
            </value>
            <value>
                <fullName>No Change</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Amendment_Quoted</fullName>
                <label>Amendment Quoted</label>
            </value>
            <value>
                <fullName>Renewal Quoted</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Subscription__c.field-meta.xml
<CustomField>
    <fullName>Subscription__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Subscription</label>
    <referenceTo>SBQQ__Subscription__c</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Unit_Price_After_Volume_Discount__c.field-meta.xml
<CustomField>
    <fullName>Unit_Price_After_Volume_Discount__c</fullName>
    <description>This is the Unit Price after Software Discount Tier or Implementation Bracket pricing is applied to Contracted Price or List Price</description>
    <inlineHelpText>This is the Unit Price after Software Discount Tier or Implementation Bracket pricing is applied to Contracted Price or List Price</inlineHelpText>
    <label>Unit Price After Volume Discount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Quotes</relationshipLabel>
    <relationshipName>Quotes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>Quote_Lines</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Subscription__c/SBQQ__Subscription__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__SubscriptionHelp</customHelpPage>
    <description>Subscription to a product or service currently or previously owned by a customer.</description>
    <label>Subscription</label>
    <nameField>
        <displayFormat>SUB-{0000000}</displayFormat>
        <label>Subscription #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscriptions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Subscription__c/fields/Line_Classification__c.field-meta.xml
<CustomField>
    <fullName>Line_Classification__c</fullName>
    <label>Line Classification</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Subscription__c/fields/Plant_Product_Transaction__c.field-meta.xml
<CustomField>
    <fullName>Plant_Product_Transaction__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Product Transaction</label>
    <referenceTo>Plant_Product_Transaction__c</referenceTo>
    <relationshipLabel>Subscriptions</relationshipLabel>
    <relationshipName>Subscriptions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/RenewableQuoteProcessHelper.cls
public class RenewableQuoteProcessHelper {
    
    public static void createChildPPTunderRenewableQL(Set<Id> quoteIds){
        
        
        String query = 'select id,name,Product__c,Renewal_Action__c,CurrencyIsoCode,Plant__c,Subscription__r.SBQQ__Discount__c,Unit_Price_After_Volume_Discount__c,Subscription__r.Line_Classification__c,Contracted_MW_Unit_List_Price__c,Quote_Line_Quantity__c,Plant__r.Plant__r.MWp__c,Account__c,Subscription__c,Subscription__r.SBQQ__QuoteLine__c  '
            			+' from Plant_Product_Transaction__c '
            			+' where Subscription__c != Null AND Status__c = \'Contracted\' AND Plant__r.Status__c =\'Active\' AND Quote_Line__r.SBQQ__Quote__c In: quoteIds';
        
        List<Plant_Product_Transaction__c> pptList = Database.query(query);
        
        Map<Id,List<Plant_Product_Transaction__c>> vargQuotePptMap = new  Map<Id,List<Plant_Product_Transaction__c>>();   
         
            for(Plant_Product_Transaction__c ppt : pptList){																	
            if(vargQuotePptMap.containsKey(ppt.Subscription__c)){
                vargQuotePptMap.get(ppt.Subscription__c).add(ppt);
               //system.debug('The get of vargQuotePptMap '+vargQuotePptMap); 
            }else{
                vargQuotePptMap.put(ppt.Subscription__c , new List<Plant_Product_Transaction__c>{ppt});
                //system.debug('The add this to the ovargQuotePptMap '+vargQuotePptMap);
                
            }
        }
        
        List<SBQQ__QuoteLine__c> qlList = [SELECT ID,SBQQ__RenewedSubscription__c ,
                                           SBQQ__Product__c,
                                           SBQQ__Quantity__c,
                                           SBQQ__ListPrice__c,
                                           SBQQ__SpecialPrice__c,
                                           SBQQ__Quote__r.name,
                                           SBQQ__Quote__r.OwnerId,
                                           SBQQ__Quote__r.CurrencyIsoCode,
                                           SBQQ__Quote__r.SBQQ__StartDate__c,
                                           SBQQ__Quote__r.SBQQ__EndDate__c,
                                           //Plant_Product_Transaction__r.Plant__c,


                                           (Select id from Plant_Product_Transactions__r) 
                                           FROM SBQQ__QuoteLine__c 
                                           WHERE SBQQ__RenewedSubscription__c IN : vargQuotePptMap.keySet() LIMIT 50000];
        
        List<Plant_Product_Transaction__c> pptListTOClone = new List <Plant_Product_Transaction__c>();
        for(SBQQ__QuoteLine__c ql : qlList){
            //system.debug('ql.Plant_Product_Transactions__r--'+ql.Plant_Product_Transactions__r);
            //system.debug('ql.SBQQ__RenewedSubscription__c--'+ql.SBQQ__RenewedSubscription__c);
            if(vargQuotePptMap.containsKey(ql.SBQQ__RenewedSubscription__c) && ( ql.Plant_Product_Transactions__r.size() == null || ql.Plant_Product_Transactions__r.size() == 0)){
                
                system.debug('ql.Plant_Product_Transactions__r--'+ql.Plant_Product_Transactions__r);
                for( Plant_Product_Transaction__c ppt:vargQuotePptMap.get(ql.SBQQ__RenewedSubscription__c) ){
                    Plant_Product_Transaction__c pp = ppt.clone(false,true,false,false);
                    pp.Quote_Line__c = ql.Id;
                    pp.Product__c=ql.SBQQ__Product__c;
                    pp.Quote__c=ql.SBQQ__Quote__r.id;
                    //pp.OwnerId = ql.SBQQ__Quote__r.OwnerId;
                    pp.CurrencyIsoCode= ppt.CurrencyIsoCode;
                    pp.Renewal_Action__c ='Renewed';
                    pp.Plant_Product__c=true;
                    pp.OwnerId=ql.SBQQ__Quote__r.OwnerId;
                    decimal s=ql.SBQQ__SpecialPrice__c;
                    decimal c=pp.Contracted_MW_Unit_List_Price__c;
                    c=s;
                    //pp.Contracted_MW_Unit_List_Price__c=ql.SBQQ__SpecialPrice__c;
                    pp.Unit_Price_After_Volume_Discount__c=ppt.Unit_Price_After_Volume_Discount__c;
                    
                    pp.MWp_Quantity__c=pp.Plant__r.Plant__r.MWp__c;
                    pp.Quote_Line_Quantity__c=pp.Plant__r.Plant__r.MWp__c;
                    pp.CurrencyIsoCode = ql.SBQQ__Quote__r.CurrencyIsoCode;
                    pp.List_Unit_Price__c=ql.SBQQ__ListPrice__c;
                    pp.Status__c = 'Renewal Quoted';
                    pp.Subscription__c = null;
                    pptListTOClone.add(pp);
                    
                    if(ql.SBQQ__Quote__r.SBQQ__StartDate__c !=null) {
                        pp.Effective_Date__c = ql.SBQQ__Quote__r.SBQQ__StartDate__c;
                        //System.debug('Start Date is on the Quote...so putting effective date in pp from Quote start date');
                    }
                    else {
                        pp.Effective_Date__c = ql.SBQQ__StartDate__c;
                        //System.debug('There is no Start Date is on the Quote...so taking from Quote line in pp record');
                    }
                    if(ql.SBQQ__Quote__r.SBQQ__EndDate__c !=null) {
                        pp.End_Date__c = ql.SBQQ__Quote__r.SBQQ__EndDate__c;
                        //System.debug('End Date is on the Quote...so putting end date in pp from Quote end  date');
                    } 
                    else { 
                        pp.End_Date__c = ql.SBQQ__EndDate__c;
                        //System.debug('There is no End Date is on the Quote...so taking from Quote line in pp record');
                    }
                    
                    
                    if(pp.Subscription__r.SBQQ__Discount__c!=null && pp.Status__c =='Renewal Quoted') {
                        pp.Addl_Discount_Percent__c = pp.Subscription__r.SBQQ__Discount__c;
                        //System.debug(' the Subscription has Additional Discount Percent – if yes, then populate Addl Discount Percent ');
                    }  
                    
                }
            }
        }
        
        if(pptListTOClone != null && pptListTOClone.size() > 0)
        {
            system.debug('pptListTOClone--'+pptListTOClone.size());
            try{
                insert pptListTOClone;
            }catch(Exception ep){
                system.debug(ep.getMessage());
            }
        }
        
    }
    
    
    
    public static void createChildPPTforRenewQLByAmendOpp(Set<Id> contIds){
        
        Set<String> pptStatusSet = new Set<String>{'Renewal Quoted','Amendment_Quoted','Contracted'};
        
        List<Contract> conList = [select id ,
                                  		(select id,
                                         		name 
                                         from SBQQ__AmendmentOpportunities__r 
                                         where StageName = 'Closed Won' 
                                         ORDER BY createddate desc 
                                         LIMIT 1) 
                                  from contract 
                                  where Id In :contIds ];
        
        
        Set<Id> idSetForAmbedmentOpp = new Set<Id>();
        
        for(Contract cont : conList){
            if(cont.SBQQ__AmendmentOpportunities__r != null && cont.SBQQ__AmendmentOpportunities__r.size() > 0)idSetForAmbedmentOpp.add(cont.SBQQ__AmendmentOpportunities__r[0].Id);
        }
        
        if(!idSetForAmbedmentOpp.isEmpty()){
            
            List<Plant_Product_Transaction__c> amendedSourcePPTRec = [select id,name,Product__c,Renewal_Action__c,CurrencyIsoCode,Plant__c,
                                                                      Subscription__r.SBQQ__Discount__c,Unit_Price_After_Volume_Discount__c,
                                                                      Subscription__r.Line_Classification__c,Contracted_MW_Unit_List_Price__c,
                                                                      Quote_Line_Quantity__c,Plant__r.Plant__r.MWp__c,Account__c,Subscription__c,
                                                                      Subscription__r.SBQQ__QuoteLine__c
                                                                      from Plant_Product_Transaction__c 
                                                                      where Quote_Line__r.SBQQ__Quote__r.SBQQ__Opportunity2__r.Id In :idSetForAmbedmentOpp
                                                                      AND Quote_Line__r.SBQQ__Quote__r.SBQQ__Type__c  = 'Amendment' 
                                                                      AND Quote_Line__r.SBQQ__Quote__r.SBQQ__Primary__c =  true
                                                                      AND Status__c IN :pptStatusSet ];
            
            system.debug('amendedSourcePPTRec--'+amendedSourcePPTRec);
            
            Map<Id,List<Plant_Product_Transaction__c>> amendQuotePptMap = new  Map<Id,List<Plant_Product_Transaction__c>>();   
            
            for(Plant_Product_Transaction__c ppt : amendedSourcePPTRec){																	
                if(amendQuotePptMap.containsKey(ppt.Product__c)) amendQuotePptMap.get(ppt.Product__c).add(ppt);
                else amendQuotePptMap.put(ppt.Product__c , new List<Plant_Product_Transaction__c>{ppt});
            }
            
            system.debug('amendQuotePptMap--'+amendQuotePptMap);
        	
            List<SBQQ__QuoteLine__c> qlList = [SELECT ID,SBQQ__RenewedSubscription__c ,
                                               SBQQ__Product__c,
                                               SBQQ__Quantity__c,
                                               SBQQ__ListPrice__c,
                                               SBQQ__SpecialPrice__c,
                                               SBQQ__Quote__r.name,
                                               SBQQ__Quote__r.OwnerId,
                                               SBQQ__Quote__r.CurrencyIsoCode,
                                               SBQQ__Quote__r.SBQQ__StartDate__c,
                                               SBQQ__Quote__r.SBQQ__EndDate__c,
                                               (Select id from Plant_Product_Transactions__r) 
                                               FROM SBQQ__QuoteLine__c 
                                               WHERE SBQQ__Quote__r.SBQQ__Type__c  = 'Renewal' 
                                               AND SBQQ__Product__c IN : amendQuotePptMap.keySet()
                                               AND SBQQ__Quote__r.SBQQ__Primary__c =  true 
                                               AND SBQQ__Quote__r.SBQQ__Opportunity2__r.QS_Order_Type__c = 'Renewal' 
                                               AND SBQQ__Quote__r.SBQQ__Opportunity2__r.SBQQ__RenewedContract__c IN :contIds  LIMIT 50000]; //
            for(SBQQ__QuoteLine__c ql : qlList){
                system.debug('qlId--'+ql.Id);
            }

            List<Plant_Product_Transaction__c> pptListTOClone = new List <Plant_Product_Transaction__c>();
            for(SBQQ__QuoteLine__c ql : qlList){
                //system.debug('ql.Plant_Product_Transactions__r--'+ql.Plant_Product_Transactions__r);
                //system.debug('ql.SBQQ__RenewedSubscription__c--'+ql.SBQQ__RenewedSubscription__c);
                if(amendQuotePptMap.containsKey(ql.SBQQ__Product__c) && ( ql.Plant_Product_Transactions__r.size() == null || ql.Plant_Product_Transactions__r.size() == 0)){
                    
                    system.debug('ql.Plant_Product_Transactions__r--'+ql.Plant_Product_Transactions__r);
                    for( Plant_Product_Transaction__c ppt:amendQuotePptMap.get(ql.SBQQ__Product__c) ){
                        Plant_Product_Transaction__c pp = ppt.clone(false,true,false,false);
                        pp.Quote_Line__c = ql.Id;
                        pp.Product__c=ql.SBQQ__Product__c;
                        pp.Quote__c=ql.SBQQ__Quote__r.id;
                        //pp.OwnerId = ql.SBQQ__Quote__r.OwnerId;
                        pp.CurrencyIsoCode= ppt.CurrencyIsoCode;
                        pp.Renewal_Action__c ='Renewed';
                        pp.Plant_Product__c=true;
                        pp.OwnerId=ql.SBQQ__Quote__r.OwnerId;
                        decimal s=ql.SBQQ__SpecialPrice__c;
                        decimal c=pp.Contracted_MW_Unit_List_Price__c;
                        c=s;
                        //pp.Contracted_MW_Unit_List_Price__c=ql.SBQQ__SpecialPrice__c;
                        pp.Unit_Price_After_Volume_Discount__c=ppt.Unit_Price_After_Volume_Discount__c;
                        
                        pp.MWp_Quantity__c=pp.Plant__r.Plant__r.MWp__c;
                        pp.Quote_Line_Quantity__c=pp.Plant__r.Plant__r.MWp__c;
                        pp.CurrencyIsoCode = ql.SBQQ__Quote__r.CurrencyIsoCode;
                        pp.List_Unit_Price__c=ql.SBQQ__ListPrice__c;
                        pp.Status__c = 'Renewal Quoted';
                        pp.Subscription__c = null;
                        pptListTOClone.add(pp);
                        
                        if(ql.SBQQ__Quote__r.SBQQ__StartDate__c !=null) {
                            pp.Effective_Date__c = ql.SBQQ__Quote__r.SBQQ__StartDate__c;
                            //System.debug('Start Date is on the Quote...so putting effective date in pp from Quote start date');
                        }
                        else {
                            pp.Effective_Date__c = ql.SBQQ__StartDate__c;
                            //System.debug('There is no Start Date is on the Quote...so taking from Quote line in pp record');
                        }
                        if(ql.SBQQ__Quote__r.SBQQ__EndDate__c !=null) {
                            pp.End_Date__c = ql.SBQQ__Quote__r.SBQQ__EndDate__c;
                            //System.debug('End Date is on the Quote...so putting end date in pp from Quote end  date');
                        } 
                        else { 
                            pp.End_Date__c = ql.SBQQ__EndDate__c;
                            //System.debug('There is no End Date is on the Quote...so taking from Quote line in pp record');
                        }
                        
                        
                        if(pp.Subscription__r.SBQQ__Discount__c!=null && pp.Status__c =='Renewal Quoted') {
                            pp.Addl_Discount_Percent__c = pp.Subscription__r.SBQQ__Discount__c;
                            //System.debug(' the Subscription has Additional Discount Percent – if yes, then populate Addl Discount Percent ');
                        }  
                        
                    }
                }
            }
            
            if(pptListTOClone != null && pptListTOClone.size() > 0)
            {
                system.debug('pptListTOClone--'+pptListTOClone.size());
                try{
                    insert pptListTOClone;
                }catch(Exception ep){
                    system.debug(ep.getMessage());
                }
                
            }
            for(Plant_Product_Transaction__c ppt : pptListTOClone){
                system.debug('ppt--'+ppt);
            }
        }
        
    }
    
    
    
  public static void updateQuantityOnQuoteLineItem2(List<SBQQ__QuoteLine__c> qlListRec){ //List of QL that may be Renewable or original 
       
       
        
        List<SBQQ__QuoteLine__c> qlList = [SELECT ID,SBQQ__RenewedSubscription__c ,(Select id,Quote_Line_Quantity__c from Plant_Product_Transactions__r)
                                           FROM SBQQ__QuoteLine__c 
                                           WHERE Id IN : qlListRec];
        
        List<SBQQ__QuoteLine__c> qlToUpdate = new List<SBQQ__QuoteLine__c>();
        for(SBQQ__QuoteLine__c ql : qlList){
            if(ql.Plant_Product_Transactions__r != null && ql.Plant_Product_Transactions__r.size() > 0){
                Decimal sumOfPPTQuoteLineQuantity = 0;
                for(Plant_Product_Transaction__c ap: ql.Plant_Product_Transactions__r){
                    sumOfPPTQuoteLineQuantity += ap.Quote_Line_Quantity__c;
                }
                if(sumOfPPTQuoteLineQuantity > 0){
                    ql.SBQQ__Quantity__c = sumOfPPTQuoteLineQuantity;
                    qlToUpdate.add(ql);
                }
                
            }
        }
        
        try {
            update qlToUpdate;
            
            for(SBQQ__QuoteLine__c ql : qlToUpdate){
                
                PlantProductController.updatePricingForQuoteLineInPPT(String.valueOf(ql.Id));
                PlantProductController.updatePricingfromPPTToQuoteline (String.valueOf(ql.Id));
                
            }
        }
        catch(Exception ex) {
            System.debug('Error updating MWh quantity on quote line'
                         +string.valueOf(ex.getLineNumber()) +ex.getTypeName() +string.valueOf(ex.getCause()) +ex.getMessage() +ex.getStackTraceString());
        }
        
    }  
    
}