unpackaged/main/default/objects/Plant__c/Plant__c.object-meta.xml
<CustomObject>
    <label>Plant</label>
    <nameField>
        <label>Plant Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plants</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <label>Plant Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Contract__c.field-meta.xml
<CustomField>
    <fullName>Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant__c.field-meta.xml
<CustomField>
    <fullName>Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <formula>Plant__r.Plant__r.Name</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Plant Product Transaction</relationshipLabel>
    <relationshipName>Plant_Product_Transaction</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Purchase Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Quoted</fullName>
            </value>
            <value>
                <fullName>Ordered</fullName>
            </value>
            <value>
                <fullName>Contracted</fullName>
            </value>
            <value>
                <fullName>Amendment_Quoted</fullName>
                <label>Amendment Quoted</label>
            </value>
            <value>
                <fullName>Renewal Quoted</fullName>
            </value>
            <value>
                <fullName>Decommissioned</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/RelatedListsController.cls
/**
 * @description       :
 * @author            : Justin Smith @cyberjus
 * @group             :
 * @last modified on  : 08-31-2022
 * @last modified by  : Justin Smith @cyberjus
 **/
public with sharing class RelatedListsController {
  @AuraEnabled(cacheable=true)
  public static List<Plant_Product_Transaction__c> getPlantProductTransactionsByAccount(
    Id accountId,
    Integer recordCount,
    String search
  ) {
    try {
      String target;
      String soql = 'select Id, Name, Plant__c, ';
      soql += 'Plant_Name__c, Product__c, Product__r.Name, End_Date__c, Contract__c, Contract__r.ContractNumber ';
      soql += 'from Plant_Product_Transaction__c where Account__c = :accountId ';
      soql += 'and Status__c = \'Contracted\' and End_Date__c >= TODAY ';
      if (!String.isBlank(search)) {
        target = '%' + search + '%';
        soql += 'and (Plant_Name__c LIKE :target OR Product__r.Name LIKE :target OR Contract__r.ContractNumber LIKE :target) ';
      }
      soql += 'order by Plant_Name__c limit :recordCount';

      return (List<Plant_Product_Transaction__c>) Database.query(soql);
    } catch (Exception e) {
      System.debug(e.getStackTraceString());    
      throw new AuraHandledException(e.getMessage());
    }
  }
}