unpackaged/main/default/objects/Program__c/Program__c.object-meta.xml
<CustomObject>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Program</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Program__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <displayFormat>A-{0000}</displayFormat>
    <label>Program ID</label>
    <type>AutoNumber</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Program__c.field-meta.xml
<CustomField>
    <fullName>Program__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Program_Name__c.field-meta.xml
<CustomField>
    <fullName>Program_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Program Name</label>
    <referenceTo>Program__c</referenceTo>
    <relationshipLabel>Projects</relationshipLabel>
    <relationshipName>Projects</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ProgramControllerTest.cls
/**
 * The Test class for apex ProgramController.   
 * @param  :  
 * @return :  
 */
@isTest
public class ProgramControllerTest {
	static testmethod void testAddProgram() {
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
        
        Program__c progm = TestDataFactory.createProgram(accnt.Id);
        insert progm;
        
        project_cloud__Project__c projectRecord = TestDataFactory.createCCProjectTemplate('Monitoring Implementation',accnt.Id);
        insert projectRecord;
        List<string> projectIds = new List<string>();
        projectIds.add(projectRecord.Id);
        Test.startTest();
        	ProgramController.fetchData(progm.Id);
        	ProgramController.addProjects(progm.Id, JSON.serialize(projectIds));
        Test.stopTest();
        project_cloud__Project__c projectProcessed = [select Program_Name__c from project_cloud__Project__c where id =:projectRecord.Id];
        system.debug('::projectProcessed'+projectProcessed);
        System.assertEquals(progm.Id,projectProcessed.Program_Name__c);
    }
}