unpackaged/main/default/objects/Account/fields/Account_Status__c.field-meta.xml
<CustomField>
    <fullName>Account_Status__c</fullName>
    <label>Account Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Unapproved</fullName>
                <default>true</default>
                <label>Unapproved</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/QS_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>QS_Order_Type__c</fullName>
    <description>An additional deal type classification. This is where Sales clarifies whether this is New Product, Renewal, Decommission, etc.</description>
    <inlineHelpText>An additional deal type classification. Clarifies whether this is New Product, Renewal, Decommission, etc.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Services Only</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Subscription Renewal</fullName>
            </value>
            <value>
                <fullName>Decommission</fullName>
            </value>
            <value>
                <fullName>Contract Renewal</fullName>
            </value>
            <value>
                <fullName>Overage</fullName>
            </value>
            <value>
                <fullName>Debooking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Amend And Renewal Process</businessProcess>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Class</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>&quot;Software</fullName>
                <isActive>false</isActive>
                <label>&quot;Software</label>
            </value>
            <value>
                <fullName>Professional Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Professional Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Pro</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
            </value>
            <value>
                <fullName>Add-ons</fullName>
            </value>
            <value>
                <fullName>Breeze Development</fullName>
            </value>
            <value>
                <fullName>Core Lite</fullName>
            </value>
            <value>
                <fullName>Ekho</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>&quot;Core</fullName>
                <isActive>false</isActive>
                <label>&quot;Core</label>
            </value>
            <value>
                <fullName>Edge Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Edge Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Services__c.field-meta.xml
<CustomField>
    <fullName>Product_Services__c</fullName>
    <label>Product Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Customization</fullName>
            </value>
            <value>
                <fullName>Consulting/Other</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/QS_Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>A summarization of the customer&#39;s currently-owned products.</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Customer Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Account__c.field-meta.xml
<CustomField>
    <fullName>QS_Account__c</fullName>
    <description>Indicates the account that is primarily associated with the customer asset. This is the account that purchased the product.</description>
    <inlineHelpText>Indicates the account that is primarily associated with the customer asset. This is the account that purchased the product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QS_Customer_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Product__c.field-meta.xml
<CustomField>
    <fullName>QS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product this customer asset represents. Customer asset records are created when the product field Generate Customer Asset = true.</description>
    <inlineHelpText>The product this customer asset represents. Customer asset records are created when the product field Generate Customer Asset = true.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>QS_Customer_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_Start_Date__c</fullName>
    <description>Roll-up field displaying the earliest start date of all Customer Asset Transactions for this product. This field shows when the customer first purchased the product. This date never changes. Start Date must be populated on at least one CAT.</description>
    <inlineHelpText>Roll-up field displaying the earliest start date of all Customer Asset Transactions for this product. This field shows when the customer first purchased the product. This date never changes. Start Date must be populated on at least one CAT.</inlineHelpText>
    <label>Start Date</label>
    <summarizedField>QS_Customer_Asset_Detail__c.QS_Start_Date__c</summarizedField>
    <summaryForeignKey>QS_Customer_Asset_Detail__c.QS_Customer_Asset__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/QS_Customer_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>Transnational detail that feeds the Customer Assets
		Start/End Dates, ARR</description>
    <label>Subscription Transaction</label>
    <nameField>
        <displayFormat>CAT-{0000000}</displayFormat>
        <label>Subscription Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Account__c.field-meta.xml
<CustomField>
    <fullName>QS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer who owns the product.</description>
    <inlineHelpText>The customer who owns the product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Asset_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Currently_Active__c.field-meta.xml
<CustomField>
    <fullName>QS_Currently_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the start date of the CAT is in the today or passed and the end date is today in the future.</description>
    <inlineHelpText>Indicates that the start date of the CAT is in the today or passed and the end date is today in the future.</inlineHelpText>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Customer_Asset__c.field-meta.xml
<CustomField>
    <fullName>QS_Customer_Asset__c</fullName>
    <description>Master-Detail lookup to the parent Customer Asset record.</description>
    <inlineHelpText>Master-Detail lookup to the parent Customer Asset record.</inlineHelpText>
    <label>Customer Asset</label>
    <referenceTo>QS_Customer_Asset__c</referenceTo>
    <relationshipName>QS_Customer_Asset_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Product__c.field-meta.xml
<CustomField>
    <fullName>QS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product this CAT represents.</description>
    <inlineHelpText>The product this CAT represents.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>QS_Customer_Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__Quote__c/fields/SBQQ__SubscriptionTerm__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__SubscriptionTerm__c</fullName>
    <description>Subscription term used to prorate eligible products by day or month.  This has been set by your administrator.</description>
    <inlineHelpText>Enter 12 unless duration should be less than a year. Ex. Trial.</inlineHelpText>
    <label>Subscription Term</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SaaS</fullName>
            </value>
            <value>
                <fullName>Recurring</fullName>
            </value>
            <value>
                <fullName>One-Time</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hydro</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Other Renewable</fullName>
    </customValue>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Wind</fullName>
    </customValue>
    <customValue>
        <fullName>All Renewables (Agnostic)</fullName>
    </customValue>
    <masterLabel>Asset Class</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SaaS</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Recurring</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CA2_OpportunityTriggerHandlerTest.cls
/******************************************************************************
 * Test class for the OpportunityTrigger and it's supporting classes 
 *
 */
@isTest( SeeAllData=false )
private class CA2_OpportunityTriggerHandlerTest 
{


    static testMethod void  test_Process0QuantityOpportunityLineItems()
    {
        Account newAccount = new Account();
        newAccount.Name = 'Test Account';
        newAccount.Account_Status__c = 'Approved';
        insert newAccount;
        
        Product2 product1 = new Product2();
        product1.ProductCode = 'product-2';
        product1.Name = 'Hardware Product 2';
        product1.Description = 'Hardware Product 2 Description';
        product1.Family = 'HardwareFamily';
        product1.QS_Generate_Asset__c = true;
        product1.IsActive = true;
        product1.SBQQ__SubscriptionPricing__c = 'Percent Of Total';
        product1.SBQQ__SubscriptionType__c = 'Renewable';
        product1.SBQQ__SubscriptionTerm__c = 12;
        product1.SBQQ__QuantityEditable__c = true;
        product1.SBQQ__IncludeInMaintenance__c = true;
        product1.Product_Line__c = 'Core'; 
product1.Product_Category__c = 'Software';
product1.Product_Type__c = 'SaaS';
product1.Product_Services__c = 'N/A';
product1.Asset_Class__c = 'Solar';
        insert product1; 
        
        Id renewalRecordTypeId = Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get('Renewal').getRecordTypeId();
        
        Opportunity renewalOpp = new Opportunity();
        renewalOpp.AccountId = newAccount.Id;
        renewalOpp.Type='Existing Business';
        renewalOpp.QS_Order_Type__c='Subscription Renewal';    
        renewalOpp.StageName= '4 - Evaluation';
        renewalOpp.CloseDate = System.today();
        renewalOpp.Name = 'Test Renewal';
        renewalOpp.RecordTypeId = renewalRecordTypeId;
        insert renewalOpp;

        SBQQ__Quote__c newQuote = new SBQQ__Quote__c();
        
        newQuote.SBQQ__Type__c = 'Renewal';
        newQuote.SBQQ__ExpirationDate__c = System.today().addDays(200);
        newQuote.SBQQ__Account__c = newAccount.Id;
        newQuote.SBQQ__Opportunity2__c = renewalOpp.Id;
        newQuote.ApprovalStatus__c = 'Approved';
        newQuote.SBQQ__Primary__c = true;
        insert newQuote;

        SBQQ__QuoteLine__c newQuoteLine = new  SBQQ__QuoteLine__c();
        newQuoteLine.SBQQ__Product__c = product1.Id;
        newQuoteLine.SBQQ__Quantity__c = 0;
       // newQuoteLine.QS_Account__c = newAccount.Id;
        newQuoteLine.SBQQ__Quote__c = newQuote.Id;
        insert newQuoteLine;

        QS_Customer_Asset__c ca = new QS_Customer_Asset__c();
        ca.QS_Account__c = newAccount.Id; 
        ca.QS_Product__c = product1.Id;
        insert ca; 
       
        QS_Customer_Asset_Detail__c cad = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-365),QS_End_Date__c = System.today().addDays(+5));
        cad.QS_Product__c = product1.Id;
        insert cad;
         renewalOpp.SBQQ__PrimaryQuote__c = newQuote.Id;
         renewalOpp.StageName = '00 - MQL';
        // update renewalOpp;
        
        CA2_OpportunityTriggerHandler thl = new CA2_OpportunityTriggerHandler();
        List<Opportunity> listOfOpp = new List<Opportunity>();
        listOfOpp.add(renewalOpp);
        thl.addDecommissionRecordsForZeroedOutProducts(listOfOpp);
        thl.processZeroedOutQuoteLines(listOfOpp);
        thl.getDecommissionRecordByQuoteLine(newQuoteLine, ca);
        thl.UpdateHistoricalCadsPendingRenewal(listOfOpp);
        
        

    }
}// /END Test Class