unpackaged/main/default/objects/Account/fields/Account_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Account_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Greenbyte Req</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Account with which we are signing the MSA.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MSA Contracts</relationshipLabel>
    <relationshipName>MSA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/MSA_Implementation_Bracket_Price__c.object-meta.xml
<CustomObject>
    <label>MSA Implementation Bracket Price</label>
    <nameField>
        <displayFormat>IP-{00000}</displayFormat>
        <label>MSA Implementation Bracket Price Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Implementation Bracket Prices</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Create_MSA_Implementation_Bracket_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>All Renewables (Agnostic)</fullName>
            </value>
            <value>
                <fullName>Wind</fullName>
            </value>
            <value>
                <fullName>Solar</fullName>
            </value>
            <value>
                <fullName>Storage</fullName>
            </value>
            <value>
                <fullName>Hydro</fullName>
            </value>
            <value>
                <fullName>Other Renewable</fullName>
            </value>
            <value>
                <fullName>Industrial</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <label>Description</label>
    <length>512</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Fixed_Price__c.field-meta.xml
<CustomField>
    <fullName>Fixed_Price__c</fullName>
    <label>Fixed Price</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound (in MW)</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/MSA_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSA_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSA Contract</label>
    <referenceTo>MSA_Contract__c</referenceTo>
    <relationshipLabel>MSA Implementation Bracket Prices</relationshipLabel>
    <relationshipName>MSA_Implementation_Bracket_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <label>Pricing Tier</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MSA_Implementation_Bracket_Price__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>16</precision>
    <scale>4</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/ImplementationBracketPrice.cls
public class ImplementationBracketPrice {

    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchAccountName(String RecId){
        System.debug('Implementation Bracket fetchAccountName');
        return [Select Account_Name__r.Name from MSA_Contract__c where Id = :RecId];
    }
    

    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchCurrency(String RecId){
        System.debug('Implementation Bracket fetchCurrency');
        return [Select CurrencyIsoCode from MSA_Contract__c where Id = :RecId];
    }


    @AuraEnabled(cacheable=true)
    public static List<MSA_Implementation_Bracket_Price__c> implementationBracketPriceRecords(String RecId){
        List<MSA_Contract__c> accountId = [Select Account_Name__r.Account_Price_Book__r.name from MSA_Contract__c where Id = :RecId limit 1];
        Id accId = string.valueOf(accountId[0].Account_Name__c);
        List<MSA_Implementation_Bracket_Price__c> records = [Select Name , Lower_Bound__c, Upper_Bound__c, Pricing_Tier__c, Fixed_Price__c, Asset_Class__c, Description__c 
            from MSA_Implementation_Bracket_Price__c 
            where Account__r.Id = :accId];
        system.debug('Account ID' + accId);
        system.debug('No of records found with contracted price =>' + records.size());
        return records;
    }
    
}