unpackaged/main/default/objects/Account/fields/Account_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Account_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Greenbyte Req</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Account with which we are signing the MSA.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MSA Contracts</relationshipLabel>
    <relationshipName>MSA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__ContractedPrice__c/fields/MSA_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSA_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSA Contract</label>
    <referenceTo>MSA_Contract__c</referenceTo>
    <relationshipLabel>Contracted Prices</relationshipLabel>
    <relationshipName>Contracted_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__ContractedPrice__c/fields/Product_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Product_List_Price__c</fullName>
    <description>List Price of related Product</description>
    <label>Product List Price</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__ContractedPrice__c/fields/Same_As_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Same_As_List_Price__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This flag is to track if the Contract Price has been changed from the List Price</description>
    <inlineHelpText>This flag is to track if the Contract Price has been changed from the List Price</inlineHelpText>
    <label>Same As List Price</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AccountForMSAContractedPrices.cls
public class AccountForMSAContractedPrices {
    
    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchAccountName(String RecId){
        System.debug('Entered function fetchAccountName');
        return [Select Account_Name__r.Name from MSA_Contract__c where Id = :RecId];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchCurrency(String RecId){
        System.debug('Entered function fetchCurrency');
        return [Select CurrencyIsoCode from MSA_Contract__c where Id = :RecId];
    }
    
    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchPriceBook(String RecId){
        System.debug('Entered function fetchPriceBook');
        return [Select Account_Name__r.Account_Price_Book__r.Name from MSA_Contract__c where Id = :RecId];
    }
    
    
    @AuraEnabled(cacheable=true)
    public static List<SBQQ__ContractedPrice__c> contractedPricesRecord(String RecId){
        List<MSA_Contract__c> accountId = [Select Account_Name__r.Account_Price_Book__r.name from MSA_Contract__c where Id = :RecId limit 1];
        Id accId = string.valueOf(accountId[0].Account_Name__c);
        List<SBQQ__ContractedPrice__c> records = [Select SBQQ__Product__r.Name, SBQQ__Product__r.ProductCode , Product_List_Price__c, SBQQ__Price__c 
            from SBQQ__ContractedPrice__c 
            where SBQQ__Account__r.Id = :accId AND Same_As_List_Price__c = False AND SBQQ__Product__r.ProductCode != null];
        system.debug('Account ID' + accId);
        system.debug('No of records found with contracted price =>' + records.size());
        return records;
    }


    @AuraEnabled(cacheable=true)
    public static List<SBQQ__ContractedPrice__c> priceBookRecords(String RecId){

        List<MSA_Contract__c> accountId = [Select Account_Name__r.Account_Price_Book__r.name from MSA_Contract__c where Id = :RecId limit 1];
        Id accId = string.valueOf(accountId[0].Account_Name__c);
        List<SBQQ__ContractedPrice__c> records = [Select SBQQ__Product__r.Name, Same_As_List_Price__c, SBQQ__Product__r.ProductCode , Product_List_Price__c, SBQQ__Price__c 
            from SBQQ__ContractedPrice__c 
            where SBQQ__Account__r.Id = :accId AND Same_As_List_Price__c = True];
        system.debug('Account ID' + accId);
        system.debug('No of records found with contracted price =>' + records.size());
        return records;

    }


    @AuraEnabled
    public static string updateContractedPrices(Object data) {
    List<SBQQ__ContractedPrice__c> contractPriceForUpdate = new List<SBQQ__ContractedPrice__c>();
    List<SBQQ__ContractedPrice__c> contractPriceDataList = (List<SBQQ__ContractedPrice__c>) JSON.deserialize(
         JSON.serialize(data),
         List<SBQQ__ContractedPrice__c>.class
            );
            Set<ID> contactedPRiceIdSet = new Set<id>();
            Map<Id, SBQQ__ContractedPrice__c> contractedPriceDataMap = new Map<Id,SBQQ__ContractedPrice__c>(); 
            for(SBQQ__ContractedPrice__c conPrice: contractPriceDataList){
                contactedPRiceIdSet.add(conPrice.Id);
                contractedPriceDataMap.put(conPrice.Id, conPrice);
            }
            List<SBQQ__ContractedPrice__c> contractedPriceList = [Select id, Product_List_Price__c from SBQQ__ContractedPrice__c where id in:contactedPRiceIdSet ];
            for(SBQQ__ContractedPrice__c conPriceRec: contractedPriceList){
                if(conPriceRec.Product_List_Price__c != contractedPriceDataMap.get(conPriceRec.Id).SBQQ__Price__c){
                   contractPriceForUpdate.add(contractedPriceDataMap.get(conPriceRec.Id));
                }
            }
            system.debug('Contracted Price Record=>' + contractPriceForUpdate);
            try {
                update contractPriceForUpdate;
                return 'Success: Contracted Prices updated successfully';
                }
            catch (Exception e) {
                return 'The following exception has occurred: ' + e.getMessage();
                }
    }


        @AuraEnabled 
		public static void deleteContractedPrice(List<SBQQ__ContractedPrice__c> cpList, String msaId){
            if (cpList.size()>0)
            {
                List<SBQQ__ContractedPrice__c> lstSelectedContractedRecords = new List<SBQQ__ContractedPrice__c>();

                for(SBQQ__ContractedPrice__c cps :cpList )
                {
                    if(cps.SBQQ__Price__c != cps.Product_List_Price__c){
                        cps.SBQQ__Price__c = cps.Product_List_Price__c;
                        cps.Same_As_List_Price__c = True;
                        lstSelectedContractedRecords.add(cps);
                    }
                }
                System.debug('Cp list : '+cpList);
                if(lstSelectedContractedRecords.size()>0)
                {
                    update lstSelectedContractedRecords;
                }
            }

        }

}