unpackaged/main/default/objects/Account/fields/Account_Price_Book__c.field-meta.xml
<CustomField>
    <fullName>Account_Price_Book__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Greenbyte Req</description>
    <label>Price Book</label>
    <referenceTo>Pricebook2</referenceTo>
    <relationshipLabel>Accounts</relationshipLabel>
    <relationshipName>Accounts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Account with which we are signing the MSA.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MSA Contracts</relationshipLabel>
    <relationshipName>MSA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/fields/MSA_Status__c.field-meta.xml
<CustomField>
    <fullName>MSA_Status__c</fullName>
    <description>To track the status of MSA</description>
    <label>MSA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Negotiation</fullName>
                <default>true</default>
                <label>In Negotiation</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/MSA_Software_Discount_Tier_Price__c.object-meta.xml
<CustomObject>
    <label>MSA Software Discount Tier Price</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>MSA Software Discount Tier Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Software Discount Tier Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Create_MSA_Software_Discount_Tier_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Cross_Orders__c.field-meta.xml
<CustomField>
    <fullName>Cross_Orders__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Consider Active MW</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/MSA_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSA_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSA Contract</label>
    <referenceTo>MSA_Contract__c</referenceTo>
    <relationshipLabel>MSA Software Discount Tier Prices</relationshipLabel>
    <relationshipName>MSA_Software_Discount_Tier_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>MSA Software Discount Tier Prices</relationshipLabel>
    <relationshipName>MSA_Software_Discount_Tier_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Product_Services__c.field-meta.xml
<CustomField>
    <fullName>Product_Services__c</fullName>
    <label>Product Services</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Services</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Class</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>&quot;Software</fullName>
                <isActive>false</isActive>
                <label>&quot;Software</label>
            </value>
            <value>
                <fullName>Professional Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Professional Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Pro</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
            </value>
            <value>
                <fullName>Add-ons</fullName>
            </value>
            <value>
                <fullName>Breeze Development</fullName>
            </value>
            <value>
                <fullName>Core Lite</fullName>
            </value>
            <value>
                <fullName>Ekho</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>&quot;Core</fullName>
                <isActive>false</isActive>
                <label>&quot;Core</label>
            </value>
            <value>
                <fullName>Edge Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Edge Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Services__c.field-meta.xml
<CustomField>
    <fullName>Product_Services__c</fullName>
    <label>Product Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Customization</fullName>
            </value>
            <value>
                <fullName>Consulting/Other</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hydro</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Other Renewable</fullName>
    </customValue>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Wind</fullName>
    </customValue>
    <customValue>
        <fullName>All Renewables (Agnostic)</fullName>
    </customValue>
    <masterLabel>Asset Class</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Product_Services.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Implementation</fullName>
    </customValue>
    <customValue>
        <fullName>Customization</fullName>
    </customValue>
    <customValue>
        <fullName>Consulting/Other</fullName>
    </customValue>
    <customValue>
        <fullName>Maintenance</fullName>
    </customValue>
    <customValue>
        <fullName>N/A</fullName>
    </customValue>
    <customValue>
        <fullName>Edge Services</fullName>
    </customValue>
    <masterLabel>Product Services</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SaaS</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Recurring</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/SoftwareDiscountTierTest.cls
@isTest
private class SoftwareDiscountTierTest{

    @testSetup 
    static void generatedata() {
    
        Pricebook2 priceBook= new Pricebook2 (Name = 'Standard Price Book');
        insert priceBook;
        
        Account acc = new Account(Name='TestCP',
                                Account_Price_Book__c = priceBook.Id);
        insert acc;

        
        MSA_Contract__c msa = new MSA_Contract__c(Account_Name__c = acc.Id ,
                                                MSA_Status__c = 'In Negotiation',
                                                CurrencyIsoCode = 'USD');                               
        insert msa;
        
        
        
        Product2 product = new Product2(Name = 'Drive O&M', 
                                    Product_Line__c = 'Core', 
                                    ProductCode = 'GB-AD-PS-OT-IM-WD-ST-EWT',
                                    Product_Category__c = 'Software',
                                    Product_Type__c = 'SaaS',
                                    Product_Services__c = 'N/A',
                                    QuantityUnitOfMeasure = 'MWp',
                                    Asset_Class__c = 'Solar'
                                    );
        insert product;
        
        MSA_Software_Discount_Tier_Price__c softPrice = new MSA_Software_Discount_Tier_Price__c(Account__c = acc.Id,
                                        Product__c = product.Id,  
                                        MSA_Contract__c = msa.Id);
                                        //Cross_Orders__c = ,
                                        //Lower_Bound__c = ,
                                        //Upper_Bound__c = ,
                                        //Discount_Amount__c
                                        //Product_List_Price__c = 24, 
                                        //SBQQ__Price__c = 25,
                                        //Same_As_List_Price__c = FALSE);
        insert softPrice;
        }
        
        
        @isTest static void fetchAccountNameTest() {
            Test.startTest();
            List<MSA_Contract__c> msaId = [Select Id from MSA_Contract__c where Account_Name__r.Name = 'TestCP' LIMIT 1];
            Id msa = string.valueOf(msaId[0].Id);
            System.debug('MSA Id : ' + msa);
            List<MSA_Contract__c> accName = SoftwareDiscountTier.fetchAccountName(msa);
            String accountName = string.valueOf(accName[0].Account_Name__r.Name);
            System.debug('Account Name : ' + accountName);
            Test.stopTest();
            System.assertEquals('TestCP', accountName );
        }
        
        
        @isTest static void fetchCurrencyTest() {
            Test.startTest();
            List<MSA_Contract__c> msaId = [Select Id from MSA_Contract__c where Account_Name__r.Name = 'TestCP' LIMIT 1];
            Id msa = string.valueOf(msaId[0].Id);
            System.debug('MSA Id : ' + msa);
            List<MSA_Contract__c> curr = SoftwareDiscountTier.fetchCurrency(msa);
            String currencyName = string.valueOf(curr[0].CurrencyIsoCode);
            System.debug('Currency Name : ' + currencyName);
            Test.stopTest();
            System.assertEquals('USD', currencyName);
        }
        
        
        @isTest static void fetchSoftwareListPriceDataTest() {
            Test.startTest();
            List<MSA_Contract__c> msaId = [Select Id from MSA_Contract__c where Account_Name__r.Name = 'TestCP' LIMIT 1];
            Id msa = string.valueOf(msaId[0].Id);
            System.debug('MSA Id : ' + msa);
            List<MSA_Software_Discount_Tier_Price__c> softwareList = SoftwareDiscountTier.fetchSoftwareListPriceData(msa);
            Test.stopTest();
            System.assert(softwareList.size()>0);
        }
        
        
        @isTest static void deleteSoftwarePriceRecordTest() {
            Test.startTest();
            List<MSA_Contract__c> msaId = [Select Id from MSA_Contract__c where Account_Name__r.Name = 'TestCP' LIMIT 1];
            Id msa = string.valueOf(msaId[0].Id);
            System.debug('MSA Id : ' + msa);
            List<MSA_Software_Discount_Tier_Price__c> softwareList = SoftwareDiscountTier.fetchSoftwareListPriceData(msa);
            SoftwareDiscountTier.deleteSoftwarePriceRecord(softwareList,msa);
            Test.stopTest();
        }

}