unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Account_Plant__c/Account_Plant__c.object-meta.xml
<CustomObject>
    <description>Junction object between Account and Plant</description>
    <label>Account Plant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Account Plant Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Account Plant</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Account_Plant__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Account Plant</relationshipLabel>
    <relationshipName>Account_Plant</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Customer_Plant_Asset_ID__c.field-meta.xml
<CustomField>
    <fullName>Customer_Plant_Asset_ID__c</fullName>
    <label>Customer Plant Asset ID</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Latitude__c.field-meta.xml
<CustomField>
    <fullName>Latitude__c</fullName>
    <formula>Plant__r.Latitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Latitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Longitude__c.field-meta.xml
<CustomField>
    <fullName>Longitude__c</fullName>
    <formula>Plant__r.Longitude__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Longitude</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/PF_Service_Product__c.field-meta.xml
<CustomField>
    <fullName>PF_Service_Product__c</fullName>
    <label>PF Service Product</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
                <default>true</default>
                <label>Drive</label>
            </value>
            <value>
                <fullName>Drive Pro</fullName>
            </value>
            <value>
                <fullName>FSM</fullName>
            </value>
            <value>
                <fullName>Asset Build</fullName>
            </value>
            <value>
                <fullName>API</fullName>
                <isActive>false</isActive>
                <label>API</label>
            </value>
            <value>
                <fullName>Advanced Analytics</fullName>
                <isActive>false</isActive>
                <label>Advanced Analytics</label>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
                <isActive>false</isActive>
                <label>Bluepoint</label>
            </value>
            <value>
                <fullName>Data Pipe</fullName>
                <isActive>false</isActive>
                <label>Data Pipe</label>
            </value>
            <value>
                <fullName>Edge Services</fullName>
                <isActive>false</isActive>
                <label>Edge Services</label>
            </value>
            <value>
                <fullName>Greenbyte</fullName>
                <isActive>false</isActive>
                <label>Greenbyte</label>
            </value>
            <value>
                <fullName>Other</fullName>
                <isActive>false</isActive>
                <label>Other</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Plant_Name__c.field-meta.xml
<CustomField>
    <fullName>Plant_Name__c</fullName>
    <formula>Plant__r.Plant_Name__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Plant Name</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Project_Lifecycle_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Lifecycle_Status__c</fullName>
    <label>Project Lifecycle Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>Documentation Review</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/Renewable_Type__c.field-meta.xml
<CustomField>
    <fullName>Renewable_Type__c</fullName>
    <formula>TEXT(Plant__r.Renewable_Type__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Renewable Type</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Account_Plant__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Account Plants</relationshipLabel>
    <relationshipName>Account_Plants</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/AssetBuilderLocationAPITest.cls
/**
 * 
 */
@IsTest
public class AssetBuilderLocationAPITest {
/*
    @IsTest
    static void testCalloutSuccessMethod() {

        Id customerPlantAssetRT = Utils.getRecordTypeInfo('Account_Plant__c', 'Child_Asset').getRecordTypeId();

        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;

        Account account = new Account(Name = 'Test Account');
        insert account;

        Account_Plant__c pa = new Account_Plant__c();
        pa.Name = 'Plant Asset Test1';
        pa.RecordTypeId = [SELECT id from RecordType where Name = 'Parent Asset'].Id;
//        pa.Plant_Name__c = 'test1';
//        pa.Renewable_Type__c = Constants.WIND;
        pa.Project_Lifecycle_Status__c = 'Pending';
//        pa.Implementation_Status__c = 'Pending Customer Submission';
//        pa.Latitude__c = '45.5017';
//       pa.Longitude__c = '-73.5673';
        pa.Account__c = account.Id;
        insert pa;

        Account_Plant__c plantAsset = new Account_Plant__c();
//        plantAsset.Name = 'Test Plant';
//        plantAsset.Renewable_Type__c = 'Solar - PV';
        plantAsset.PF_Service_Product__c = 'Drive';
        plantAsset.Customer_Plant_Asset_ID__c = '7777.77.777';
        plantAsset.TEM_Version__c = newTemVersion.id;
        plantAsset.RecordTypeId = customerPlantAssetRT;
//        plantAsset.Parent__c = pa.Id;
//        plantAsset.Latitude__c = '45.5017';
//        plantAsset.Longitude__c = '-73.5673';
        plantAsset.Account__c = account.Id;

        insert plantAsset;

        String bodyContent = '{"LOCATION_ELEVATION":"28.48959","LOCATION_COUNTRY":"CA","LOCATION_STATE":"QC","LOCATION_TIMEZONE":"Eastern Standard Time"}';
//        Test.setMock(HttpCalloutMock.class, new ImplementationWizardFormMock(bodyContent, 200));

        Test.startTest();

        Plant_Asset_Prompt_Detail__c plantAssetPD = new Plant_Asset_Prompt_Detail__c();
        AssetBuilderLocationAPI.callLocationAPI(plantAsset.Id,plantAssetPD,false, true);

        Test.stopTest();
    }

    @IsTest
    static void testCalloutErrorMethod() {
        Id customerPlantAssetRT = Utils.getRecordTypeInfo('Account_Plant__c', 'Child_Asset').getRecordTypeId();

        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;

        Account account = new Account(Name = 'Test Account');
        insert account;

        Account_Plant__c pa = new Account_Plant__c();
        pa.Name = 'Plant Asset Test1';
        pa.RecordTypeId = [SELECT id from RecordType where Name = 'Parent Asset'].Id;
        pa.Plant_Name__c = 'test1';
        pa.Renewable_Type__c = Constants.WIND;
        pa.Project_Lifecycle_Status__c = 'Pending';
//        pa.Implementation_Status__c = 'Pending Customer Submission';
        pa.Latitude__c = '45.5017';
        pa.Longitude__c = '-73.5673';
        pa.Account__c = account.Id;
        insert pa;

        Account_Plant__c plantAsset = new Account_Plant__c();
        plantAsset.Name = 'Test Plant';
        plantAsset.Renewable_Type__c = 'Solar - PV';
        plantAsset.PF_Service_Product__c = 'Drive';
        plantAsset.Customer_Plant_Asset_ID__c = '7777.77.777';
        plantAsset.TEM_Version__c = newTemVersion.id;
        plantAsset.RecordTypeId = customerPlantAssetRT;
        plantAsset.Parent__c = pa.Id;
        plantAsset.Latitude__c = '45.5017';
        plantAsset.Longitude__c = '-73.5673';
        plantAsset.Account__c = account.Id;

        insert plantAsset;

        String bodyContent = '{"LOCATION_ELEVATION":"28.48959","LOCATION_COUNTRY":"CA","LOCATION_STATE":"QC","LOCATION_TIMEZONE":"Eastern Standard Time"}';
        Test.setMock(HttpCalloutMock.class, new ImplementationWizardFormMock(bodyContent, 500));

        Test.startTest();
        Plant_Asset_Prompt_Detail__c plantAssetPD = new Plant_Asset_Prompt_Detail__c();
        AssetBuilderLocationAPI.callLocationAPI(plantAsset.Id,plantAssetPD,false, true);
        Test.stopTest();
    }

    @IsTest
    static void testCalloutExceptionMethod() {
        Id customerPlantAssetRT = Utils.getRecordTypeInfo('Account_Plant__c', 'Child_Asset').getRecordTypeId();

        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;

        Account account = new Account(Name = 'Test Account');
        insert account;

        Account_Plant__c pa = new Account_Plant__c();
        pa.Name = 'Plant Asset Test1';
        pa.RecordTypeId = [SELECT id from RecordType where Name = 'Parent Asset'].Id;
        pa.Plant_Name__c = 'test1';
        pa.Renewable_Type__c = Constants.WIND;
        pa.Project_Lifecycle_Status__c = 'Pending';
//        pa.Implementation_Status__c = 'Pending Customer Submission';
        pa.Latitude__c = '45.5017';
        pa.Longitude__c = '-73.5673';
        pa.Account__c = account.Id;
        insert pa;

        Account_Plant__c plantAsset = new Account_Plant__c();
        plantAsset.Name = 'Test Plant';
        plantAsset.Renewable_Type__c = 'Solar - PV';
        plantAsset.PF_Service_Product__c = 'Drive';
        plantAsset.Customer_Plant_Asset_ID__c = '7777.77.777';
        plantAsset.TEM_Version__c = newTemVersion.id;
        plantAsset.RecordTypeId = customerPlantAssetRT;
        plantAsset.Parent__c = pa.Id;
        plantAsset.Latitude__c = '45.5017';
        plantAsset.Longitude__c = '-73.5673';
        plantAsset.Account__c = account.Id;

        insert plantAsset;

        Test.startTest();
        Plant_Asset_Prompt_Detail__c plantAssetPD = new Plant_Asset_Prompt_Detail__c();
        AssetBuilderLocationAPI.callLocationAPI(plantAsset.Id,plantAssetPD,false, true);
        Test.stopTest();
    }

    @IsTest
    static void testLWCMethod() {
        Id customerPlantAssetRT = Utils.getRecordTypeInfo('Account_Plant__c', 'Child_Asset').getRecordTypeId();

        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;

        Account account = new Account(Name = 'Test Account');
        insert account;

        Account_Plant__c pa = new Account_Plant__c();
        pa.Name = 'Plant Asset Test1';
        pa.RecordTypeId = [SELECT id from RecordType where Name = 'Parent Asset'].Id;
        pa.Plant_Name__c = 'test1';
        pa.Renewable_Type__c = Constants.WIND;
        pa.Project_Lifecycle_Status__c = 'Pending';
//        pa.Implementation_Status__c = 'Pending Customer Submission';
        pa.Latitude__c = '45.5017';
        pa.Longitude__c = '-73.5673';
        pa.Account__c = account.Id;
        insert pa;

        Account_Plant__c plantAsset = new Account_Plant__c();
        plantAsset.Name = 'Test Plant';
        plantAsset.Renewable_Type__c = 'Solar - PV';
        plantAsset.PF_Service_Product__c = 'Drive';
        plantAsset.Customer_Plant_Asset_ID__c = '7777.77.777';
        plantAsset.TEM_Version__c = newTemVersion.id;
        plantAsset.RecordTypeId = customerPlantAssetRT;
        plantAsset.Parent__c = pa.Id;
        plantAsset.Latitude__c = '45.5017';
        plantAsset.Longitude__c = '-73.5673';
        plantAsset.Account__c = account.Id;

        insert plantAsset;

        Test.startTest();
        AssetBuilderLocationAPI.callLocationAPIfromLWC(plantAsset.Id, true);
        Test.stopTest();
    }*/
}