unpackaged/main/default/objects/Account/recordTypes/Customer.recordType-meta.xml
<RecordType>
    <fullName>Customer</fullName>
    <active>true</active>
    <label>Customer</label>
</RecordType>

unpackaged/main/default/objects/Opportunity/fields/QS_Order_Type__c.field-meta.xml
<CustomField>
    <fullName>QS_Order_Type__c</fullName>
    <description>An additional deal type classification. This is where Sales clarifies whether this is New Product, Renewal, Decommission, etc.</description>
    <inlineHelpText>An additional deal type classification. Clarifies whether this is New Product, Renewal, Decommission, etc.</inlineHelpText>
    <label>Order Type</label>
    <type>Picklist</type>
    <valueSet>
        <controllingField>Type</controllingField>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>AddOn</fullName>
            </value>
            <value>
                <fullName>Migration</fullName>
            </value>
            <value>
                <fullName>Services Only</fullName>
            </value>
            <value>
                <fullName>Change Order</fullName>
            </value>
            <value>
                <fullName>Subscription Renewal</fullName>
            </value>
            <value>
                <fullName>Decommission</fullName>
            </value>
            <value>
                <fullName>Contract Renewal</fullName>
            </value>
            <value>
                <fullName>Overage</fullName>
            </value>
            <value>
                <fullName>Debooking</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/fields/QS_Sales_Forecast_Category__c.field-meta.xml
<CustomField>
    <fullName>QS_Sales_Forecast_Category__c</fullName>
    <description>Indicates Sales&#39;s estimate of the forecast category and may differ from Manager Forecast Category.</description>
    <inlineHelpText>The forecast status of the opportunity as noted by the sales person.</inlineHelpText>
    <label>Sales Forecast Category</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>4 - Omitted</fullName>
            </value>
            <value>
                <fullName>3 - Pipeline</fullName>
            </value>
            <value>
                <fullName>2 - Best Case</fullName>
            </value>
            <value>
                <fullName>1 - Commit</fullName>
            </value>
            <value>
                <fullName>0 - Closed Won</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Opportunity/recordTypes/Renewal.recordType-meta.xml
<RecordType>
    <fullName>Renewal</fullName>
    <active>true</active>
    <businessProcess>Amend And Renewal Process</businessProcess>
    <label>Renewal</label>
</RecordType>

unpackaged/main/default/objects/Product2/fields/Asset_Class__c.field-meta.xml
<CustomField>
    <fullName>Asset_Class__c</fullName>
    <label>Asset Class</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Asset_Class</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>&quot;Software</fullName>
                <isActive>false</isActive>
                <label>&quot;Software</label>
            </value>
            <value>
                <fullName>Professional Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Professional Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Pro</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
            </value>
            <value>
                <fullName>Add-ons</fullName>
            </value>
            <value>
                <fullName>Breeze Development</fullName>
            </value>
            <value>
                <fullName>Core Lite</fullName>
            </value>
            <value>
                <fullName>Ekho</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>&quot;Core</fullName>
                <isActive>false</isActive>
                <label>&quot;Core</label>
            </value>
            <value>
                <fullName>Edge Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Edge Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Services__c.field-meta.xml
<CustomField>
    <fullName>Product_Services__c</fullName>
    <label>Product Services</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Implementation</fullName>
            </value>
            <value>
                <fullName>Customization</fullName>
            </value>
            <value>
                <fullName>Consulting/Other</fullName>
            </value>
            <value>
                <fullName>Maintenance</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Type__c.field-meta.xml
<CustomField>
    <fullName>Product_Type__c</fullName>
    <label>Product Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Product_Type</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/QS_Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>A summarization of the customer&#39;s currently-owned products.</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Customer Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Account__c.field-meta.xml
<CustomField>
    <fullName>QS_Account__c</fullName>
    <description>Indicates the account that is primarily associated with the customer asset. This is the account that purchased the product.</description>
    <inlineHelpText>Indicates the account that is primarily associated with the customer asset. This is the account that purchased the product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QS_Customer_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_End_Date__c</fullName>
    <description>Roll-up field displaying the latest end date amongst all the CATs. This field changes as products are added or renewed.</description>
    <inlineHelpText>Roll-up field displaying the latest end date amongst all the CATs. This field changes as products are added or renewed.</inlineHelpText>
    <label>End Date</label>
    <summarizedField>QS_Customer_Asset_Detail__c.QS_End_Date__c</summarizedField>
    <summaryForeignKey>QS_Customer_Asset_Detail__c.QS_Customer_Asset__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Product__c.field-meta.xml
<CustomField>
    <fullName>QS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product this customer asset represents. Customer asset records are created when the product field Generate Customer Asset = true.</description>
    <inlineHelpText>The product this customer asset represents. Customer asset records are created when the product field Generate Customer Asset = true.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>QS_Customer_Assets</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_Start_Date__c</fullName>
    <description>Roll-up field displaying the earliest start date of all Customer Asset Transactions for this product. This field shows when the customer first purchased the product. This date never changes. Start Date must be populated on at least one CAT.</description>
    <inlineHelpText>Roll-up field displaying the earliest start date of all Customer Asset Transactions for this product. This field shows when the customer first purchased the product. This date never changes. Start Date must be populated on at least one CAT.</inlineHelpText>
    <label>Start Date</label>
    <summarizedField>QS_Customer_Asset_Detail__c.QS_Start_Date__c</summarizedField>
    <summaryForeignKey>QS_Customer_Asset_Detail__c.QS_Customer_Asset__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/QS_Customer_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>Transnational detail that feeds the Customer Assets
		Start/End Dates, ARR</description>
    <label>Subscription Transaction</label>
    <nameField>
        <displayFormat>CAT-{0000000}</displayFormat>
        <label>Subscription Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Account__c.field-meta.xml
<CustomField>
    <fullName>QS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer who owns the product.</description>
    <inlineHelpText>The customer who owns the product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Asset_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Contract__c.field-meta.xml
<CustomField>
    <fullName>QS_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The Contract from which the source subscription originated. This field will be blank if the CAT is generated from an Asset (Non-Recurring Product) as those are not related to Contracts, only Accounts.</description>
    <inlineHelpText>The Contract from which the source subscription originated. This field will be blank if the CAT is generated from an Asset (Non-Recurring Product) as those are not related to Contracts, only Accounts.</inlineHelpText>
    <label>Contract</label>
    <referenceTo>Contract</referenceTo>
    <relationshipName>QS_Customer_Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Currently_Active__c.field-meta.xml
<CustomField>
    <fullName>QS_Currently_Active__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Indicates that the start date of the CAT is in the today or passed and the end date is today in the future.</description>
    <inlineHelpText>Indicates that the start date of the CAT is in the today or passed and the end date is today in the future.</inlineHelpText>
    <label>Currently Active</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Customer_Asset__c.field-meta.xml
<CustomField>
    <fullName>QS_Customer_Asset__c</fullName>
    <description>Master-Detail lookup to the parent Customer Asset record.</description>
    <inlineHelpText>Master-Detail lookup to the parent Customer Asset record.</inlineHelpText>
    <label>Customer Asset</label>
    <referenceTo>QS_Customer_Asset__c</referenceTo>
    <relationshipName>QS_Customer_Asset_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_End_Date__c</fullName>
    <description>The End Date of the source Subscription. This is blank when the CAP source is an Asset (non-recurring product).</description>
    <inlineHelpText>The End Date of the source Subscription. This is blank when the CAP source is an Asset (non-recurring product).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Product__c.field-meta.xml
<CustomField>
    <fullName>QS_Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The product this CAT represents.</description>
    <inlineHelpText>The product this CAT represents.</inlineHelpText>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipName>QS_Customer_Asset_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_Start_Date__c</fullName>
    <description>The start date from the source Quote Line for this CAT.</description>
    <inlineHelpText>The start date from the source Quote Line for this CAT.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/globalValueSets/Asset_Class.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Hydro</fullName>
    </customValue>
    <customValue>
        <fullName>Industrial</fullName>
    </customValue>
    <customValue>
        <fullName>Other Renewable</fullName>
    </customValue>
    <customValue>
        <fullName>Solar</fullName>
    </customValue>
    <customValue>
        <fullName>Storage</fullName>
    </customValue>
    <customValue>
        <fullName>Wind</fullName>
    </customValue>
    <customValue>
        <fullName>All Renewables (Agnostic)</fullName>
    </customValue>
    <masterLabel>Asset Class</masterLabel>
</GlobalValueSet>

unpackaged/main/default/globalValueSets/Product_Type.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SaaS</fullName>
    </customValue>
    <customValue>
        <fullName>Perpetual License</fullName>
    </customValue>
    <customValue>
        <fullName>Recurring</fullName>
    </customValue>
    <customValue>
        <fullName>One-Time</fullName>
    </customValue>
    <masterLabel>Product Type</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/CA2_CustomerAssetDetailTriggerHdlTest.cls
@isTest
private class CA2_CustomerAssetDetailTriggerHdlTest {
        @isTest static void CA2_CustomerAssetDetailTriggerHandlerTest() {
        
       Account account = new Account();
        account.Name = 'Test acctName';
        account.BillingCountry = 'United States';
        insert account;
        
        // Create a product record
        List<Product2> productList = new List<Product2>();       
        
        Product2 product1 = new Product2();
        product1.ProductCode = 'product-2';
        product1.Name = 'Hardware Product 2';
        product1.Description = 'Hardware Product 2 Description';
        product1.Family = 'HardwareFamily';
        product1.QS_Generate_Asset__c = true;
        product1.IsActive = true;
        product1.SBQQ__SubscriptionPricing__c = 'Percent Of Total';
        product1.SBQQ__SubscriptionType__c = 'Renewable';
        product1.SBQQ__SubscriptionTerm__c = 12;
        product1.SBQQ__QuantityEditable__c = true;
        product1.SBQQ__IncludeInMaintenance__c = true;
            product1.Product_Line__c = 'Core'; 
        product1.Product_Category__c = 'Software';
        product1.Product_Type__c = 'SaaS';
        product1.Product_Services__c = 'N/A';
        
       product1.Asset_Class__c = 'Solar';
        productList.add(product1);

        insert  productList; 

        Test.startTest();
          QS_Customer_Asset__c ca = new QS_Customer_Asset__c(QS_Account__c = account.Id);
        insert ca; 
        
        // Insert a Customer Asset Detail with an OLD Start Date and FUTURE End Date
        QS_Customer_Asset_Detail__c cad = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-365),QS_End_Date__c = System.today().addDays(+5));
        insert cad; 
        CA2_CustomerAssetUtil.Create_CA_On_Update = true;
            
        cad.QS_Start_Date__c = System.today().addDays(-100);
        cad.QS_End_Date__c = System.today().addDays(110);
        update cad;   
            
            
        cad.QS_End_Date__c = System.today().addDays(-10);
        update cad;    
        
        cad.QS_Start_Date__c = System.today().addDays(100);
        cad.QS_End_Date__c = System.today().addDays(110);
        update cad;      
            
        cad.QS_End_Date__c = null;
        update cad;       
       
    }
    
    @isTest static void CA2_CustomerAssetDetailStatusbatchableTest() {
        
       Account account = new Account();
        account.Name = 'Test acctName';
        account.BillingCountry = 'United States';
        insert account;
        
        // Create a product record
        List<Product2> productList = new List<Product2>();       
        Product2 product = new Product2();
        product.ProductCode = 'product-2';
        product.Name = 'Hardware Product 2';
        product.Description = 'Hardware Product 2 Description';
        product.Family = 'HardwareFamily';
        product.QS_Generate_Asset__c = true;
        product.IsActive = true;
        product.Product_Line__c = 'Core'; 
        product.Product_Category__c = 'Software';
        product.Product_Type__c = 'SaaS';
        product.Product_Services__c = 'N/A';
        
       product.Asset_Class__c = 'Solar';
        product.SBQQ__SubscriptionPricing__c = 'Percent Of Total';
        product.SBQQ__SubscriptionType__c = 'Renewable';
        product.SBQQ__SubscriptionTerm__c = 12;
        product.SBQQ__QuantityEditable__c = true;
        product.SBQQ__IncludeInMaintenance__c = true;
        productList.add(product);
        
        
        Product2 product1 = new Product2();
        product1.ProductCode = 'product-2';
        product1.Name = 'Hardware Product 2';
        product1.Description = 'Hardware Product 2 Description';
        product1.Family = 'HardwareFamily';
        product1.QS_Generate_Asset__c = true;
        product1.IsActive = true;
        product1.SBQQ__SubscriptionPricing__c = 'Percent Of Total';
        product1.SBQQ__SubscriptionType__c = 'Renewable';
        product1.SBQQ__SubscriptionTerm__c = 12;
        product1.SBQQ__QuantityEditable__c = true;
        product1.Product_Line__c = 'Core'; 
        product1.Product_Category__c = 'Software';
        product1.Product_Type__c = 'SaaS';
        product1.Product_Services__c = 'N/A';
        
       product1.Asset_Class__c = 'Solar';
        product1.SBQQ__IncludeInMaintenance__c = true;
        productList.add(product1);
        
        
        Product2 product2 = new Product2();
        product2.ProductCode = 'product-3';
        product2.Name = 'Hardware Product 3';
        product2.Description = 'Hardware Product 3 Description';
        product2.Family = 'HardwareFamily';
        product2.QS_Generate_Asset__c = true;
        product2.IsActive = true;
        product2.SBQQ__SubscriptionPricing__c = 'Percent Of Total';
        product2.SBQQ__SubscriptionType__c = 'Renewable';
        product2.SBQQ__SubscriptionTerm__c = 12;
        product2.SBQQ__QuantityEditable__c = true;
        product2.SBQQ__IncludeInMaintenance__c = true;
        product2.Product_Line__c = 'Core'; 
        product2.Product_Category__c = 'Software';
        product2.Product_Type__c = 'SaaS';
        product2.Product_Services__c = 'N/A';
        
       product2.Asset_Class__c = 'Solar';
        productList.add(product2);

        insert  productList; 
        //===========================================
        Opportunity newOPp = new Opportunity();
        newOPp.Name = 'Test Opp';
        newOPp.AccountId = account.Id;
        newOpp.StageName = '00 - MQL';
        newOpp.CloseDate = Date.today();
        newOpp.QS_Sales_Forecast_Category__c = 'Commit';
        newOpp.QS_Order_Type__c = 'Commit';
        newOpp.Type ='New';
        newOpp.QS_Order_Type__c = 'New Customer';
        insert newOPp;
        
        
        Opportunity closeLostRenewalOpp = new Opportunity();
        closeLostRenewalOpp.Name = 'Test Opp';
        closeLostRenewalOpp.AccountId = account.Id;
        closeLostRenewalOpp.StageName = '00 - MQL';
        closeLostRenewalOpp.CloseDate = Date.today();
        closeLostRenewalOpp.QS_Sales_Forecast_Category__c = 'Commit';
        closeLostRenewalOpp.QS_Order_Type__c = 'Commit';
        closeLostRenewalOpp.Type ='Existing Customer';
        closeLostRenewalOpp.QS_Order_Type__c = 'Subscription Renewal';
        insert closeLostRenewalOpp;
        
        Contract cont = new Contract();
        cont.AccountId = account.Id;
        cont.SBQQ__Opportunity__c = newOPp.Id;
        cont.SBQQ__RenewalOpportunity__c = closeLostRenewalOpp.Id;
        cont.StartDate = Date.today().addDays(-380);
        cont.ContractTerm = 12;
        insert cont;
        
            
        //====================================================
        QS_Customer_Asset__c ca = new QS_Customer_Asset__c(QS_Account__c = account.Id);
        insert ca; 
        
        // Insert a Customer Asset Detail with an OLD Start Date and FUTURE End Date
        List<QS_Customer_Asset_Detail__c> lstCadToInsert = new List<QS_Customer_Asset_Detail__c>();
        QS_Customer_Asset_Detail__c cad = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-365),QS_End_Date__c = System.today().addDays(-10));
        lstCadToInsert.add(cad);
        
        QS_Customer_Asset_Detail__c cad1 = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[0].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-365),QS_End_Date__c = System.today().addDays(+10));
        lstCadToInsert.add(cad1);
        
        QS_Customer_Asset_Detail__c cad2 = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[1].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-30),QS_End_Date__c = System.today().addDays(+15));
        lstCadToInsert.add(cad2);
        
        
        QS_Customer_Asset_Detail__c cad3 = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[2].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-30),QS_End_Date__c = System.today().addDays(+15));
        lstCadToInsert.add(cad3);
        
        QS_Customer_Asset_Detail__c cad4 = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[2].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-30),QS_End_Date__c = System.today().addDays(+15));
        lstCadToInsert.add(cad4);
        
        QS_Customer_Asset_Detail__c cadWithRenewal = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[2].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today(),QS_End_Date__c = System.today().addDays(-16));
        cadWithRenewal.QS_Contract__c = cont.Id;                
        lstCadToInsert.add(cadWithRenewal);
        QS_Customer_Asset_Detail__c cadReducedCurrent = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[2].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-30),QS_End_Date__c = System.today().addDays(+15));
        lstCadToInsert.add(cadReducedCurrent);
        
        QS_Customer_Asset_Detail__c cadReducedExpired = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[2].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-90),QS_End_Date__c = System.today().addDays(-35));
        lstCadToInsert.add(cadReducedExpired);
        
        QS_Customer_Asset_Detail__c cadPendingRenewal = new QS_Customer_Asset_Detail__c(QS_Customer_Asset__c = ca.id,QS_Product__c = productList[1].id, QS_Currently_Active__c=False,QS_Start_Date__c = System.today().addDays(-30),QS_End_Date__c = System.today().addDays(+15));
        cadPendingRenewal.QS_Contract__c = cont.Id;
        lstCadToInsert.add(cadPendingRenewal);
        insert lstCadToInsert; 
        
       
       
         DateTime future = system.now().addMinutes(1);
        Integer year = future.year();
        Integer month = future.month();
        Integer day = future.day();
        Integer hour = future.hour();
        Integer minute = future.minute();
        Integer second = future.second();
         String cron_exp = second + ' ' + minute + ' ' + hour + ' ' + day + ' ' + month + ' ?' + ' ' + year;            

        Test.startTest();

        // Create an instance of CA2_CustomerAssetDetailStatusbatchable
        CA2_CustomerAssetDetailStatusSchedule scheduler = new CA2_CustomerAssetDetailStatusSchedule();

        // Schedule the job using System's scheduler
        String jobId = System.schedule('testBasicScheduledApex', cron_exp, scheduler);
        
        // Get the information from the CronTrigger API object
        CronTrigger ct = [SELECT Id, CronExpression, TimesTriggered, 
                          NextFireTime
                          FROM CronTrigger WHERE id = :jobId];
        
        // Verify the expressions are the same
        System.assertEquals(cron_exp, ct.CronExpression);
        
        // Verify the job has not run
        System.assertEquals(0, ct.TimesTriggered);

        // Force scheduler execution
        //scheduler.execute(null);
        
       // cad.QS_End_Date__c = 
        Test.stopTest();
    }  
}