unpackaged/main/default/objects/Attribute_Master__c/Attribute_Master__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute Master</label>
    <nameField>
        <label>Attribute Master Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Masters</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Master__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Master__c/fields/Data_Type__c.field-meta.xml
<CustomField>
    <fullName>Data_Type__c</fullName>
    <label>Data Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Decimal</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/Attribute_Value__c.object-meta.xml
<CustomObject>
    <label>Attribute Value</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Value__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute</label>
    <referenceTo>Core_Attribute__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Site_Metadata__c</fullName>
    <label>Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Attribute__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Alias is the attribute display name which will be shown in lightning web components</description>
    <inlineHelpText>Alias is the attribute display name which will be shown in lightning web components</inlineHelpText>
    <label>Alias</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Attribute_Master__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Master__c</fullName>
    <label>Attribute Master</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Attribute_Master__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Attribute_Master__c</referenceTo>
    <relationshipLabel>Core Atributes</relationshipLabel>
    <relationshipName>Core_Atributes</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Base_Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link the attributes to the relevant Base Asset</description>
    <label>Base Asset Name</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Last_Attr_Value_Process_Initiated_DT__c.field-meta.xml
<CustomField>
    <fullName>Last_Attr_Value_Process_Initiated_DT__c</fullName>
    <label>Last Attr Value Process Initiated DT</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Prompt Name Alias</description>
    <label>Alias</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Attribute_Info__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Info__c</fullName>
    <label>Attribute Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <formula>Plant_Asset_Prompt_Detail__r.Is_Deleted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Specific_Info__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Specific_Info__c</fullName>
    <label>Prompt Specific Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/classes/AttributeValueObjDataHandler.cls
/**
 * TODO - Calls from SiteMetaDataHandler when Site Metadata is created or updated.
 * Create or update Attribute Value against Site Metadata for particular Plant Asset.
 */
public with Sharing class AttributeValueObjDataHandler {
    public DateTime lastPromptInitiatedId;
    public String plantAssetId;
    public String plantAssetPromptDetail;
    /*
    * Attribute Value is created based on the Attribute in Base Asset Template from Site Metadata. 
    * @param {List<Id>} siteMetaDataIdLst - List of Site Metadata need for creation or updation of Attribute Value.
    * @param {DateTime} lastPromptInitiatedId - Initiated date and time for track the execution process.
    * @param {String} plantAssetPromptDetail - Track updates of Attribute value Creation/Updation against Plant Asset.
    * @param {String} plantAssetId - Attribute Value against Plant Asset
    */
    public static void createOrUpdateAttrValueRecs(List<Id> siteMetaDataIdLst, DateTime lastPromptInitiatedId, 
        String plantAssetPromptDetail, String plantAssetId){
        Plant_Asset_Prompt_Detail__c pltAstPrtDtl = [SELECT Id, Name, Last_Attr_Value_Process_Initiated_DT__c 
                    FROM Plant_Asset_Prompt_Detail__c 
                    WHERE Id =: plantAssetPromptDetail AND Is_Deleted__c = FALSE];
        try{
            lastPromptInitiatedId = lastPromptInitiatedId;
            plantAssetId = plantAssetId;
            plantAssetPromptDetail = plantAssetPromptDetail;

            Set<Id> baseAssetId = new Set<Id>();
            Set<Id> promptInfoId = new Set<Id>();
            List<Site_Metadata__c> siteMetaData = new List<Site_Metadata__c>();
    		
            for(Site_Metadata__c strInstance : [SELECT Id, Name, Attribute_Info__c, Base_Asset_Template__c, Account_Plant__c, 
                                                Prompt_Specific_Info__c, Prompt_Information__c, Plant_Asset_Prompt_Detail__r.Is_Deleted__c
                                                FROM Site_Metadata__c 
                                                WHERE Id IN: siteMetaDataIdLst AND Plant_Asset_Prompt_Detail__r.Is_Deleted__c = FALSE]){
                baseAssetId.add(strInstance.Base_Asset_Template__c);
                promptInfoId.add(strInstance.Prompt_Information__c);
                siteMetaData.add(strInstance);
            }
            Map<String, Core_Attribute__c> attrNameToAttrInfo = new Map<String, Core_Attribute__c>();
    
            if(baseAssetId.size() > 0){
                for(Core_Attribute__c attrInfo : [SELECT  Id, Alias__c, Base_Asset_Name__c, Attribute_Master__r.Name,
                                                    Attribute_Master__r.Data_Type__c,Default_value__c, Prompt_Information__c
                                                FROM    Core_Attribute__c
                                                WHERE   (Base_Asset_Name__c IN:baseAssetId OR Prompt_Information__c IN:promptInfoId)]){   
                    String attributeUniqueCheck = String.isNotBlank(attrInfo.Base_Asset_Name__c) ? attrInfo.Base_Asset_Name__c+'-'+attrInfo.Attribute_Master__r.Name : attrInfo.Prompt_Information__c+'-'+attrInfo.Attribute_Master__r.Name;
                    attrNameToAttrInfo.put(attributeUniqueCheck, attrInfo);
                } 
            }
    
            List<Attribute_Value__c> attrValueCreateOrUpdateList = new List<Attribute_Value__c>();
            for(Site_Metadata__c siteMetaDataInstance : siteMetaData){
                Map<String,String> coreAttributeInfoMap = 
                            (Map<String, String>) System.JSON.deserialize(siteMetaDataInstance.Attribute_Info__c,Map<String, String>.class);
                Map<String,String> promptSpecificInfoMap = 
                            (Map<String, String>) System.JSON.deserialize(siteMetaDataInstance.Prompt_Specific_Info__c,Map<String, String>.class);     
                for(String attrName : coreAttributeInfoMap.keySet()){
                    //Formed unique value to conform Attribute related to specific Base Asset Template
                    String baseAstNameAttrName = siteMetaDataInstance.Base_Asset_Template__c+'-'+attrName;
                    if(attrNameToAttrInfo.containsKey(baseAstNameAttrName)){
                        Attribute_Value__c attrValue = attributeValueFormation(siteMetaDataInstance, coreAttributeInfoMap, baseAstNameAttrName, attrNameToAttrInfo);
                        attrValueCreateOrUpdateList.add(attrValue);
                    }
                }
                for(String attrName : promptSpecificInfoMap.keySet()){
                    //Formed unique value to conform Attribute related to specific Prompt information
                    String promptInfoNameAttrName = siteMetaDataInstance.Prompt_Information__c+'-'+attrName;
                    if(attrNameToAttrInfo.containsKey(promptInfoNameAttrName)){
                        Attribute_Value__c attrValue = attributeValueFormation(siteMetaDataInstance, promptSpecificInfoMap, promptInfoNameAttrName, attrNameToAttrInfo);
                        attrValueCreateOrUpdateList.add(attrValue);
                    }
                }
            }
            //Update the Plant Asset Prompt Detail to track the creation process
            pltAstPrtDtl.Last_Attr_Value_Process_Initiated_DT__c = lastPromptInitiatedId;
            if(attrValueCreateOrUpdateList.size()>0){
                upsert attrValueCreateOrUpdateList External_ID__c;
                update pltAstPrtDtl;
            }
            
        }catch(Exception exceptionDetails){
            pltAstPrtDtl.Last_Attr_Value_Process_Initiated_DT__c = null;
            System.debug(' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber());
            Error_Log__c errorLogInstance = Utils.catchErrorLogs('createOrUpdateAttrValueRecs',exceptionDetails.getMessage(), 
                exceptionDetails.getLineNumber(), plantAssetId, plantAssetPromptDetail);
            insert errorLogInstance;
            update pltAstPrtDtl;
        }
        
    }
	/*
    * Form attribute value based on site metadata and attribute
    * @param {Site_Metadata__c} siteMetaDataInstance - Site Metadata needed for creation or updation of Attribute Value.
    * @param {Map<String,String>} infoMap - Set of information, it may be attribute info or prompt specific info.
    * @param {String} AttrName - Attribute name that needed to create attribute value.
    * @param {Map<String, Core_Attribute__c>} attrNameToAttrInfo - Attribute Value against Plant Asset
    */
    public static Attribute_Value__c attributeValueFormation(Site_Metadata__c siteMetaDataInstance, Map<String,String> infoMap, String AttrName, Map<String, Core_Attribute__c> attrNameToAttrInfo){
        Attribute_Value__c attrValue = new Attribute_Value__c();
        attrValue.Account_Plant__c = siteMetaDataInstance.Account_Plant__c;
        attrValue.Site_Metadata__c = siteMetaDataInstance.Id;
        attrValue.Prompt_Information__c = siteMetaDataInstance.Prompt_Information__c; 
        attrValue.Base_Asset_Template__c = siteMetaDataInstance.Base_Asset_Template__c;
        String attrNameWithoutBAT = AttrName.split('-')[1];
        attrValue.Value__c = String.isNotBlank(infoMap.get(attrNameWithoutBAT)) ? infoMap.get(attrNameWithoutBAT) : attrNameToAttrInfo.get(AttrName).Default_value__c;
        Core_Attribute__c coreAttr = attrNameToAttrInfo.get(AttrName);
        attrValue.Attribute__c = coreAttr.Id;
        attrValue.External_ID__c = attrValue.Account_Plant__c+'-'+attrValue.Site_Metadata__c+'-'+attrValue.Attribute__c;
        String dataType = attrNameToAttrInfo.get(AttrName).Attribute_Master__r.Data_Type__c;
        if(String.isNotBlank(attrValue.Value__c)){
            String valueToCheck = attrValue.Value__c;
            if(dataType == 'Decimal'){
                attrValue.Value_Floating__c = valueToCheck.isNumeric()? Decimal.valueOf(attrValue.Value__c) : null; 
            }else if(dataType == 'Date'){
                attrValue.Value_Date__c = Date.valueOf(attrValue.Value__c);
            }else if(dataType == 'Checkbox'){
                attrValue.Value_Checkbox__c = Boolean.valueOf(attrValue.Value__c);
            }else if(dataType == 'Number'){
                attrValue.Value_Number__c = valueToCheck.isNumeric()? Integer.valueOf(attrValue.Value__c) : null;
            }                                            
        }
        return attrValue;
    }
}