unpackaged/main/default/objects/SBQQ__Quote__c/SBQQ__Quote__c.object-meta.xml
<CustomObject>
    <customHelpPage>SBQQ__QuoteHelp</customHelpPage>
    <description>Sales quote for a given opportunity. There may be multiple quotes for a single opportunity.</description>
    <label>Quote</label>
    <nameField>
        <displayFormat>Q-{00000}</displayFormat>
        <label>Quote Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Quotes</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/SBQQ__QuoteLine__c/fields/SBQQ__Quote__c.field-meta.xml
<CustomField>
    <fullName>SBQQ__Quote__c</fullName>
    <description>Quote to which this line item belongs.</description>
    <inlineHelpText>Quote to which this line item belongs</inlineHelpText>
    <label>Quote</label>
    <referenceTo>SBQQ__Quote__c</referenceTo>
    <relationshipLabel>Quote Lines</relationshipLabel>
    <relationshipName>LineItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/classes/addNetTotalFromPptTest.cls
@isTest
public class addNetTotalFromPptTest {
    
    @testSetup 
    public static void generatedata() {

        Pricebook2 pbId = TestDataFactory.createPriceBook();
        insert pbId ;
        
        Account acc = TestDataFactory.createAccount(pbId.Id);
        insert acc;
        
        Opportunity opp = TestDataFactory.createOpportunity(acc.Id);
        insert opp;
        
        SBQQ__Quote__c quote  = TestDataFactory.createQuote(acc.Id, opp.Id);
        insert quote;
        
        Product2 product = TestDataFactory.createProductAgain();
        insert product;
        
        SBQQ__QuoteLine__c quoteLine = TestDataFactory.createQuoteLine(quote.Id, product.Id);
        insert quoteLine;
        
        }
    
    public static testMethod void testInsert(){
    
    	String accName = 'TestCP';
    	Account accts = [SELECT Id, Name FROM Account WHERE Name =:accName LIMIT 1];
    	Test.startTest();
        System.debug('Account Name : ' + accName);
        Test.stopTest();
        System.assertEquals('TestCP', accName );
    
	}

}