unpackaged/main/default/objects/Asset_Builder_Report_Data__c/Asset_Builder_Report_Data__c.object-meta.xml
<CustomObject>
    <label>Completeness Report Data</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Asset Builder Report Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completeness Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Completeness Report Data</relationshipLabel>
    <relationshipName>Asset_Builder_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Completeness Report Data</relationshipLabel>
    <relationshipName>Asset_Builder_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/AttributesRequirementForRFIItemCreation__mdt/AttributesRequirementForRFIItemCreation__mdt.object-meta.xml
<CustomObject>
    <description>For dynamic query Attribute Requirement for RFI Item Creation</description>
    <label>AttributesRequirementForRFIItemCreation</label>
    <pluralLabel>AttributesRequirementForRFIItemCreations</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/AttributesRequirementForRFIItemCreation__mdt/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/RFI_Category__c.field-meta.xml
<CustomField>
    <fullName>RFI_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RFI Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipLabel>Base Asset Templates</relationshipLabel>
    <relationshipName>Base_Asset_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/Evaluation__c.object-meta.xml
<CustomObject>
    <label>Evaluation</label>
    <nameField>
        <label>Evaluation Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Evaluations</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Evaluation__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <label>Alias</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data Capability</fullName>
            </value>
            <value>
                <fullName>Feature</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Evaluation_Notes__c.field-meta.xml
<CustomField>
    <fullName>Evaluation_Notes__c</fullName>
    <label>Evaluation Notes</label>
    <type>TextArea</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Group_1__c.field-meta.xml
<CustomField>
    <fullName>Group_1__c</fullName>
    <label>Group 1</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Group_for_Evaluation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Group_2__c.field-meta.xml
<CustomField>
    <fullName>Group_2__c</fullName>
    <label>Group 2</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>Group_for_Evaluation</valueSetName>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Products__c.field-meta.xml
<CustomField>
    <fullName>Products__c</fullName>
    <label>Products</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Drive Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Evaluations</relationshipLabel>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Result__c.field-meta.xml
<CustomField>
    <fullName>Result__c</fullName>
    <label>Result</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/RFI_Category__c.field-meta.xml
<CustomField>
    <fullName>RFI_Category__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>RFI Category</label>
    <referenceTo>RFI_Categories__c</referenceTo>
    <relationshipLabel>Evaluations</relationshipLabel>
    <relationshipName>Evaluations</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation__c/fields/Sub_Category__c.field-meta.xml
<CustomField>
    <fullName>Sub_Category__c</fullName>
    <label>Sub Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Feature</fullName>
            </value>
            <value>
                <fullName>Plant</fullName>
            </value>
            <value>
                <fullName>Weather Station</fullName>
            </value>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/Evaluation_Value__c.object-meta.xml
<CustomObject>
    <label>Evaluation Value</label>
    <nameField>
        <displayFormat>EV-{0000}</displayFormat>
        <label>Evaluation Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Evaluation Values</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Evaluation Values</relationshipLabel>
    <relationshipName>Evaluation_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Evaluation__c.field-meta.xml
<CustomField>
    <fullName>Evaluation__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Evaluation</label>
    <referenceTo>Evaluation__c</referenceTo>
    <relationshipLabel>Evaluation Values</relationshipLabel>
    <relationshipName>Evaluation_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Logic_Result__c.field-meta.xml
<CustomField>
    <fullName>Logic_Result__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Logic Result</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Evaluation_Value__c/fields/Show_In_Report__c.field-meta.xml
<CustomField>
    <fullName>Show_In_Report__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show In Report</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/Implementation_Wizard_Form_Detail__c.object-meta.xml
<CustomObject>
    <description>To store file and API request and response details of implementation wizard form</description>
    <label>Implementation Wizard Form Detail</label>
    <nameField>
        <label>Implementation Wizard Form Detail Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Implementation Wizard Form Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Implementation_Wizard_Form_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Link to plant asset related to the form API request</description>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Implementation Wizard Form Details</relationshipLabel>
    <relationshipName>Implementation_Wizard_Form_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Bulk_Import_Type__c.field-meta.xml
<CustomField>
    <fullName>Bulk_Import_Type__c</fullName>
    <label>Bulk Import Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Single Base Asset Template Prompts</fullName>
                <default>true</default>
                <label>Single Base Asset Template Prompts</label>
            </value>
            <value>
                <fullName>Multiple Base Asset Template Prompts</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Manual</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Alias__c.field-meta.xml
<CustomField>
    <fullName>Alias__c</fullName>
    <description>Prompt Name Alias</description>
    <label>Alias</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Onshore</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
            <value>
                <fullName>MetMast</fullName>
            </value>
            <value>
                <fullName>SubstationSwitchgear</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/globalValueSets/Group_for_Evaluation.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>Ambient Temperature</fullName>
    </customValue>
    <customValue>
        <fullName>Anemometer</fullName>
    </customValue>
    <customValue>
        <fullName>Availability</fullName>
    </customValue>
    <customValue>
        <fullName>Combiner Heatmap</fullName>
    </customValue>
    <customValue>
        <fullName>Common</fullName>
    </customValue>
    <customValue>
        <fullName>Common - Energy Loss Allocation - Energy Loss</fullName>
    </customValue>
    <customValue>
        <fullName>Dashboard</fullName>
    </customValue>
    <customValue>
        <fullName>Energy Loss Allocation</fullName>
    </customValue>
    <customValue>
        <fullName>Event Creation</fullName>
    </customValue>
    <customValue>
        <fullName>Expected/Predicted Production</fullName>
    </customValue>
    <customValue>
        <fullName>Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Inverter Configuration S</fullName>
    </customValue>
    <customValue>
        <fullName>IRRADIANCE CLEAR_SKY</fullName>
    </customValue>
    <customValue>
        <fullName>Level 0</fullName>
    </customValue>
    <customValue>
        <fullName>Level 0 (optional)</fullName>
    </customValue>
    <customValue>
        <fullName>Level 2</fullName>
    </customValue>
    <customValue>
        <fullName>Meter</fullName>
    </customValue>
    <customValue>
        <fullName>Met mast Configuration W</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Metadata - Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Metadata - Plant</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Metadata - Subarray</fullName>
    </customValue>
    <customValue>
        <fullName>Missing or Invalid Subarray Metadata - Inverter</fullName>
    </customValue>
    <customValue>
        <fullName>Modelling</fullName>
    </customValue>
    <customValue>
        <fullName>Module Temperature</fullName>
    </customValue>
    <customValue>
        <fullName>Nominal Power</fullName>
    </customValue>
    <customValue>
        <fullName>Other</fullName>
    </customValue>
    <customValue>
        <fullName>Other Miscellaneous</fullName>
    </customValue>
    <customValue>
        <fullName>Plant Configuration S</fullName>
    </customValue>
    <customValue>
        <fullName>Plant configuration W</fullName>
    </customValue>
    <customValue>
        <fullName>POA Pyranometer</fullName>
    </customValue>
    <description>Picklist values for Group fields in Evaluation Object.</description>
    <masterLabel>Group for Evaluation</masterLabel>
</GlobalValueSet>

unpackaged/main/default/classes/Utils2.cls
public with sharing class Utils2 {
    
    /*
     * To update all the plantAssetPromptDetails as Is_Deleted__c = true 
     * @param plantAssetId
    */
    @AuraEnabled
    public static Boolean updatePlantAssetPromptDetail(String plantAssetId){
            Boolean result = false;
            Plant_Asset_Prompt_Detail__c g1PlantAssetPromptDetail = Utils.getG1PlantAssetPromptDetail(plantAssetId);
            List<Plant_Asset_Prompt_Detail__c>  plantAssetPromptDetailLst = new List<Plant_Asset_Prompt_Detail__c>();
            List<ContentDocumentLink> cdList = new List<ContentDocumentLink>();
            String plantAssetPromptDetailId = '';
            try {
                if(g1PlantAssetPromptDetail.Bulk_Import_Type__c == Constants.SINGLE_BASE_ASSET_TEMPLATE_PROMPTS){
                    for(Plant_Asset_Prompt_Detail__c plantAssetPromptDetail: [SELECT Id, Is_Deleted__c, Prompt_Information__r.Name FROM Plant_Asset_Prompt_Detail__c WHERE Account_Plant__c =:plantAssetId AND Is_Deleted__c = false]){
                        if(plantAssetPromptDetail.Prompt_Information__r.Name != Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT){
                            plantAssetPromptDetail.Is_Deleted__c = true ;
                            plantAssetPromptDetailLst.add(plantAssetPromptDetail);
                        } else {
                            plantAssetPromptDetailId = plantAssetPromptDetail.Id;
                        }
                    }
                    if(plantAssetPromptDetailId != ''){
                        for(ContentDocumentLink cd : [SELECT Id,LinkedEntityId FROM ContentDocumentLink WHERE LinkedEntityId =: plantAssetPromptDetailId]){
                                cdList.add(cd);
                        }
                    }
                    
                    if(cdList.size() > 0){
                        delete cdList;
                    }
        
                    if(plantAssetPromptDetailLst.size() > 0){
                        update plantAssetPromptDetailLst;
                    }
                }
                result = true;
            } catch(Exception exceptionDetails){
                result = false;
                String errorMessage = System.Label.AssetBuilderExceptionMessage;
                System.debug(' Error Message -> ' + exceptionDetails.getMessage() + ' Line # ' + exceptionDetails.getLineNumber());
                throw new AuraHandledException(errorMessage);
            }  
            return result;
        }
        /*
        * To generate RFI and updatation RFI related field for tracking purpose
        * @param plantAssetId
        */
        public static String callRFIGeneration(String plantAssetId){
            String rfiProcessResult='';
            try{
                //query all evaluations related against plant asset
                List<Evaluation_Value__c> evalValueLst = new List<Evaluation_Value__c>([SELECT Id, Name, Logic_Result__c, Account_Plant__c, Show_In_Report__c, Result__c, Evaluation__r.Sub_Category__c, Evaluation__r.Category__c,
                    Evaluation__r.Alias__c, Evaluation__r.Group_1__c, Evaluation__r.Group_2__c, Evaluation__r.Evaluation_Notes__c, Evaluation__r.RFI_Category__c, Evaluation__r.Products__c
                    FROM Evaluation_Value__c WHERE Account_Plant__c =: plantAssetId AND Show_In_Report__c = TRUE AND Result__c !=: Constants.PASS]);
                //query all Asset builder report data to know missing attributes related to completeness report
                List<String> systemNames = Utils.getAttrReqSysNamesFrmG1(plantAssetId);
                
                //Get necessary attribute requirement for rfi item creation 
                Map<String, String> attrReqInRD = new Map<String, String>();
                List<Asset_Builder_Report_Data__c> assetBuilderReportDataLst = new List<Asset_Builder_Report_Data__c>();
                
                for(AttributesRequirementForRFIItemCreation__mdt attrReqForRFI : [SELECT DeveloperName, Type__c, Value__c,Label FROM AttributesRequirementForRFIItemCreation__mdt WHERE Label IN: systemNames ORDER BY Label]){
                        attrReqInRD.put(attrReqForRFI.Label, attrReqForRFI.Type__c);
                }
                
                for(Asset_Builder_Report_Data__c abrd : [SELECT Base_Asset_Template__r.RFI_Category__c, Base_Asset_Template__c, Prompt_Information__c, System__c, Type__c, Total_Attribute_Count__c, Total_Completed_Attribute_Count__c, Is_Archived__c, Account_Plant__c FROM Asset_Builder_Report_Data__c 
                                                            WHERE Account_Plant__c =: plantAssetId AND Is_Archived__c = FALSE AND Type__c IN: attrReqInRD.values()]){
                    if(attrReqInRD.containsKey(abrd.System__c)){
                        assetBuilderReportDataLst.add(abrd);
                    }
                }
                
                //To show message based on a condition - if there is no missed attributes during asset builder process and no evaluation value generated - show a information message 
                if(evalValueLst.size() == 0 && assetBuilderReportDataLst.size() == 0){
                    rfiProcessResult = System.Label.NoRfiToBeCreated+'&Error';
                }else if(evalValueLst.size() > 0 || assetBuilderReportDataLst.size() > 0){ //To show message based on a condition - if any missed attributes during asset builder process or any evaluation value generated - show a information message and publish a event for rfi creation
                    //Update RFI Generation status in G1 Plant asset prompt detail against Plant asset
                    Plant_Asset_Prompt_Detail__c pltAstPrtDtl = [SELECT Id, Name, RFI_Generated_for_CA_Report__c, RFI_Generated_for_CO_Report__c, Account_Plant__c,  Account_Plant__r.Asset_Builder_Status__c, RFI_Generated_By_User__c, RFI_Generated_Datetime__c FROM Plant_Asset_Prompt_Detail__c WHERE Account_Plant__c =:plantAssetId AND Prompt_Information__r.Name=: Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT AND Is_Deleted__c = FALSE];
                    pltAstPrtDtl.RFI_Generated_for_CA_Report__c = Constants.IN_PROGRESS;
                    pltAstPrtDtl.RFI_Generated_for_CO_Report__c = Constants.IN_PROGRESS;
                    pltAstPrtDtl.RFI_Generated_Datetime__c = System.now();
                    pltAstPrtDtl.RFI_Generated_By_User__c = UserInfo.getUserId(); 
                    pltAstPrtDtl.RFI_PE_Process_Description__c = '';
                    update pltAstPrtDtl;
                    //Call RFI Data Creation class
/*                    String resultFromRFICreation = RFIDataCreation.dataFormationForRFI(plantAssetId);
                    if(resultFromRFICreation == 'true'){
                        rfiProcessResult = System.Label.RFIGeneratedSuccessfully+'&Success';
                    }else{
                        rfiProcessResult = resultFromRFICreation+'&Error';
                    }  */ //Uncomment after Deploying RFI
                }
            }catch(Exception exceptionDetails){
                rfiProcessResult = exceptionDetails.getMessage()+'&Error';
                insert Utils.catchErrorLogs('callRFIGeneration',exceptionDetails.getMessage(), exceptionDetails.getLineNumber(), plantAssetId, '');
            }
            return rfiProcessResult;
        }
        @AuraEnabled
        public static Boolean updateG1PlantAssetPromptDetail(String plantAssetId, String jsonInputParametersAndValues){
            Boolean result = false;
            Plant_Asset_Prompt_Detail__c g1PlantAssetPromptDetail = Utils.getG1PlantAssetPromptDetail(plantAssetId);
            if(!String.isBlank(jsonInputParametersAndValues)){
                Map<String,String> jsonInputParametersAndValuesMap = Utils.deserializeAttribute(jsonInputParametersAndValues);
                Boolean isBulkUploadCheck = Boolean.valueOf(jsonInputParametersAndValuesMap.get(Constants.IS_BULK_UPLOAD));
                Boolean isBulkUploadMultipleBATCheck = Boolean.valueOf(jsonInputParametersAndValuesMap.get(Constants.IS_BULK_UPLOAD_MULTIPLE_BAT));
                if(isBulkUploadCheck){
                    g1PlantAssetPromptDetail.Bulk_Import_Type__c = Constants.MULTIPLE_BASE_ASSET_TEMPLATE_PROMPTS;
                    result = true;
                }else if(isBulkUploadMultipleBATCheck){
                    g1PlantAssetPromptDetail.Bulk_Import_Type__c = Constants.COMPLETED;
                    result = true;
                }
                update g1PlantAssetPromptDetail;
            }
            return result;
        }
    
    
        /**
         * This Method is used to get the csv string based on the Prompt Name, Plant Asset Id and Json Input Values
         */
        public static String getImpWizCSVFileforPrompts(String jsonInputParametersAndValues, String plantAssetId,
                String currentPromptName){
            String promptName;
            String csvData = '';
            if(currentPromptName.contains('/')){
                currentPromptName = currentPromptName.replace('/', '-');
            }
    
            promptName = (currentPromptName.length()>31) ? currentPromptName.substring(0, 31) : currentPromptName;
            Map<String,String> jsonInputParametersAndValuesMap = Utils.deserializeAttribute(jsonInputParametersAndValues);
            Boolean isImpWizUpLoad = Boolean.valueOf(jsonInputParametersAndValuesMap.get(Constants.IS_IMPWIZ_UPLOAD));
    
            if(isImpWizUpLoad){
                csvData = Utils2.getPlatAssetCSVData(plantAssetId, promptName);
            }
            return csvData;
        }
    
        // To get CSv file from the Plant Asset to populate the values based on the prompt name.
        // This is when user launch AB from IW to load date from the downloaded/ uploaded file.
    
        public static String getPlatAssetCSVData (String plantAssetId, String promptName){
    
            list<String> allfilesRelatedToPA = new List<String>();
            String searchString = promptName;
            Id linkedIWFDId = [SELECT Id FROM Implementation_Wizard_Form_Detail__c WHERE Account_Plant__c =: plantAssetId
                                ORDER BY CreatedDate desc LIMIT 1].Id;
    
            for(ContentDocumentLink contentDocument :[SELECT ContentDocumentId, LinkedEntityId  FROM ContentDocumentLink WHERE
                    LinkedEntityId =: linkedIWFDId ]){
                allfilesRelatedToPA.add(contentDocument.ContentDocumentId);
            }
    
            string promptNamewithCSV = promptName+'.csv';
            List<ContentVersion> getCSVData = new list<ContentVersion>([SELECT Id, Title, VersionData FROM ContentVersion
            WHERE ContentDocumentId =: allfilesRelatedToPA
            AND Title =: promptNamewithCSV ORDER BY LastModifiedDate DESC LIMIT 1]);
    
            String csvString;
            if(getCSVData.size()>0){
                csvString = Utils.blobToString( getCSVData[0].VersionData,'ISO-8859-1');
            }else{
                csvString = 'No CSV Files Found';
            }
            return csvString;
        }
    }