unpackaged/main/default/objects/Asset_Builder_Report_Data__c/Asset_Builder_Report_Data__c.object-meta.xml
<CustomObject>
    <label>Completeness Report Data</label>
    <nameField>
        <displayFormat>RD-{0000}</displayFormat>
        <label>Asset Builder Report Data Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Completeness Report Data</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Completeness Report Data</relationshipLabel>
    <relationshipName>Asset_Builder_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Asset Builder Report Data</relationshipLabel>
    <relationshipName>Completeness_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Is_Archived__c.field-meta.xml
<CustomField>
    <fullName>Is_Archived__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Archived?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Completeness Report Data</relationshipLabel>
    <relationshipName>Asset_Builder_Report_Data</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Asset_Builder_Report_Data__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <label>System</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Requirement__c/Attribute_Requirement__c.object-meta.xml
<CustomObject>
    <description>Stores the base asset&#39;s attribute requirement information to be fetched in prompt screens</description>
    <label>Attribute Requirement</label>
    <nameField>
        <label>Attribute Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Requirement__c/fields/Core_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Core_Attribute__c</fullName>
    <label>Core Attribute</label>
    <referenceTo>Core_Attribute__c</referenceTo>
    <relationshipLabel>Attribute Requirements</relationshipLabel>
    <relationshipName>Attribute_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Requirement__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <label>Required</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Yes</fullName>
            </value>
            <value>
                <fullName>No</fullName>
            </value>
            <value>
                <fullName>N/A</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attribute_Requirement__c/fields/System__c.field-meta.xml
<CustomField>
    <fullName>System__c</fullName>
    <description>To collect the which system the core attribute is required</description>
    <inlineHelpText>Select one value in which system this attribute is required</inlineHelpText>
    <label>System</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drive</fullName>
            </value>
            <value>
                <fullName>Drive Plus</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/Attribute_Value__c.object-meta.xml
<CustomObject>
    <label>Attribute Value</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Value__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute</label>
    <referenceTo>Core_Attribute__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Is_Completed__c.field-meta.xml
<CustomField>
    <fullName>Is_Completed__c</fullName>
    <formula>NOT(ISBLANK(Value__c))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Completed?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Is_Value_Defaulted__c.field-meta.xml
<CustomField>
    <fullName>Is_Value_Defaulted__c</fullName>
    <formula>IF(NOT(ISBLANK(Attribute__r.Default_value__c)),TRUE,FALSE)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Value Defaulted?</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Site_Metadata__c</fullName>
    <label>Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Attribute__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Required__c.field-meta.xml
<CustomField>
    <fullName>Required__c</fullName>
    <label>Required</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Error_Log__c/Error_Log__c.object-meta.xml
<CustomObject>
    <label>Error Log</label>
    <nameField>
        <displayFormat>Error-{0000}</displayFormat>
        <label>Error Logs Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Error_Log__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Error Logs</relationshipLabel>
    <relationshipName>Error_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Account_Plant__c.field-meta.xml
<CustomField>
    <fullName>Account_Plant__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account Plant</label>
    <referenceTo>Account_Plant__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Is_Deleted__c.field-meta.xml
<CustomField>
    <fullName>Is_Deleted__c</fullName>
    <formula>Plant_Asset_Prompt_Detail__r.Is_Deleted__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Is Deleted</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Parent_Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Parent_Site_Metadata__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Parent Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Site Metadata (Parent Site Metadata)</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/ReportDataHandler.cls
public with sharing class ReportDataHandler {
    Map<String,Integer> attrCompletedCountMap = new Map<String,Integer>();
    Map<String,Integer> attrTotalCountMap = new Map<String,Integer>();

    List<Asset_Builder_Report_Data__c> reportDataCreationList = new List<Asset_Builder_Report_Data__c>();
    Map<String,List<String>> systemMap = new Map<String,List<String>>();
    Map<String,String> requiredMap = new Map<String,String>{
        'Yes' => 'Required',
        'No' => 'Optional'
    };
    public Plant_Asset_Prompt_Detail__c pltAstPrtDtl;
    public static String plantAssetId;

    public Void assetReportDataCreation(Id plantId, List<Id> promptIds) {
        try{
            plantAssetId = plantId;
            systemMap.put('Drive', new List<string>{'Yes','No'});
            systemMap.put('Drive Plus', new List<string>{'Yes','No'});
            List<String> fieldNames = new List<String>{'Is_Completed__c','Is_Value_Defaulted__c'};

            for(String sys : systemMap.keySet()){ 
                for(String requiredSys : systemMap.get(sys)){
                    for(String fieldName : fieldNames){
                        reportDataAggregateQuery(plantId, promptIds, sys, requiredSys, fieldName);
                    }
                }
            }

            if(attrCompletedCountMap.size() > 0){
                reportDataCreation(plantId);
            }
        }catch(Exception exp){
            System.debug('error message ' + exp.getMessage() + ' line # ' + exp.getLineNumber());
            Error_Log__c errorLogInstance = Utils.catchErrorLogs('reportDataCreation',exp.getMessage(), exp.getLineNumber(), plantAssetId, '');
            insert errorLogInstance;
        }
    }

    public void reportDataAggregateQuery(Id plantId, List<Id> promptIds, String sys, String requiredSys, String fieldName){
        try{
            String query = 'SELECT Prompt_Information__c, Base_Asset_Template__c,' + (String.isBlank(fieldName) ? '' : fieldName + ',');
            query += ' Count(Id)cnt FROM Attribute_Value__c';
            query += ' WHERE Plant_Asset__r.Id =: plantId AND Site_Metadata__r.Is_Deleted__c = FALSE';
            if(promptIds.size() > 0){
                query += ' AND Prompt_Information__c IN: promptIds';
            }
            query += ' AND Attribute__c IN (SELECT Core_Attribute__c FROM Attribute_Requirement__c WHERE';
            query += ' System__c =: sys AND Required__c =: requiredSys)';
            query += ' GROUP BY ROLLUP(Prompt_Information__c, Base_Asset_Template__c' + (String.isBlank(fieldName) ? '' : ',' + fieldName) +')'; 
            query += ' ORDER BY Base_Asset_Template__c NULLS last ' + (String.isBlank(fieldName) ? '' : ',' + fieldName) + ' NULLS last';

            for(AggregateResult agrResultRow : Database.query(query)){                    
                if(agrResultRow.get('Prompt_Information__c') != NULL && agrResultRow.get('Base_Asset_Template__c') != NULL){
                    String promptId = (String)agrResultRow.get('Prompt_Information__c');
                    String baseAssetId = (String)agrResultRow.get('Base_Asset_Template__c');
                    Integer cnt = (Integer)agrResultRow.get('cnt');
                    String mapKey = promptId + '-' + baseAssetId + '-' + sys + '-' + requiredMap.get(requiredSys) + ((fieldName == 'Is_Value_Defaulted__c')?' (Default)':'');
                
                    if(agrResultRow.get(fieldName) != NULL){
                        Integer recCount;
                        if((Boolean)agrResultRow.get(fieldName)){
                            recCount = cnt;
                        }else{
                            recCount = 0;
                        }
                        attrCompletedCountMap.put(mapKey, recCount);
                    }else if(agrResultRow.get(fieldName) == NULL){
                        attrTotalCountMap.put(mapKey, cnt);
                    }
                }
            }
        }catch(Exception exp){
            System.debug('error message ' + exp.getMessage() + ' line # ' + exp.getLineNumber());
            Error_Log__c errorLogInstance = Utils.catchErrorLogs('reportDataCreation',exp.getMessage(), exp.getLineNumber(), plantAssetId, '');
            insert errorLogInstance;
        }
    }

    public void queryExsistingReportData(Id plantId, List<Id> promptIds){
        try{
            String query = 'SELECT Id, Name, Is_Archived__c FROM Asset_Builder_Report_Data__c WHERE Account_Plant__c =: plantId';
            if(promptIds.size()>0){
                query += ' AND Prompt_Information__c IN: promptIds';
            }

            List<Asset_Builder_Report_Data__c> exsistingReportDataArchived = new List<Asset_Builder_Report_Data__c>();
            for(Asset_Builder_Report_Data__c reportData : Database.query(query)){
                reportData.Is_Archived__c = TRUE;
                exsistingReportDataArchived.add(reportData);
            }

            if(exsistingReportDataArchived.size() > 0){
                update exsistingReportDataArchived;
            }
            
            assetReportDataCreation(plantId, promptIds);
        }catch(Exception exp){
            System.debug('error message ' + exp.getMessage() + ' line # ' + exp.getLineNumber());
            Error_Log__c errorLogInstance = Utils.catchErrorLogs('reportDataCreation',exp.getMessage(), exp.getLineNumber(), plantAssetId, '');
            insert errorLogInstance;
        }
    }

    public void reportDataCreation(Id plantId){
        Savepoint sp;
        try{
            if(attrCompletedCountMap.size() > 0){
                for(String attrCompletedKey : attrCompletedCountMap.keySet()){
                    List<String> attrCompletedKeySplit = attrCompletedKey.split('-');
                    String promptId, baseAssetId, systemName, requiredSys;
                    Integer cnt;

                    if(attrCompletedKeySplit.size() == 4){
                        promptId = attrCompletedKeySplit[0];
                        baseAssetId = attrCompletedKeySplit[1];
                        systemName = attrCompletedKeySplit[2];
                        requiredSys = attrCompletedKeySplit[3];
                        cnt = attrCompletedCountMap.get(attrCompletedKey);
                    }

                    Asset_Builder_Report_Data__c assetReportCreation = new Asset_Builder_Report_Data__c();
                    assetReportCreation.Account_Plant__c = plantId; 
                    assetReportCreation.Prompt_Information__c = promptId;
                    assetReportCreation.Base_Asset_Template__c = baseAssetId;
                    assetReportCreation.System__c = systemName;
                    assetReportCreation.Type__c = requiredSys;
                    assetReportCreation.Total_Completed_Attribute_Count__c = cnt;
                    assetReportCreation.Total_Attribute_Count__c = attrTotalCountMap.get(attrCompletedKey);
                    reportDataCreationList.add(assetReportCreation);
                }
            }
            sp = Database.setSavepoint();
            pltAstPrtDtl = [SELECT Id, Name, Capability_Report_Status__c, Completeness_Report_Status__c, Prompt_Information__c, Account_Plant__c  
                    FROM Plant_Asset_Prompt_Detail__c 
                    WHERE Account_Plant__c =:plantId  AND Prompt_Information__r.Name=: Constants.G1_G2_PLANT_INFO_AND_RENEWABLE_TYPE_PROMPT AND Is_Deleted__c = FALSE];
            pltAstPrtDtl.Completeness_Report_Status__c = 'Completed';
           
            if(reportDataCreationList.size() > 0){
                insert reportDataCreationList;
                update pltAstPrtDtl;
            }
        }catch(Exception exceptionDetails){
            Database.rollback(sp);
            System.debug('error message ' + exceptionDetails.getMessage() + ' line # ' + exceptionDetails.getLineNumber());
            Error_Log__c errorLogInstance = Utils.catchErrorLogs('reportDataCreation',exceptionDetails.getMessage(), 
                                                                 exceptionDetails.getLineNumber(), plantAssetId, '');
            insert errorLogInstance;
            pltAstPrtDtl.Completeness_Report_Status__c = 'Completed - Error';
            update pltAstPrtDtl;
        }
        
    } 
}