unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Account with which we are signing the MSA.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MSA Contracts</relationshipLabel>
    <relationshipName>MSA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/MSA_Software_Discount_Tier_Price__c.object-meta.xml
<CustomObject>
    <label>MSA Software Discount Tier Price</label>
    <nameField>
        <displayFormat>DS-{0000}</displayFormat>
        <label>MSA Software Discount Tier Price</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Software Discount Tier Prices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Create_MSA_Software_Discount_Tier_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Cross_Orders__c.field-meta.xml
<CustomField>
    <fullName>Cross_Orders__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Consider Active MW</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Discount_Amount__c.field-meta.xml
<CustomField>
    <fullName>Discount_Amount__c</fullName>
    <label>Discount Amount</label>
    <precision>14</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Lower_Bound__c.field-meta.xml
<CustomField>
    <fullName>Lower_Bound__c</fullName>
    <label>Lower Bound</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/MSA_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSA_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSA Contract</label>
    <referenceTo>MSA_Contract__c</referenceTo>
    <relationshipLabel>MSA Software Discount Tier Prices</relationshipLabel>
    <relationshipName>MSA_Software_Discount_Tier_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Pricing_Tier__c.field-meta.xml
<CustomField>
    <fullName>Pricing_Tier__c</fullName>
    <inlineHelpText>Pricing Tier</inlineHelpText>
    <label>Pricing Tier</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>Product2.IsActive</field>
            <operation>equals</operation>
            <value>True</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>MSA Software Discount Tier Prices</relationshipLabel>
    <relationshipName>MSA_Software_Discount_Tier_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Software_Discount_Tier_Price__c/fields/Upper_Bound__c.field-meta.xml
<CustomField>
    <fullName>Upper_Bound__c</fullName>
    <label>Upper Bound</label>
    <precision>12</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/classes/SoftwareDiscountTier.cls
public class SoftwareDiscountTier {

    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchAccountName(String RecId){
        System.debug('Discount tier fetchAccountName');
        return [Select Id , Account_Name__c , Account_Name__r.Name from MSA_Contract__c where Id = :RecId];
    }
    

    @AuraEnabled(cacheable=true)
    public static List<MSA_Contract__c> fetchCurrency(String RecId){
        System.debug('ESoftware Discount Tier fetchCurrency');
        return [Select CurrencyIsoCode from MSA_Contract__c where Id = :RecId];
    }


    @AuraEnabled(cacheable=true)
    public static List<MSA_Software_Discount_Tier_Price__c> fetchSoftwareListPriceData(String RecId){
        List<MSA_Contract__c> accountId = [Select Account_Name__c from MSA_Contract__c where Id = :RecId limit 1];
        Id accId = string.valueOf(accountId[0].Account_Name__c);
        List<MSA_Software_Discount_Tier_Price__c> records = [Select Id, MSA_Contract__c, Account__r.Name, Product__r.Name, Pricing_Tier__c, Cross_Orders__c, Lower_Bound__c, Upper_Bound__c, Discount_Amount__c, Effective_Start_Date__c,  Effective_End_Date__c
        from MSA_Software_Discount_Tier_Price__c
        where Account__r.Id = :accId ];
        system.debug('Account ID' + accId);
        system.debug('No of records found with software price =>' + records.size());
        return records;
    }


    @AuraEnabled 
    public static void deleteSoftwarePriceRecord(List<MSA_Software_Discount_Tier_Price__c> softPriceList, String msaId){  
       // if (softPriceList.size() == 0){}
           // return; 
        List<Id> deletedPrices = new List<Id>();
        for(MSA_Software_Discount_Tier_Price__c softPrice : softPriceList ){
            deletedPrices.add(softPrice.Id);
        }
         System.debug('Deleted Prices::'+deletedPrices);
         
        try {
            delete softPriceList;
            System.debug('Deleted');
        }
        catch(DmlException ex) {
                System.debug('Exception while deleting the plants from the quote line i.e. deleting PPT records'
                                +string.valueOf(ex.getLineNumber()) +ex.getTypeName() +string.valueOf(ex.getCause()) +ex.getMessage() +ex.getStackTraceString());

            }
        }

}