unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Contract__c/fields/Account_Name__c.field-meta.xml
<CustomField>
    <fullName>Account_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This is the Account with which we are signing the MSA.</description>
    <label>Account Name</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>MSA Contracts</relationshipLabel>
    <relationshipName>MSA_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/fields/Annual_Uplift_Percentage__c.field-meta.xml
<CustomField>
    <fullName>Annual_Uplift_Percentage__c</fullName>
    <inlineHelpText>Enter 0 if there is no contractual annual uplift. A customer&#39;s contracted prices are increased by this amount automatically.</inlineHelpText>
    <label>Annual Uplift Percentage</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Percent</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/fields/MSA_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>MSA_Start_Date__c</fullName>
    <description>Agreement Effective Date</description>
    <label>MSA Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/MSA_Contract__c/fields/MSA_Status__c.field-meta.xml
<CustomField>
    <fullName>MSA_Status__c</fullName>
    <description>To track the status of MSA</description>
    <label>MSA Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>In Negotiation</fullName>
                <default>true</default>
                <label>In Negotiation</label>
            </value>
            <value>
                <fullName>Submitted</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/SBQQ__ContractedPrice__c/fields/MSA_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSA_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSA Contract</label>
    <referenceTo>MSA_Contract__c</referenceTo>
    <relationshipLabel>Contracted Prices</relationshipLabel>
    <relationshipName>Contracted_Prices</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/SBQQ__ContractedPrice__c/fields/Same_As_List_Price__c.field-meta.xml
<CustomField>
    <fullName>Same_As_List_Price__c</fullName>
    <defaultValue>true</defaultValue>
    <description>This flag is to track if the Contract Price has been changed from the List Price</description>
    <inlineHelpText>This flag is to track if the Contract Price has been changed from the List Price</inlineHelpText>
    <label>Same As List Price</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/autoUpliftContractedPriceBatchProcess.cls
global class autoUpliftContractedPriceBatchProcess implements Database.Batchable<sObject> {
    global Database.QueryLocator start(Database.BatchableContext BC) {
        
        // collect the batches of records or objects to be passed to execute
        String query = 'Select Id,Name,Account_Name__c, Account_Name__r.Name,Annual_Uplift_Percentage__c, MSA_Status__c, MSA_Start_Date__c  from MSA_Contract__c  where MSA_Status__c =\'Approved\' AND  Annual_Uplift_Percentage__c != null ';

        system.debug('==soql.Value__c='+query);
       
       
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<MSA_Contract__c> msaContractList) {
        set<id>accountIdSet = new set<id>();
        map<id,MSA_Contract__c>accIdWithMSAContractMap = new map<id,MSA_Contract__c>();
        for(MSA_Contract__c msa : msaContractList){
            system.debug('----msaContractList----'+msaContractList);
            integer yearDifference =   date.today().Year() - msa.MSA_Start_Date__c.Year();
                    system.debug('----yearDifference----'+yearDifference  );
            date msaDate = msa.MSA_Start_Date__c.addYears(yearDifference);
                    system.debug('---msaDate----'+msaDate);

            if(msaDate == date.today()){
                accountIdSet.add(msa.Account_Name__c);
                accIdWithMSAContractMap.put(msa.Account_Name__c,msa);            
            }
        }
        system.debug('----accIdWithMSAContractMap---'+accIdWithMSAContractMap);
        map<id,list<SBQQ__ContractedPrice__c>> accIdWithContractPriceListMap = new map<id,list<SBQQ__ContractedPrice__c>>();
        //Fetching Contracted Price assoicated to MSA Contract Account
        for(SBQQ__ContractedPrice__c contractedPrice : [Select id,Name,SBQQ__Price__c,SBQQ__Account__c,Same_As_List_Price__c,SBQQ__Account__r.Name,SBQQ__Product__c,SBQQ__Product__r.Name
                                                         from SBQQ__ContractedPrice__c where SBQQ__Account__c IN : accountIdSet AND SBQQ__Product__r.IsActive = true AND SBQQ__Price__c != null ]){
                                            system.debug('--SBQQ__Price__c--'+contractedPrice.SBQQ__Price__c);
                                            system.debug('--SBQQ__Price__c-id-'+contractedPrice);            
                                            list<SBQQ__ContractedPrice__c>contractPriceList;
                                            if(!accIdWithContractPriceListMap.isEmpty() && accIdWithContractPriceListMap.containskey(contractedPrice.SBQQ__Account__c)){
                                                contractPriceList = accIdWithContractPriceListMap.get(contractedPrice.SBQQ__Account__c);
                                                contractPriceList.add(contractedPrice);
                                            }
                                            else{
                                                contractPriceList = new list<SBQQ__ContractedPrice__c>();
                                                contractPriceList.add(contractedPrice);
                                            }
                                            accIdWithContractPriceListMap.put(contractedPrice.SBQQ__Account__c,contractPriceList);

        }
        list<SBQQ__ContractedPrice__c>updateContractPriceList = new list<SBQQ__ContractedPrice__c>();
        if(!accIdWithMSAContractMap.isEmpty() && !accIdWithContractPriceListMap.isEmpty()){
            for(id accId : accIdWithMSAContractMap.keyset()){
                MSA_Contract__c MSAContractVal = accIdWithMSAContractMap.get(accId);
                for(SBQQ__ContractedPrice__c contractPriceVal: accIdWithContractPriceListMap.get(accId)){
                    //calculating uplifting percent value in contract price
                    system.debug('---MSAContractVal.Annual_Uplift_Percentage__c---'+MSAContractVal.Annual_Uplift_Percentage__c);
                    system.debug('----contractPriceVal.SBQQ__Price__c ---'+contractPriceVal.SBQQ__Price__c );
                    contractPriceVal.SBQQ__Price__c += ((MSAContractVal.Annual_Uplift_Percentage__c * contractPriceVal.SBQQ__Price__c)/100 ) ;
 
                    updateContractPriceList.add(contractPriceVal);
                   
                }
            }
        }
        if(updateContractPriceList != null && updateContractPriceList.size() > 0){
            system.debug('---updateContractPriceList---'+updateContractPriceList);
            update updateContractPriceList;
        }
        
    }

    global void finish(Database.BatchableContext BC) {
        
    }
}