unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/MSA_Contract__c/fields/ApprovalStatus__c.field-meta.xml
<CustomField>
    <fullName>ApprovalStatus__c</fullName>
    <label>Approval Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Rejected</fullName>
            </value>
            <value>
                <fullName>Recalled</fullName>
            </value>
            <value>
                <fullName>Submitted</fullName>
                <isActive>false</isActive>
                <label>Submitted</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/classes/MSA_ContractExtControllerTests.cls
@isTest  
private class MSA_ContractExtControllerTests {  
      
    testMethod static void testSubmit() {  
        MSA_Contract__c MSA_Contract = new MSA_Contract__c();  
        insert MSA_Contract;  
          
        Test.startTest();  
        MSA_ContractExtController con = new MSA_ContractExtController(new ApexPages.StandardController(MSA_Contract));  
        con.onSubmit();  
        MSA_Contract = [SELECT ApprovalStatus__c FROM MSA_Contract__c WHERE Id = :MSA_Contract.Id LIMIT 1];  
        Test.stopTest();  
          
        System.assertEquals('Approved', MSA_Contract.ApprovalStatus__c);  
    }  
      
    testMethod static void testRecall() {  
        MSA_Contract__c MSA_Contract = new MSA_Contract__c();  
        insert MSA_Contract;  
          
        Test.startTest();  
        MSA_ContractExtController con = new MSA_ContractExtController(new ApexPages.StandardController(MSA_Contract));  
        con.onRecall();  
        MSA_Contract = [SELECT ApprovalStatus__c FROM MSA_Contract__c WHERE Id = :MSA_Contract.Id LIMIT 1];  
        Test.stopTest();  
          
        System.assertEquals('Recalled', MSA_Contract.ApprovalStatus__c);  
    }  
}