unpackaged/main/default/objects/MSA_Contract__c/MSA_Contract__c.object-meta.xml
<CustomObject>
    <label>MSA Contract</label>
    <nameField>
        <displayFormat>MSA - {0000}</displayFormat>
        <label>MSA Contract Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>MSA Contracts</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sbaa__Approval__c/sbaa__Approval__c.object-meta.xml
<CustomObject>
    <customHelpPage>sbaa__ApprovalHelp</customHelpPage>
    <description>Approval by individual for specific record.</description>
    <label>Approval</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Approval #</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Approvals</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/sbaa__Approval__c/fields/MSA_Contract__c.field-meta.xml
<CustomField>
    <fullName>MSA_Contract__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>MSA Contract</label>
    <referenceTo>MSA_Contract__c</referenceTo>
    <relationshipLabel>Approvals</relationshipLabel>
    <relationshipName>Approvals</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/classes/MSA_ContractExtController.cls
public with sharing class MSA_ContractExtController { 
    private Id MSA_ContractId; 
    public MSA_ContractExtController(ApexPages.StandardController stdController) { 
        MSA_ContractId = stdController.getId(); 
    } 
    public PageReference onSubmit() { 
        if (MSA_ContractId != null) { 
            SBAA.ApprovalAPI.submit(MSA_ContractId, SBAA__Approval__c.MSA_Contract__c); 
        } 
        return new PageReference('/' + MSA_ContractId); 
    } 
    public PageReference onRecall() { 
        if (MSA_ContractId != null) { 
            SBAA.ApprovalAPI.recall(MSA_ContractId, SBAA__Approval__c.MSA_Contract__c); 
        } 
        return new PageReference('/' + MSA_ContractId); 
    } 
}