unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/CompletenessReportSectionConfig__mdt.object-meta.xml
<CustomObject>
    <label>CompletenessReportSectionConfig</label>
    <pluralLabel>CompletenessReportSectionConfig</pluralLabel>
</CustomObject>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/App_Name__c.field-meta.xml
<CustomField>
    <fullName>App_Name__c</fullName>
    <description>This field values should be in sync with Prompt Information Object - Prompt Type field</description>
    <inlineHelpText>To get the respective prompt details in report</inlineHelpText>
    <label>App Name</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Asset Builder</fullName>
                <default>true</default>
                <label>Asset Builder</label>
            </value>
            <value>
                <fullName>Interface Builder</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Prompt_Type__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Type__c</fullName>
    <label>Prompt Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wind - Onshore</fullName>
                <default>true</default>
                <label>Wind - Onshore</label>
            </value>
            <value>
                <fullName>MetMast</fullName>
            </value>
            <value>
                <fullName>SubstationSwitchgear</fullName>
            </value>
            <value>
                <fullName>Solar - PV</fullName>
            </value>
            <value>
                <fullName>Wind - Offshore</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Report_Display_Order__c.field-meta.xml
<CustomField>
    <fullName>Report_Display_Order__c</fullName>
    <inlineHelpText>Report Section Display Order</inlineHelpText>
    <label>Report Section Display Order</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Section_Label__c.field-meta.xml
<CustomField>
    <fullName>Section_Label__c</fullName>
    <inlineHelpText>This field value is used as completeness report section label</inlineHelpText>
    <label>Section Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/CompletenessReportSectionConfig__mdt/fields/Summary_Report_First_Column_Label__c.field-meta.xml
<CustomField>
    <fullName>Summary_Report_First_Column_Label__c</fullName>
    <inlineHelpText>This field value will be used in completeness summary report first column label</inlineHelpText>
    <label>Summary Report First Column Label</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/CompletenessReportParent.cls
public with sharing class CompletenessReportParent {
    @AuraEnabled
    public Static String getCompletenessReportSection() {
        List<CompletenessReportSectionConfig__mdt> promptTypeLst  = new List<CompletenessReportSectionConfig__mdt>();
        for(CompletenessReportSectionConfig__mdt promptType : 
            [SELECT Id, App_Name__c, Prompt_Type__c, Section_Label__c, Report_Display_Order__c, 
            Summary_Report_First_Column_Label__c
            FROM CompletenessReportSectionConfig__mdt WHERE App_Name__c = 'Asset Builder'
            ORDER BY Report_Display_Order__c ASC]){
                promptTypeLst.add(promptType);
        }

        return JSON.serialize(promptTypeLst);
    }
}