unpackaged/main/default/objects/Attribute_Requirement__c/Attribute_Requirement__c.object-meta.xml
<CustomObject>
    <description>Stores the base asset&#39;s attribute requirement information to be fetched in prompt screens</description>
    <label>Attribute Requirement</label>
    <nameField>
        <label>Attribute Requirement Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attribute Requirements</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Requirement__c/fields/Core_Attribute__c.field-meta.xml
<CustomField>
    <fullName>Core_Attribute__c</fullName>
    <label>Core Attribute</label>
    <referenceTo>Core_Attribute__c</referenceTo>
    <relationshipLabel>Attribute Requirements</relationshipLabel>
    <relationshipName>Attribute_Requirements</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Requirement__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attribute Requirements</relationshipLabel>
    <relationshipName>Attribute_Requirements</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/Attribute_Value__c.object-meta.xml
<CustomObject>
    <label>Attribute Value</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Attribute Value Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Attribute Values</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Attribute_Value__c/fields/Attribute__c.field-meta.xml
<CustomField>
    <fullName>Attribute__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Attribute</label>
    <referenceTo>Core_Attribute__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Attribute_Value__c/fields/Site_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Site_Metadata__c</fullName>
    <label>Site Metadata</label>
    <referenceTo>Site_Metadata__c</referenceTo>
    <relationshipLabel>Attribute Values</relationshipLabel>
    <relationshipName>Attribute_Values</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Base_Asset_Template__c/Base_Asset_Template__c.object-meta.xml
<CustomObject>
    <description>The logical grouping of attributes configured to the lasest version for Assets to be implemented. This structure is used for the standards framework that PF applies to its SaaS platforms.</description>
    <label>Base Asset Template</label>
    <nameField>
        <label>Base Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Base Asset Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Base_Asset_Template__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Base Asset Templates</relationshipLabel>
    <relationshipName>Base_Asset_Templates</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/Core_Attribute__c.object-meta.xml
<CustomObject>
    <description>Individual building blocks of the templates used to create the structures for the final configuration. The components are the pieces that are to be configured during the phases of implementation.</description>
    <label>Attribute</label>
    <nameField>
        <label>Attribute Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Attributes</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Core_Attribute__c/fields/Base_Asset_Name__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>To link the attributes to the relevant Base Asset</description>
    <label>Base Asset Name</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Default_value__c.field-meta.xml
<CustomField>
    <fullName>Default_value__c</fullName>
    <label>Default value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Picklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Master__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Picklist Master</label>
    <referenceTo>Picklist_Master__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Core_Attributes</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Attributes</relationshipLabel>
    <relationshipName>Attributes</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Core_Attribute__c/recordTypes/Core_Attribute.recordType-meta.xml
<RecordType>
    <fullName>Core_Attribute</fullName>
    <active>true</active>
    <label>Core Attribute</label>
</RecordType>

unpackaged/main/default/objects/Picklist_Detail__c/Picklist_Detail__c.object-meta.xml
<CustomObject>
    <description>This object has all picklist values related to its picklist master E.g Time Zone is the picklist master and its time zone literals (values) like IST, PST, EST will be here in this object</description>
    <label>Picklist Detail</label>
    <nameField>
        <label>Picklist Value</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Picklist_Detail__c/fields/Picklist_Master__c.field-meta.xml
<CustomField>
    <fullName>Picklist_Master__c</fullName>
    <label>Picklist Master</label>
    <referenceTo>Picklist_Master__c</referenceTo>
    <relationshipLabel>Picklist Details</relationshipLabel>
    <relationshipName>Picklist_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/Picklist_Detail__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Picklist Details</relationshipLabel>
    <relationshipName>Picklist_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Picklist_Master__c/Picklist_Master__c.object-meta.xml
<CustomObject>
    <description>This object will have the picklist master details. E.g Time Zone. The time zone literals will be there in Picklist Details object</description>
    <label>Picklist Master</label>
    <nameField>
        <label>Picklist Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Picklist Master</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Picklist_Master__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Picklist Master</relationshipLabel>
    <relationshipName>Picklist_Masters</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/Plant_Asset_Prompt_Detail__c.object-meta.xml
<CustomObject>
    <description>Stores each and every Prompt details and link to the Site/Plant and Parent Prompt also this object will help for smooth navigation between prompts</description>
    <label>Plant Asset Prompt Detail</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Asset Prompt Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Base_Asset__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Plant_Asset_Prompt_Detail__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Plant Asset Prompt Details</relationshipLabel>
    <relationshipName>Plant_Asset_Prompt_Details</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/Prompt_Information__c.object-meta.xml
<CustomObject>
    <label>Prompt Information</label>
    <nameField>
        <label>Prompt Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Prompt Information</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Prompt_Information__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <lookupFilter>
        <active>true</active>
        <filterItems>
            <field>$Source.TEM_Version__c</field>
            <operation>equals</operation>
            <valueField>Base_Asset_Template__c.TEM_Version__r.Id</valueField>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Prompt_Information__c/fields/TEM_Version__c.field-meta.xml
<CustomField>
    <fullName>TEM_Version__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>TEM Version</label>
    <referenceTo>TEM_Version__c</referenceTo>
    <relationshipLabel>Prompt Information</relationshipLabel>
    <relationshipName>Prompt_Information</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/Site_Metadata__c.object-meta.xml
<CustomObject>
    <description>Stores prompt specific information like Inverters, Transformers, Turbines, etc… and its core attributes values</description>
    <label>Site Metadata</label>
    <nameField>
        <label>Site Metadata Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Site Metadata</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Site_Metadata__c/fields/Attribute_Info__c.field-meta.xml
<CustomField>
    <fullName>Attribute_Info__c</fullName>
    <label>Attribute Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Base_Asset_Template__c.field-meta.xml
<CustomField>
    <fullName>Base_Asset_Template__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Base Asset Template</label>
    <referenceTo>Base_Asset_Template__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Plant_Asset_Prompt_Detail__c.field-meta.xml
<CustomField>
    <fullName>Plant_Asset_Prompt_Detail__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Plant Asset Prompt Detail</label>
    <referenceTo>Plant_Asset_Prompt_Detail__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Information__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Information__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Prompt Information</label>
    <referenceTo>Prompt_Information__c</referenceTo>
    <relationshipLabel>Site Metadata</relationshipLabel>
    <relationshipName>Site_Metadata</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/Site_Metadata__c/fields/Prompt_Specific_Info__c.field-meta.xml
<CustomField>
    <fullName>Prompt_Specific_Info__c</fullName>
    <label>Prompt Specific Info</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

unpackaged/main/default/objects/TEM_Version__c/TEM_Version__c.object-meta.xml
<CustomObject>
    <label>TEM Version</label>
    <nameField>
        <displayFormat>VERSION-{000}</displayFormat>
        <label>Version Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>TEM Versions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/ReportDataHandlerTest.cls
/**
**/
@istest
public with sharing class ReportDataHandlerTest {
 /*   @testSetup
    public static void testDataSetup() {
        TEM_Version__c newTemVersion = TestDataFactory.createTemVersion(Constants.DRAFT);
        insert newTemVersion;

        Plant_Asset__c newPlantAsset1 = TestDataFactory.createPlantAsset(Constants.WIND, 'Drive', '7777.77.777', newTemVersion.Id);
        insert newPlantAsset1;

        Plant_Asset__c newPlantAsset2 = TestDataFactory.createPlantAsset(Constants.SOLAR, 'Drive', '7777.77.777', newTemVersion.Id);
        insert newPlantAsset2;

        Base_Asset_Template__c newBaseAssetTemplate1 = TestDataFactory.createBaseAssetTemplate(Constants.BASE_INVERTER_PAD, newTemVersion.Id);
        insert newBaseAssetTemplate1;

        Base_Asset_Template__c newBaseAssetTemplate2 = TestDataFactory.createBaseAssetTemplate(Constants.BASE_INVERTER_PAD, newTemVersion.Id);
        insert newBaseAssetTemplate2;

        Prompt_Information__c newPromptInfo1 = TestDataFactory.createPromptInformation(Constants.P3_PAD_BUILDS_AND_COUNTS,
                                                                                      newBaseAssetTemplate1.Id, newTemVersion.Id);
        insert newPromptInfo1;

        Prompt_Information__c newPromptInfo2 = TestDataFactory.createPromptInformation(Constants.P3_PAD_BUILDS_AND_COUNTS,
                                                                                      newBaseAssetTemplate2.Id, newTemVersion.Id);
        insert newPromptInfo2;

        Picklist_Master__c newPicklistMaster = TestDataFactory.createPicklistMaster('Test Master', newTemVersion.Id);
        insert newPicklistMaster;
        
        Picklist_Detail__c picklistDetailValue = TestDataFactory.createPicklistValue(newPicklistMaster.Id, newTemVersion.Id);
        insert picklistDetailValue;

        //for core attribute records
        List<Core_Attribute__c> coreAttrLst  = new List<Core_Attribute__c> ();
        list<String> datatypeLst = new list<String>{
            'Text','Number','Text','Text',
            'Text','Number','Text','Text',
            'Text','Number','Text','Text'
        };
        list<String> coreAttrNameLst = new list<String>{
            'Manufacturer','AC_Capacity','Tracker','Serial_Number',
            'Manufacturer2','AC_Capacity2','Tracker2','Serial_Number2',
            'Manufacturer3','AC_Capacity3','Tracker3','Serial_Number3'
        };

        Id coreAttrRTId = Utils.getRecordTypeInfo('Core_Attribute__c','Core_Attribute').getRecordTypeId();

        for(integer i = 0; i < coreAttrNameLst.size(); i++){
            Core_Attribute__c coreAttr = TestDataFactory.createCoreAttribute(coreAttrNameLst[i],
                                                                                'Metadata',
                                                                                datatypeLst[i],
                                                                                coreAttrRTId,
                                                                                (datatypeLst[i] == 'Picklist')? newPicklistMaster.Id : null,
                                                                                newBaseAssetTemplate1.Id, newTemVersion.Id);
            coreAttr.Base_Asset_Name__c = (math.mod(i,2) == 0) ? newBaseAssetTemplate1.Id : newBaseAssetTemplate2.Id;
            coreAttr.Default_Value__c = (math.mod(i,2) == 0) ? '2':'';
            coreAttrLst.add(coreAttr);
        }
        insert coreAttrLst;

        List<Attribute_Requirement__c> attrReqLst  = new List<Attribute_Requirement__c> ();
        for(integer i = 0; i < coreAttrNameLst.size(); i++){
            Attribute_Requirement__c attrReq1 = TestDataFactory.createAttributeRequirement('Drive','Yes',coreAttrLst[i].Id, newTemVersion.Id);
            attrReqLst.add(attrReq1);
            Attribute_Requirement__c attrReq2 = TestDataFactory.createAttributeRequirement('Drive','No',coreAttrLst[i].Id, newTemVersion.Id);
            attrReqLst.add(attrReq2);
            Attribute_Requirement__c attrReq3 = TestDataFactory.createAttributeRequirement('Drive Plus','Yes',coreAttrLst[i].Id, newTemVersion.Id);
            attrReqLst.add(attrReq3);
            Attribute_Requirement__c attrReq4 = TestDataFactory.createAttributeRequirement('Drive Plus','No',coreAttrLst[i].Id, newTemVersion.Id);
            attrReqLst.add(attrReq4);
        }
        insert attrReqLst;

        Plant_Asset_Prompt_Detail__c p1PlantAssetPromptDetail1 = new Plant_Asset_Prompt_Detail__c();
        p1PlantAssetPromptDetail1.Name = newPlantAsset1.Name +'-'+ newPromptInfo1.Name;
        p1PlantAssetPromptDetail1.Plant_Asset__c = newPlantAsset1.Id;
        p1PlantAssetPromptDetail1.Prompt_Information__c = newPromptInfo1.Id;
        p1PlantAssetPromptDetail1.Base_Asset__c = newBaseAssetTemplate1.Id;
        insert p1PlantAssetPromptDetail1;

        Plant_Asset_Prompt_Detail__c p1PlantAssetPromptDetail2 = new Plant_Asset_Prompt_Detail__c();
        p1PlantAssetPromptDetail2.Name = newPlantAsset2.Name +'-'+ newPromptInfo2.Name;
        p1PlantAssetPromptDetail2.Plant_Asset__c = newPlantAsset2.Id;
        p1PlantAssetPromptDetail2.Prompt_Information__c = newPromptInfo2.Id;
        p1PlantAssetPromptDetail2.Base_Asset__c = newBaseAssetTemplate2.Id;
        insert p1PlantAssetPromptDetail2;

        Site_Metadata__c siteMetaData1 = new Site_Metadata__c(); 
        siteMetaData1.Name = Constants.P1_PLANT_INFO_PROMPT_SOLAR;
        siteMetaData1.Prompt_Specific_Info__c = '{"noOfBlocks":"","Flat Hierarchy":"No","drivePlus":"true"}';
        siteMetaData1.Attribute_Info__c = '{\"Manufacturer\":\"4\",\"AC_Capacity\":\"8\",\"Tracker\":\"8\",\"Serial_Number\":\"8\"}';
        siteMetaData1.Base_Asset_Template__c = newBaseAssetTemplate1.Id;
        siteMetaData1.Plant_Asset__c = newPlantAsset1.id;
        siteMetaData1.Plant_Asset_Prompt_Detail__c = p1PlantAssetPromptDetail1.Id;
        insert siteMetaData1;

        Site_Metadata__c siteMetaData2 = new Site_Metadata__c(); 
        siteMetaData2.Name = Constants.P1_PLANT_INFO_PROMPT_SOLAR;
        siteMetaData2.Prompt_Specific_Info__c = '{"noOfBlocks":"","Flat Hierarchy":"No","drivePlus":"true"}';
        siteMetaData2.Attribute_Info__c = '{\"Manufacturer\":\"4\",\"AC_Capacity\":\"8\",\"Tracker\":\"8\",\"Serial_Number\":\"8\"}';
        siteMetaData2.Base_Asset_Template__c = newBaseAssetTemplate2.Id;
        siteMetaData2.Plant_Asset__c = newPlantAsset2.id;
        siteMetaData2.Plant_Asset_Prompt_Detail__c = p1PlantAssetPromptDetail2.Id;
        insert siteMetaData2;

        List<Attribute_Value__c> attrValueLst = new List<Attribute_Value__c>();
        for(integer i = 0; i < 2; i++){
            for(integer j = 0; j < coreAttrNameLst.size(); j++){
                Attribute_Value__c attributeValue = new Attribute_Value__c();
                attributeValue.Plant_Asset__c = (i == 0) ? newPlantAsset1.Id : newPlantAsset2.Id;
                attributeValue.Site_Metadata__c = (i == 0) ? siteMetaData1.Id : siteMetaData2.Id;
                attributeValue.Prompt_Information__c = (i == 0) ? newPromptInfo1.Id : newPromptInfo2.Id; 
                attributeValue.Base_Asset_Template__c = (i == 0) ? newBaseAssetTemplate1.Id : newBaseAssetTemplate2.Id;
                attributeValue.Value__c = (math.mod(j,2) == 0) ? '3' : '';
                attributeValue.Attribute__c = coreAttrLst[j].Id;
                attrValueLst.add(attributeValue);
            }
        }
        
        if(attrValueLst.size() > 0){
            insert attrValueLst;
        }
    }

    public static testMethod void assetReportCreationTestMtd(){
        Plant_Asset__c plantAsset = [SELECT Id FROM Plant_Asset__c WHERE Renewable_Type__c = :Constants.WIND LIMIT 1];
        List<Id> promptInfo = new List<Id>();
        ReportDataHandler ReportDataHandlerCls = new ReportDataHandler();
        ReportDataHandlerCls.queryExsistingReportData(plantAsset.Id, promptInfo);
    }*/
}