unpackaged/main/default/objects/QS_Customer_Asset__c/QS_Customer_Asset__c.object-meta.xml
<CustomObject>
    <description>A summarization of the customer&#39;s currently-owned products.</description>
    <label>Purchased Product</label>
    <nameField>
        <label>Customer Asset Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Purchased Products</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Account__c.field-meta.xml
<CustomField>
    <fullName>QS_Account__c</fullName>
    <description>Indicates the account that is primarily associated with the customer asset. This is the account that purchased the product.</description>
    <inlineHelpText>Indicates the account that is primarily associated with the customer asset. This is the account that purchased the product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>QS_Customer_Assets</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_End_Date__c</fullName>
    <description>Roll-up field displaying the latest end date amongst all the CATs. This field changes as products are added or renewed.</description>
    <inlineHelpText>Roll-up field displaying the latest end date amongst all the CATs. This field changes as products are added or renewed.</inlineHelpText>
    <label>End Date</label>
    <summarizedField>QS_Customer_Asset_Detail__c.QS_End_Date__c</summarizedField>
    <summaryForeignKey>QS_Customer_Asset_Detail__c.QS_Customer_Asset__c</summaryForeignKey>
    <summaryOperation>max</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_New_Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>QS_New_Asset_Status__c</fullName>
    <formula>IF(
AND(QS_Start_Date__c &gt; QS_Dynamic_Current_Date__c) , &#39;Pending Activation&#39;, 
IF(AND(QS_Start_Date__c &lt;= QS_Dynamic_Current_Date__c,  QS_Quantity__c &gt; 0), &#39;Active&#39;, 
IF(AND(QS_Quantity__c = 0,  QS_Start_Date__c &lt;= QS_Dynamic_Current_Date__c),&#39;Decommissioned&#39;, 
&#39;Error Occurred&#39; 
)
) 
)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset__c/fields/QS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_Start_Date__c</fullName>
    <description>Roll-up field displaying the earliest start date of all Customer Asset Transactions for this product. This field shows when the customer first purchased the product. This date never changes. Start Date must be populated on at least one CAT.</description>
    <inlineHelpText>Roll-up field displaying the earliest start date of all Customer Asset Transactions for this product. This field shows when the customer first purchased the product. This date never changes. Start Date must be populated on at least one CAT.</inlineHelpText>
    <label>Start Date</label>
    <summarizedField>QS_Customer_Asset_Detail__c.QS_Start_Date__c</summarizedField>
    <summaryForeignKey>QS_Customer_Asset_Detail__c.QS_Customer_Asset__c</summaryForeignKey>
    <summaryOperation>min</summaryOperation>
    <type>Summary</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/QS_Customer_Asset_Detail__c.object-meta.xml
<CustomObject>
    <description>Transnational detail that feeds the Customer Assets
		Start/End Dates, ARR</description>
    <label>Subscription Transaction</label>
    <nameField>
        <displayFormat>CAT-{0000000}</displayFormat>
        <label>Subscription Transaction No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Subscription Transactions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Account__c.field-meta.xml
<CustomField>
    <fullName>QS_Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The customer who owns the product.</description>
    <inlineHelpText>The customer who owns the product.</inlineHelpText>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipName>Customer_Asset_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Customer_Asset__c.field-meta.xml
<CustomField>
    <fullName>QS_Customer_Asset__c</fullName>
    <description>Master-Detail lookup to the parent Customer Asset record.</description>
    <inlineHelpText>Master-Detail lookup to the parent Customer Asset record.</inlineHelpText>
    <label>Customer Asset</label>
    <referenceTo>QS_Customer_Asset__c</referenceTo>
    <relationshipName>QS_Customer_Asset_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_End_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_End_Date__c</fullName>
    <description>The End Date of the source Subscription. This is blank when the CAP source is an Asset (non-recurring product).</description>
    <inlineHelpText>The End Date of the source Subscription. This is blank when the CAP source is an Asset (non-recurring product).</inlineHelpText>
    <label>End Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_New_Asset_Status__c.field-meta.xml
<CustomField>
    <fullName>QS_New_Asset_Status__c</fullName>
    <formula>IF(
			QS_Quantity__c &gt; 0 &amp;&amp; QS_Start_Date__c&gt; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c, &#39;Pending Activation&#39;,
			IF(
			QS_Quantity__c &gt; 0 &amp;&amp;
			QS_Start_Date__c &lt;= QS_Customer_Asset__r.QS_Dynamic_Current_Date__c
			&amp;&amp; (QS_End_Date__c &gt;= QS_Customer_Asset__r.QS_Dynamic_Current_Date__c||
			ISBLANK(QS_End_Date__c))
			, &#39;Active&#39;,



			IF(
			(QS_Customer_Asset__r.QS_Dynamic_Current_Date__c  &lt; QS_Terminated_Date__c +1) ||
			(QS_Quantity__c = 0 &amp;&amp; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c &lt; QS_Start_Date__c)

			, &#39;Pending Decommission&#39;,
			IF(
			(QS_Customer_Asset__r.QS_Dynamic_Current_Date__c &gt;= QS_Terminated_Date__c +1) ||
			(QS_Quantity__c = 0 &amp;&amp; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c &gt;= QS_Start_Date__c),
			&#39;Decommissioned&#39;,
			IF(
			QS_Quantity__c &lt; 0 &amp;&amp; QS_Start_Date__c&gt; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c, &#39;Pending Reduction&#39;,
			IF(
			QS_Quantity__c &lt; 0 &amp;&amp; QS_Start_Date__c &lt;= QS_Customer_Asset__r.QS_Dynamic_Current_Date__c, &#39;Reduced&#39;,
			IF(
			QS_End_Date__c &lt; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c &amp;&amp; ISBLANK(QS_Renewed_Date__c) &amp;&amp; !QS_Is_Renewal_Closed__c &amp;&amp; !QS_Migrated_No_Renewal__c &amp;&amp; QS_Is_Last_Segment__c, &#39;Pending Renewal&#39;,

			IF(
			QS_End_Date__c &lt; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c &amp;&amp;
			(
			(ISBLANK(QS_Renewed_Date__c) &amp;&amp; QS_Migrated_No_Renewal__c) ||
			(QS_Is_Renewal_Closed__c &amp;&amp; QS_Is_Last_Segment__c)
			), &#39;Expired&#39;,
			IF(QS_End_Date__c &lt; QS_Customer_Asset__r.QS_Dynamic_Current_Date__c &amp;&amp; NOT(QS_Is_Last_Segment__c),&#39;Expired&#39;,
			&#39;Invalid Status&#39;
			)))))))))</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Asset Status</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/QS_Customer_Asset_Detail__c/fields/QS_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>QS_Start_Date__c</fullName>
    <description>The start date from the source Quote Line for this CAT.</description>
    <inlineHelpText>The start date from the source Quote Line for this CAT.</inlineHelpText>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/classes/QS_BatchSimulatorCtrlTest.cls
@isTest
public class QS_BatchSimulatorCtrlTest {
	
    @TestSetup
    public static void testData(){
        Account account = new Account();
        account.Name = 'Test acctName';
        account.BillingCountry = 'United States';
        insert account;
        
        QS_Customer_Asset__c qcAsset = new QS_Customer_Asset__c ();
        qcAsset.Name = 'Test';
        qcAsset.QS_Account__c = account.id;
        insert qcAsset;
        
        QS_Customer_Asset_Detail__c acAssetDetail = new QS_Customer_Asset_Detail__c();
        acAssetDetail.QS_Customer_Asset__c = qcAsset.Id;
        //acAssetDetail.QS_New_Asset_Status__c = 'Expired';
        insert acAssetDetail;
        
    }
    @isTest
    public static void method01(){
        Test.startTest();
        
		QS_Customer_Asset__c qcAsset = [SELECT Id FROM QS_Customer_Asset__c LIMIT 1];
        
        QS_BatchSimulatorCtrl.initializeData(qcAsset.id);
        
        QS_BatchSimulatorCtrl.runBatchProcessByDate(qcAsset.id , system.today());
        
        QS_Customer_Asset_Detail__c qac = [SELECT Id FROM QS_Customer_Asset_Detail__c LIMIT 1];
        
        qac.QS_End_Date__c = system.today().addDays(-10);
        update qac;
        QS_BatchSimulatorCtrl.runBatchProcessByDate(qcAsset.id , system.today());
        
        qac.QS_End_Date__c = system.today().addDays(10);
        qac.QS_Start_Date__c = system.today().addDays(10);
        update qac;
        QS_BatchSimulatorCtrl.runBatchProcessByDate(qcAsset.id , system.today());
        
		qac.QS_End_Date__c = system.today().addDays(10);
        qac.QS_Start_Date__c = system.today().addDays(-10);
        update qac;
        QS_BatchSimulatorCtrl.runBatchProcessByDate(qcAsset.id , system.today());        
        
        Test.stopTest();
    }
}