unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Billing_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Billing_Start_Date__c</fullName>
    <label>Billing Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Deployment_date__c.field-meta.xml
<CustomField>
    <fullName>Deployment_date__c</fullName>
    <label>Deployment date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Implementation_Start_Date__c.field-meta.xml
<CustomField>
    <fullName>Implementation_Start_Date__c</fullName>
    <formula>IF(ISBLANK(Project_Name__c),Manual_Entry_Implementation_Start_Date__c,  Project_Name__r.Implementation_start_date__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Implementation Start Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Installation_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Commencement_Date__c</fullName>
    <label>Installation Commencement Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Product__r.Product_Line__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Project_Name__c.field-meta.xml
<CustomField>
    <fullName>Project_Name__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Project Name</label>
    <referenceTo>project_cloud__Project__c</referenceTo>
    <relationshipLabel>Plant Product Transactions</relationshipLabel>
    <relationshipName>Plant_Product_Transactions</relationshipName>
    <type>Lookup</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Deployment_Date__c.field-meta.xml
<CustomField>
    <fullName>Deployment_Date__c</fullName>
    <description>Auto-Populated - First time only when Internal Status changes to Completed, Completed - Work Open or Completed - historical data import.</description>
    <label>Deployment Date</label>
    <type>Date</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Implementation_start_date__c.field-meta.xml
<CustomField>
    <fullName>Implementation_start_date__c</fullName>
    <label>Implementation start date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Installation_Commencement_Date__c.field-meta.xml
<CustomField>
    <fullName>Installation_Commencement_Date__c</fullName>
    <label>Installation Commencement Date</label>
    <type>DateTime</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/fields/Product_Family__c.field-meta.xml
<CustomField>
    <fullName>Product_Family__c</fullName>
    <label>Product Family</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/classes/PPTBillingTriggerBatchApex.cls
global class PPTBillingTriggerBatchApex implements Database.Batchable<sObject>
{
    global Database.QueryLocator start(Database.BatchableContext BC)
    {
        
        String query = 'SELECT Id,Name,Product_Category__c,Product_Family__c,Product_Line__c,Effective_Date__c,Billing_Start_Date__c,Implementation_Start_Date__c,'+
                        ' Deployment_date__c,Installation_Commencement_Date__c,Project_Name__c,Project_Name__r.Implementation_Start_Date__c FROM Plant_Product_Transaction__c '+ 
                        System.Label.PPTBillingTriggerSoql;
                        // +System.Label.BatchApexAutocreateProjectSoql where Product_Line__c != null AND Product_Family__c != null AND  Product_Category__c != null
       	system.debug('::query::'+query);
        return Database.getQueryLocator(query);
    }
    global void execute(Database.BatchableContext BC, List<Plant_Product_Transaction__c> scope)
    {
        list<Plant_Product_Transaction__c> updatePPTList = new list<Plant_Product_Transaction__c>();
        set<id>projectIdSet = new set<id>();
        for(Plant_Product_Transaction__c pptRec : scope){  
            system.debug('---pptRec---'+pptRec);
            //Criteria to populate Billing_Start_Date__c from Installation commencement Date    
           if((pptRec.Product_Category__c == 'Professional Services' &&  pptRec.Product_Family__c == 'Greenbyte') && ( pptRec.Product_Line__c =='Add-ons' || pptRec.Product_Line__c =='Core')){
            pptRec.Billing_Start_Date__c = pptRec.Implementation_Start_Date__c;
            updatePPTList.add(pptRec);
           }
           //Criteria to populate Billing_Start_Date__c from Implementation Start Date
           if((pptRec.Product_Family__c == 'Drive' && pptRec.Product_Category__c == 'Professional Services') && (pptRec.Product_Line__c =='Pro' || pptRec.Product_Line__c =='Core') ){
            system.debug('-----pptRec.Project_Name__r.Implementation_Start_Date__c;----'+pptRec.Project_Name__r.Implementation_Start_Date__c);
            pptRec.Billing_Start_Date__c = pptRec.Implementation_Start_Date__c;
            updatePPTList.add(pptRec);
           }
           //Criteria to populate Billing_Start_Date__c from Effective Date
           if(((pptRec.Product_Family__c == 'Ekhosoft' && pptRec.Product_Line__c =='Ekho') && (pptRec.Product_Category__c == 'Software' || pptRec.Product_Category__c == 'license')) ||
                (pptRec.Product_Family__c == 'Greenbyte' && pptRec.Product_Line__c =='Customer Success' && pptRec.Product_Category__c =='Professional Services')){
                pptRec.Billing_Start_Date__c = pptRec.Effective_Date__c;
                updatePPTList.add(pptRec);
           }
           //Criteria to populate Billing_Start_Date__c from Discussion Pending
           if(((pptRec.Product_Family__c == 'BluePoint' && pptRec.Product_Category__c == 'Software') && (pptRec.Product_Line__c == 'Bluepoint' || pptRec.Product_Line__c == 'Core' || pptRec.Product_Line__c == 'Enterprise' || pptRec.Product_Line__c == 'Pro'))){
                pptRec.Billing_Start_Date__c = pptRec.Deployment_date__c;
                updatePPTList.add(pptRec);
           }
           if((pptRec.Product_Family__c == 'BluePoint' && pptRec.Product_Category__c == 'Professional Services' && pptRec.Product_Line__c == 'Bluepoint')){
               pptRec.Billing_Start_Date__c = pptRec.Implementation_Start_Date__c;
               updatePPTList.add(pptRec);
           }
           //Criteria to populate Billing_Start_Date__c from Deployment Date
           if(
            ((pptRec.Product_Family__c == 'Drive' && pptRec.Product_Category__c == 'Software') && (pptRec.Product_Line__c == 'Add-ons' || pptRec.Product_Line__c == 'Core' || pptRec.Product_Line__c == 'Core Lite' || pptRec.Product_Line__c == 'O&M' || pptRec.Product_Line__c == 'Pro')) ||
           ((pptRec.Product_Family__c == 'Drive' && pptRec.Product_Category__c == 'Professional Services') && (pptRec.Product_Line__c == 'Add-ons' || pptRec.Product_Line__c == 'Customer Success'||pptRec.Product_Line__c == 'O&M')) ||
            (pptRec.Product_Family__c == 'Drive' && pptRec.Product_Category__c == 'Hardware' && pptRec.Product_Line__c == 'Customer Success') ||
            (pptRec.Product_Family__c == 'Ekhosoft' && pptRec.Product_Category__c == 'Professional Services' && pptRec.Product_Line__c == 'Ekho') ||
            ((pptRec.Product_Family__c == 'Greenbyte' && pptRec.Product_Category__c == 'Software') && (pptRec.Product_Line__c == 'Add-ons'|| pptRec.Product_Line__c == 'Breeze Development'|| pptRec.Product_Line__c == 'Core')) ||
            (pptRec.Product_Family__c == 'Greenbyte' && pptRec.Product_Category__c == 'Professional Services' && pptRec.Product_Line__c == 'Breeze Development')){
                pptRec.Billing_Start_Date__c = pptRec.Deployment_date__c;
                updatePPTList.add(pptRec);
           }

        }
        if(updatePPTList.size() > 0 && updatePPTList != null){
            system.debug('---updatePPTList.size()---'+updatePPTList.size());
            system.debug('---updatePPTList---'+updatePPTList);
            update updatePPTList;
        }
        
    }
    global void finish(Database.BatchableContext BC) {
    }
}