unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Project_Creation_Status__c.field-meta.xml
<CustomField>
    <fullName>Project_Creation_Status__c</fullName>
    <label>Project Creation Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>&quot;Software</fullName>
                <isActive>false</isActive>
                <label>&quot;Software</label>
            </value>
            <value>
                <fullName>Professional Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Professional Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Services_Short_Name__c.field-meta.xml
<CustomField>
    <fullName>Services_Short_Name__c</fullName>
    <label>Services Short Name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Project_Template__c/Project_Template__c.object-meta.xml
<CustomObject>
    <label>Project Template</label>
    <nameField>
        <label>Project Template Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Project Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/classes/BatchApexAutocreateProjectsTest.cls
/**
 * The Test class for batch apex BatchApexAutocreateProjects.   
 * @param  :  
 * @return :  
 */
@isTest
public with sharing class BatchApexAutocreateProjectsTest {
    static testmethod void testCommissionedProject() {
        //Create product with product having project template
        Product2 pr = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');
        insert pr;
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
        project_cloud__Project__c commTemplate = TestDataFactory.createCCProjectTemplate('Monitoring Implementation',accnt.Id);
        insert commTemplate;
        project_cloud__Project__c deCommTemplate = TestDataFactory.createCCProjectTemplate('Monitoring Decommissioning',accnt.Id);
        insert deCommTemplate;
        Project_Template__c proTemplate =  TestDataFactory.createProjectTemplate(pr.Id, commTemplate.Id, deCommTemplate.Id);
        insert proTemplate;
        system.debug('::proTemplate::'+proTemplate);
        Plant_Product_Transaction__c ppt1 = TestDataFactory.createPPT('Ordered', accnt.Id, pr.Id);
        insert ppt1;
        Plant_Product_Transaction__c ppt2 = TestDataFactory.createPPT('Contracted', accnt.Id, pr.Id);
        insert ppt2;
        Test.startTest();
            BatchApexAutocreateProjects c = new BatchApexAutocreateProjects();
            Database.executeBatch(c);
        Test.stopTest();
        Plant_Product_Transaction__c pptProcessed = [select Project_Creation_Status__c from Plant_Product_Transaction__c where id =:ppt1.id];
        System.assertEquals('Completed',pptProcessed.Project_Creation_Status__c);
        system.debug('---ppt1---'+ppt1);
    }
    static testmethod void testDecommissionedProject() {
        //Create product with product having project template
        Product2 pr = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');
        pr.Product_Category__c = 'Software';
        pr.Services_Short_Name__c = 'Test Short Name of Product';
        insert pr;
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
        project_cloud__Project__c commTemplate = TestDataFactory.createCCProjectTemplate('Monitoring Implementation',accnt.Id);
        insert commTemplate;
        project_cloud__Project__c deCommTemplate = TestDataFactory.createCCProjectTemplate('Monitoring Decommissioning',accnt.Id);
        insert deCommTemplate;
        Project_Template__c proTemplate =  TestDataFactory.createProjectTemplate(pr.Id, commTemplate.Id, deCommTemplate.Id);
        insert proTemplate;
        system.debug('::proTemplate2::'+proTemplate);
        Plant_Product_Transaction__c ppt3 = TestDataFactory.createPPT('Decommissioned', accnt.Id, pr.Id);
        insert ppt3;
        
        Test.startTest();
            BatchApexAutocreateProjects c = new BatchApexAutocreateProjects();
            Database.executeBatch(c);
        Test.stopTest();
        Plant_Product_Transaction__c pptProcessed = [select Project_Creation_Status__c from Plant_Product_Transaction__c where id =:ppt3.id];
        System.assertEquals('Completed',pptProcessed.Project_Creation_Status__c);
    }
}