unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Is_Project_Added__c.field-meta.xml
<CustomField>
    <fullName>Is_Project_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Project Added</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <formula>TEXT(Product__r.Product_Category__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Category</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <formula>TEXT(Product__r.Product_Line__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Product Line</label>
    <type>Text</type>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Category__c.field-meta.xml
<CustomField>
    <fullName>Product_Category__c</fullName>
    <label>Product Category</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Software</fullName>
            </value>
            <value>
                <fullName>Hardware</fullName>
            </value>
            <value>
                <fullName>Professional Services</fullName>
            </value>
            <value>
                <fullName>&quot;Software</fullName>
                <isActive>false</isActive>
                <label>&quot;Software</label>
            </value>
            <value>
                <fullName>Professional Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Professional Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/Product2/fields/Product_Line__c.field-meta.xml
<CustomField>
    <fullName>Product_Line__c</fullName>
    <label>Product Line</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Core</fullName>
            </value>
            <value>
                <fullName>Pro</fullName>
            </value>
            <value>
                <fullName>O&amp;M</fullName>
            </value>
            <value>
                <fullName>Bluepoint</fullName>
            </value>
            <value>
                <fullName>Add-ons</fullName>
            </value>
            <value>
                <fullName>Breeze Development</fullName>
            </value>
            <value>
                <fullName>Core Lite</fullName>
            </value>
            <value>
                <fullName>Ekho</fullName>
            </value>
            <value>
                <fullName>Edge Services</fullName>
            </value>
            <value>
                <fullName>Customer Success</fullName>
            </value>
            <value>
                <fullName>Enterprise</fullName>
            </value>
            <value>
                <fullName>&quot;Core</fullName>
                <isActive>false</isActive>
                <label>&quot;Core</label>
            </value>
            <value>
                <fullName>Edge Services&quot;</fullName>
                <isActive>false</isActive>
                <label>Edge Services&quot;</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/project_cloud__Project__c/fields/project_cloud__IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>project_cloud__IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if this project can be used as a Project Template</description>
    <inlineHelpText>When checked, indicates that the project is a template.</inlineHelpText>
    <label>Project Template</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/PPTBillingTrigger_Test.cls
@isTest
public class PPTBillingTrigger_Test {
    static testmethod void testAddPPT() {
        Product2 pr = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');        
        insert pr;
        Product2 pr1 = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');  
        pr1.Product_Category__c = 'Professional Services';
        pr1.Product_Line__c = 'Add-ons';
        pr1.Family = 'Greenbyte';
        insert pr1;
        
        Product2 pr2 = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');        
        pr2.Product_Category__c = 'Software';
        pr2.Product_Line__c = 'Ekho';
        pr2.Family = 'Ekhosoft';
        insert pr2;
        Product2 pr3 = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');        
        pr3.Product_Category__c = 'Software';
        pr3.Product_Line__c = 'Core Lite';
        pr3.Family = 'Drive';
        insert pr3;
        
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
        
        Plant_Product_Transaction__c ppt1 = TestDataFactory.createPPT('Ordered', accnt.Id, pr.Id);
        insert ppt1;
        
        Plant_Product_Transaction__c ppt2 = TestDataFactory.createPPT('Ordered', accnt.Id, pr1.Id);
        Insert ppt2;
            
        Plant_Product_Transaction__c ppt3 = TestDataFactory.createPPT('Ordered', accnt.Id, pr2.Id);
        Insert ppt3;
       
        Plant_Product_Transaction__c ppt4 = TestDataFactory.createPPT('Ordered', accnt.Id, pr3.Id);
        Insert ppt4;
            
        project_cloud__Project__c projectRecord = TestDataFactory.createCCProjectTemplate('Monitoring Implementation',accnt.Id);
        projectRecord.project_cloud__IsTemplate__c = true;
        insert projectRecord;
        List<string> pptIds = new List<string>();
        pptIds.add(ppt1.Id);
        Test.startTest();
        PPTBillingTriggerBatchApex msaBatch = new PPTBillingTriggerBatchApex ();		
		Database.executebatch(msaBatch);
        Test.stopTest();
        Plant_Product_Transaction__c pptProcessed = [select Is_Project_Added__c from Plant_Product_Transaction__c where id =:ppt1.Id];
        system.debug('::pptProcessed'+pptProcessed);
        
    }
    
}