unpackaged/main/default/objects/Plant_Product_Transaction__c/Plant_Product_Transaction__c.object-meta.xml
<CustomObject>
    <description>Junction object</description>
    <label>Plant Product Transaction</label>
    <nameField>
        <label>Plant Product Transaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Plant Product Transactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/Plant_Product_Transaction__c/fields/Is_Project_Added__c.field-meta.xml
<CustomField>
    <fullName>Is_Project_Added__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Project Added</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/objects/project_cloud__Project__c/project_cloud__Project__c.object-meta.xml
<CustomObject>
    <description>Top level information about the project such as the name of the project, project manager, and project start and end dates.</description>
    <label>Project</label>
    <nameField>
        <label>Project Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/main/default/objects/project_cloud__Project__c/fields/project_cloud__IsTemplate__c.field-meta.xml
<CustomField>
    <fullName>project_cloud__IsTemplate__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this box if this project can be used as a Project Template</description>
    <inlineHelpText>When checked, indicates that the project is a template.</inlineHelpText>
    <label>Project Template</label>
    <type>Checkbox</type>
</CustomField>

unpackaged/main/default/classes/AddPPTControllerV2Test.cls
/**
 * The Test class for apex AddPPTControllerV2Test.   
 * @param  :  
 * @return :  
 */
@isTest
public class AddPPTControllerV2Test {
    static testmethod void testAddPPT() {
        Product2 pr = TestDataFactory.createProductWithCode('DR-PR-PS-OT-IM-ST-ST-N/A');
        insert pr;
        Pricebook2 pb = TestDataFactory.createPriceBook();
        insert pb;
        Account accnt = TestDataFactory.createAccount(pb.Id);
        insert accnt;
        Plant_Product_Transaction__c ppt1 = TestDataFactory.createPPT('Ordered', accnt.Id, pr.Id);
       
        insert ppt1;
        project_cloud__Project__c projectRecord = TestDataFactory.createCCProjectTemplate('Monitoring Implementation',accnt.Id);
        projectRecord.project_cloud__IsTemplate__c = true;
        insert projectRecord;
        List<string> pptIds = new List<string>();
        pptIds.add(ppt1.Id);
        Test.startTest();
        	AddPPTControllerV2.getExistingPPTList(projectRecord.id);
        	AddPPTControllerV2.addProjects(projectRecord.id, JSON.serialize(pptIds));
        Test.stopTest();
        Plant_Product_Transaction__c pptProcessed = [select Is_Project_Added__c from Plant_Product_Transaction__c where id =:ppt1.Id];
        system.debug('::pptProcessed'+pptProcessed);
        System.assertEquals(true,pptProcessed.Is_Project_Added__c);
    }
}